/* Level overlay code after unclassified; generated by `decomp overlays stubs`, stubs replaced by C as functions are matched. */
#include "types.h"
#include "asm.h"
#include "rnc/storage/disc_table.h"

#define NOT_SDA

#define MACRO_ADDR

#include "qcopy.h"

/* Ported from rac1-decomp (src/overlays/shared/vendor_0029FD68.c: func_L00_002A0C20), where it is exact; names translated to the US level program. */

typedef struct {
    float v[4][4];
    int rgba[4];
    float uv[4][2];
    long gs[4];
} QuadPkt;

extern float D_L00_001CA318[][4];
extern float vector_length_xyz(void *);
extern int get_effect_texture(int) __asm__("FUN_001f44b8");
extern void project_graphics_bounds_float(void *, void *, float *, float *, float *,
                                          float *) __asm__("FUN_00237c80");
extern void add_vector_xyz(void *, void *, void *);
extern void draw_geometry_quad(void *, void *, int);
extern void normalize_vector_xyz(void *, void *, float);
extern void subtract_vector_xyz(void *, void *, void *);
extern void transform_scaled_vertex_batch(char *arg0, int arg1, void *arg2,
                                          char *arg3) __asm__("FUN_0020cd48");
extern void vu1_add_g_sregister(int, long);

void FUN_L00_0029f990(char *m) {
    float A[4];
    float B[4];
    float C[4];
    float P[3][4];
    int idx[3];
    float E[4];
    QuadPkt q;
    float g[4];
    float f;
    int i;
    float one = 1.0f;
    float uvv = 0.984375f;
    for (i = 1; i < 6; i++) {
        idx[0] = i * 4;
        idx[1] = i * 4 + 1;
        idx[2] = i * 4 + 2;
        transform_scaled_vertex_batch(m, 3, idx, (char *)P);
        qcopy(C, P[0]);
        subtract_vector_xyz(A, P[1], P[0]);
        subtract_vector_xyz(B, P[2], P[0]);
        f = vector_length_xyz(A);
        normalize_vector_xyz(E, A, D_L00_001CA318[i][0]);
        add_vector_xyz(C, C, E);
        normalize_vector_xyz(A, A, f - D_L00_001CA318[i][2] * 2.0f);
        f = vector_length_xyz(B);
        normalize_vector_xyz(E, B, D_L00_001CA318[i][1]);
        add_vector_xyz(C, C, E);
        normalize_vector_xyz(B, B, f - D_L00_001CA318[i][3] * 2.0f);
        add_vector_xyz(E, C, A);
        add_vector_xyz(E, E, B);
        project_graphics_bounds_float(C, E, &g[0], &g[1], &g[2], &g[3]);
        qcopy(q.v[0], C);
        add_vector_xyz(q.v[1], C, A);
        add_vector_xyz(q.v[2], C, B);
        add_vector_xyz(q.v[3], q.v[2], A);
        q.gs[0] = 5;
        q.gs[2] = 1;
        q.gs[3] = 0x8000000044L;
        q.rgba[0] = 0x80808080;
        q.rgba[1] = 0x80808080;
        q.rgba[2] = 0x80808080;
        q.rgba[3] = 0x80808080;
        q.gs[1] = get_effect_texture(0x19);
        q.v[0][3] = one;
        q.v[1][3] = one;
        q.v[2][3] = one;
        q.v[3][3] = one;
        q.uv[0][0] = 0;
        q.uv[0][1] = 0;
        q.uv[1][0] = uvv;
        q.uv[1][1] = 0;
        q.uv[2][0] = 0;
        q.uv[2][1] = uvv;
        q.uv[3][0] = uvv;
        q.uv[3][1] = uvv;
        vu1_add_g_sregister(0x47, 0x32003);
        draw_geometry_quad(&q, 0, 1);
    }
}
#include "qcopy.h"
#include "rnc/overlay/quad.h"
typedef struct {
    int a, b, c;
} I3_29fcd0;
extern I3_29fcd0 D_L00_00161178_29fcd0 __asm__("D_L00_00161178") __attribute__((section(".data")));
extern long D_0015EED0_29fcd0 __asm__("D_0015EED0");
void FUN_0020cd48_29fcd0(void *, int, void *, void *) __asm__("FUN_0020cd48");
void FUN_001f9a28_29fcd0(void *, void *, void *) __asm__("FUN_001f9a28");
float FUN_001f9af0_29fcd0(void *) __asm__("FUN_001f9af0");
void FUN_001f9bf8_29fcd0(void *, void *, float) __asm__("FUN_001f9bf8");
void FUN_001f9a10_29fcd0(void *, void *, void *) __asm__("FUN_001f9a10");
void FUN_00237a78_29fcd0(void *, void *, int *, int *, int *, int *) __asm__("FUN_00237a78");
void FUN_00239690_29fcd0(int, int, float) __asm__("FUN_00239690");
void FUN_001fb740_29fcd0(int, int) __asm__("FUN_001fb740");
void FUN_00233980_29fcd0(int, long) __asm__("FUN_00233980");
void FUN_L00_0029ead8_29fcd0(void *, int, int) __asm__("FUN_L00_0029ead8");
void FUN_00239328_29fcd0(int, float, float) __asm__("FUN_00239328");
void FUN_001f7978_29fcd0(void) __asm__("FUN_001f7978");
void FUN_0020d330_29fcd0(void *, int) __asm__("FUN_0020d330");
void FUN_001f5450_29fcd0(int, int, int, int, int, int, int, int, long,
                         long) __asm__("FUN_001f5450");

void FUN_L00_0029fcd0(void *m) {
    OvlQuad d1[1];
    OvlQuad d2[1];
    OvlQuad base[1];
    OvlQuad out[3];
    I3_29fcd0 ids;
    OvlQuad tmp[1];
    OvlQuad c[4];
    OvlQuad pad[5];
    OvlQuad a, b;
    int x, y, w, h;
    float len;
    ids = D_L00_00161178_29fcd0;
    FUN_0020cd48_29fcd0(m, 3, &ids, out);
    qcopy(base, out);
    FUN_001f9a28_29fcd0(d1, &out[1], out);
    FUN_001f9a28_29fcd0(d2, &out[2], out);
    len = FUN_001f9af0_29fcd0(d1);
    FUN_001f9bf8_29fcd0(tmp, d1, 0.03f);
    FUN_001f9a10_29fcd0(base, base, tmp);
    FUN_001f9bf8_29fcd0(d1, d1, len - 0.06f);
    len = FUN_001f9af0_29fcd0(d2);
    FUN_001f9bf8_29fcd0(tmp, d2, 0.04f);
    FUN_001f9a10_29fcd0(base, base, tmp);
    FUN_001f9bf8_29fcd0(d2, d2, len - 0.04f);
    qcopy(&c[0], base);
    FUN_001f9a10_29fcd0(&c[1], base, d1);
    FUN_001f9a10_29fcd0(&c[2], base, d2);
    FUN_001f9a10_29fcd0(&c[3], &c[2], d1);
    a = c[0];
    b = c[3];
    FUN_00237a78_29fcd0(&a, &b, &x, &y, &w, &h);
    FUN_00239690_29fcd0(9, 7, 1.0f);
    FUN_001fb740_29fcd0(0x200, 0x200);
    FUN_00233980_29fcd0(0x42, 0x8000000064L);
    FUN_L00_0029ead8_29fcd0(m, x, y);
    FUN_00239328_29fcd0(6, (float)x, (float)y);
    FUN_001f7978_29fcd0();
    FUN_001fb740_29fcd0(0x200, 0x200);
    FUN_00233980_29fcd0(0x42, 0x8000000064L);
    FUN_0020d330_29fcd0(m, 1);
    FUN_001f5450_29fcd0(w, h, x, y, 0, 0, x, y, 0x80808080L, D_0015EED0_29fcd0);
}
#ifndef NON_MATCHING
INCLUDE_ASM("config/us/overlays/asm/FUN_L00_0029ff58.s", FUN_L00_0029ff58);
#else
typedef struct {
    float position[4][4];
    int color[4];
    float uv[4][2];
    long extra[4];
} L00Quad29ff58;

extern float D_L00_00161184 __attribute__((section(".sdata")));
extern int D_L00_001CA480[4][4];
extern float D_L00_001CA380[16][4];
extern float D_L00_001CA410[8][2];
extern int D_L00_001CA458[];
extern char D_L00_001CA4C0_29ff58[] __asm__("D_L00_001CA4C0");
extern long FUN_001f44b8_29ff58(int) __asm__("FUN_001f44b8");
extern void FUN_001f9cf8_29ff58(void *, void *, void *) __asm__("FUN_001f9cf8");
extern void FUN_001f7d30_29ff58(void *, int, int) __asm__("FUN_001f7d30");

void FUN_L00_0029ff58(void) {
    L00Quad29ff58 q;
    float transformed[4][4];
    float *position;
    int i, index0, index1, index2, index3;
    int *indices;
    D_L00_00161184 = D_L00_00161184 + 0.01f;
    if (1.0f < D_L00_00161184) {
        D_L00_00161184 = D_L00_00161184 - 1.0f;
    }
    q.extra[0] = 0;
    q.extra[1] = FUN_001f44b8_29ff58(0x18);
    q.extra[2] = 1;
    q.extra[3] = 0x4000000044L;
    for (i = 0; i < 4; i++) {
        indices = D_L00_001CA480[i];
        index0 = indices[0];
        FUN_001f9cf8_29ff58(transformed[0], D_L00_001CA380[index0], *(char **)(D_L00_001CA4C0_29ff58 + 0x1c) + 0xc0);
        index1 = indices[1];
        FUN_001f9cf8_29ff58(transformed[1], D_L00_001CA380[index1], *(char **)(D_L00_001CA4C0_29ff58 + 0x1c) + 0xc0);
        index2 = indices[2];
        FUN_001f9cf8_29ff58(transformed[2], D_L00_001CA380[index2], *(char **)(D_L00_001CA4C0_29ff58 + 0x1c) + 0xc0);
        index3 = indices[3];
        FUN_001f9cf8_29ff58(transformed[3], D_L00_001CA380[index3], *(char **)(D_L00_001CA4C0_29ff58 + 0x1c) + 0xc0);
        position = (float *)(*(char **)(D_L00_001CA4C0_29ff58 + 0x1c) + 0x10);
#define SET_POSITION(n) \
        q.position[n][0] = position[0] + transformed[n][0]; \
        q.position[n][1] = position[1] + transformed[n][1]; \
        q.position[n][2] = position[2] + transformed[n][2]
        SET_POSITION(0);
        SET_POSITION(1);
        SET_POSITION(2);
        SET_POSITION(3);
#undef SET_POSITION
        index0 = indices[0];
        index1 = indices[1];
        index2 = indices[2];
        index3 = indices[3];
#define SET_COLOR_UV(n, index) \
        q.color[n] = D_L00_001CA458[index]; \
        q.uv[n][0] = D_L00_001CA410[index][0]; \
        q.uv[n][1] = D_L00_001CA410[index][1] + D_L00_00161184
        SET_COLOR_UV(0, index0);
        SET_COLOR_UV(1, index1);
        SET_COLOR_UV(2, index2);
        SET_COLOR_UV(3, index3);
#undef SET_COLOR_UV
        FUN_001f7d30_29ff58(&q, 0, 1);
    }
}
#endif
#include "eetypes.h"
#include "qzero.h"
typedef struct {
    u128 q[3];
} Q3_2a02b0;

typedef struct {
    char pad[0x8];
    s32 f8;
    s32 fC;
    s32 f10;
    s32 f14;
    s32 f18;
    u8 *f1C;
    u8 *f20;
    char pad24[8];
    s32 f2C;
    char pad30[0x10];
    s32 f40;
    char pad44[0x14];
    s32 f58;
    s32 f5C;
    char pad60[0x10];
    u128 f70;
    char pad80[0x50];
    struct {
        s32 a;
        s32 b;
        s32 c[3];
    } arr[4];
} A02b0_obj;

typedef struct {
    char pad[0x30];
    s32 f30;
    char pad2[0xC];
} A02b0_tab;

extern s32 D_L00_0015F5D8;
extern A02b0_obj D_L00_001CA4C0;
extern s32 D_L00_001CA4C0_w __asm__("D_L00_001CA4C0");
extern s32 D_L00_0015F3F4;
extern s32 D_L00_0015F3F8[];
extern s32 D_L00_0015F3F8_s __asm__("D_L00_0015F3F8");
extern volatile s32 D_L00_0015F3F8_v[1] __asm__("D_L00_0015F3F8");
extern s32 D_L00_001611CC;
extern s32 D_L00_0016118C;
extern s32 D_L00_00161E38;
extern s32 D_L00_001BA4C0;
extern s16 D_001516D8[];
extern u32 D_0013E504[];
extern u32 D_0015EE84;
extern u128 D_L00_00166DD0[];
extern u128 D_L00_00165F80[];
extern u128 D_L00_00166FE0[];
extern u128 D_L00_00166FF0[];
extern u128 D_L00_00166FD0[];
extern f32 D_L00_00166C80[];
extern A02b0_tab D_L00_001C8FF0[];

extern void append_gif_transfer_packet(void) __asm__("FUN_001fb368");
extern void draw_debug_profiler(void) __asm__("FUN_001f39d0");
extern void FUN_L00_002a09d8(s32);
extern s32 FUN_00122298(s32);
extern void FUN_L00_002a08c8(void);
extern void swap_render_buffer_chain(void) __asm__("FUN_00233630");
extern void FUN_L00_001f99c0(s32);
extern void FUN_001f2260(void);
extern void FUN_001f9ad8(void *, void *, void *);
extern void init_moby_instance(void *, s32) __asm__("FUN_0020c5f0");
extern void FUN_L00_00250df8(void *);
extern void FUN_0020d4f0(void *, s32, s32, s32, s32);
extern void FUN_L00_0029b680(void);
extern void FUN_001f9810(void *, s32);
extern s32 start_audio_stream_read(void *, s32, s32) __asm__("FUN_00216788");
extern void FUN_L00_002a0fc8(s32, u32, u32);
extern void setup_gif_paging(s32) __asm__("FUN_001f4280");
extern void reset_gs_registers(void) __asm__("FUN_001f3868");
extern void draw_mobys_setup(void) __asm__("FUN_0020d278");
extern void init_moby_class_dists(void) __asm__("FUN_0020d1f0");
extern void stash_moby_class_dists(void) __asm__("FUN_0020d218");
extern void draw_moby_list(void *, s32) __asm__("FUN_0020d330");
extern void FUN_L00_0029ff58(void);
extern void render_vendor_capture_pass_sequence(s32) __asm__("FUN_00239780");
extern void FUN_L00_0029fcd0_c(void *) __asm__("FUN_L00_0029fcd0");
extern void FUN_00233980(s32, s64);
extern void update_hud(void) __asm__("FUN_001ff780");
extern void do_gif_paging(void) __asm__("FUN_001f4398");
extern void restore_moby_class_dists(void) __asm__("FUN_0020d248");
extern void draw_mobys_clean_up(void) __asm__("FUN_0020d3b0");
extern void patch_moby_gifs(void) __asm__("FUN_0020cef8");

void FUN_L00_002a02b0(void) {
    A02b0_obj *e;
    A02b0_tab *g;
#define p (&D_L00_001CA4C0)

    if (D_L00_0015F5D8 != 0) {
        return;
    }
    append_gif_transfer_packet();
    switch (p->f8) {
    case 0:
        if (p->fC != 0) {
            *(u16 *)(p->f1C + 0x34) |= 1;
        }
        D_L00_0015F3F4 = 0x100FF;
        if (p->fC != 0 || *(s32 *)p == 3) {
            D_L00_0015F3F4 = 0x7F;
        }
        draw_debug_profiler();
        if (p->fC == 0) {
            return;
        }
        p->f8 = 1;
        p->fC = 0;
        FUN_L00_002a09d8(1);
        FUN_00122298(0);
        D_L00_0015F3F8_s = D_L00_0015F3F8_v[0] + 1;
        FUN_L00_002a08c8();
        swap_render_buffer_chain();
        D_L00_001611CC = 0x60000;
        FUN_L00_001f99c0(p->f10);
        *(u16 *)(p->f1C + 0x34) &= 0xFFFE;
        *(f32 *)(p->f1C + 0x2C) = 0.14190800487995148f;
        if (p->f40 != 0) {
            qcopy(&p->f70, &D_L00_00166DD0[0]);
            {
                u128 *s = &D_L00_00166DD0[32];
                D_L00_00165F80[0] = s[0];
                D_L00_00165F80[1] = s[1];
                D_L00_00165F80[2] = s[2];
                qzero(s);
            }
            qzero(D_L00_00166FE0);
            qzero(D_L00_00166FF0);
            D_L00_00166C80[0x350 / 4] = 1.0f;
            D_L00_00166C80[0x364 / 4] = 1.0f;
            D_L00_00166C80[0x378 / 4] = 1.0f;
            D_L00_00166C80[0x37C / 4] = 1.0f;
            FUN_001f2260();
        } else {
            D_L00_00165F80[0] = D_L00_00166FD0[0];
            D_L00_00165F80[1] = D_L00_00166FD0[1];
            D_L00_00165F80[2] = D_L00_00166FD0[2];
            FUN_001f9ad8(&D_L00_00166FD0[1], &D_L00_00166FD0[0], &D_L00_00166FD0[2]);
        }
        p->f20 = p->f14 + 0x100;
        init_moby_instance(p->f20, 0xD);
        *(u16 *)(p->f20 + 0x32) = 0x40;
        FUN_L00_00250df8(p->f20);
        FUN_0020d4f0(p->f20, 0x202020, 0xE, 0xE, 0);
        init_moby_instance(p->f20 + 0x500, 0xD);
        *(u16 *)(p->f20 + 0x532) = 0x40;
        FUN_L00_00250df8(p->f20 + 0x500);
        FUN_0020d4f0(p->f20 + 0x500, 0x202020, 0xE, 0xE, 0);
        FUN_L00_0029b680();
        p->f2C = p->f14 + 0x1400;
        FUN_001f9810(p->f2C, 0x400);
        p->f18 = p->f2C + 0x400;
        if (D_001516D8[0] == 0) {
            if (start_audio_stream_read(p->f18 + 0x80000, disc_table.animation_streams[48].sector,
                                        disc_table.animation_streams[48].size) != 0) {
                D_L00_0016118C = 1;
            } else {
                D_L00_0016118C = 0;
            }
        } else {
            D_L00_0016118C = 0;
        }
        break;
    case 1:
        break;
    default:
        return;
    }
    FUN_L00_002a0fc8(p->f10, D_0015EE84, D_0013E504[0] << 11);
    setup_gif_paging(0);
    FUN_001f2260();
    reset_gs_registers();
    draw_mobys_setup();
    init_moby_class_dists();
    stash_moby_class_dists();
    if (D_L00_00161E38 == 0 && p->f40 == 0) {
        if (p->arr[p->f58].b == 1) {
            g = &D_L00_001C8FF0[p->arr[p->f58].a];
            if (g->f30 != 0) {
                draw_moby_list(p->f20 + 0x200, 1);
            }
        } else {
            draw_moby_list(p->f20 + 0x300, 1);
        }
    }
    draw_moby_list(p->f1C, 1);
    if (p->f40 == 0) {
        FUN_L00_0029ff58();
    }
    render_vendor_capture_pass_sequence(p->f1C);
    if (p->f5C != 0) {
        FUN_L00_0029fcd0_c(p->f20 + 0x400);
    }
    FUN_L00_0029f990(p->f1C);
    FUN_00233980(0x42, 0x8000000044LL);
    update_hud();
    do_gif_paging();
    restore_moby_class_dists();
    draw_mobys_clean_up();
    FUN_L00_002a09d8(0x10);
    patch_moby_gifs();
}
