/* Level overlay code after ui/help; generated by `decomp overlays stubs`, stubs replaced by C as functions are matched. */
#include "types.h"
#include "rnc/gameplay/hero.h"
#include "rnc/globals.h"
#include "asm.h"
#include "qcopy.h"
#include "rnc/overlay/collision.h"
#include "rnc/math/circle_offset.h"

extern CollisionHit coll_hit __asm__("D_L00_00173E40") __attribute__((section(".data")));
/* line query from -> to; fills the collision hit record, nonzero on a hit */
extern int collision_line(void *from, void *to, int mask, void *ignore, int) __asm__("FUN_001efa68");
extern int collision_hit_material(void) __asm__("FUN_001f0b58");
extern f32 vector_length_xy(void *) __asm__("FUN_001f9b20");
extern f32 atan2_f(f32, f32) __asm__("FUN_001f9e90");
extern f32 fast_add_rotations(f32, f32) __asm__("FUN_001fa580");
extern f32 fast_difference_between_rotations(f32, f32) __asm__("FUN_001fa688");

/*
 * Ledge probe: steps forward from `pos` along the hero's yaw looking for a
 * flat top (normal within 20 degrees of up, not material 9 or 12) at least
 * `min_height` above the floor and not above pos + up, then for the wall
 * under it. Returns 1 when the hero (facing `*dir`) faces that wall within
 * 65 degrees and the ledge edge is found within 2.4 units along it.
 * Constants live in locals because retail loads each one once.
 */
int FUN_L00_0020c758(Vec4 *pos, f32 *dir)
{
    Vec4 probe, top, low, wall, edge;
    f32 drop, fwd, up, reach, min_height;
    f32 ang, wall_yaw, d, step, top_margin, max_slope, one, five, half, inc, limit;
    int found, hit, i, j, material;

    if (hero.unk308 == 2)
        return 0;

    drop = -0.7f;
    fwd = 0.3f;
    up = 1.5f;
    reach = 1.15f;
    min_height = 1.8f;
    if (hero.unk20A4 == 1) {
        min_height = 0.7f;
        drop = -0.4f;
        fwd = 0.25f;
        reach = min_height;
        up = 0.725f;
    }
    wall_yaw = 0.0f;
    found = 0;
    qcopy(&probe, pos);
    step = 0.25f;
    i = 0;
    top_margin = 0.15f;
    max_slope = 0.34906584f;       /* 20 degrees */
    probe.f[0] += fast_cos(hero.motion.rot.f[2]) * hero.unk234;
    probe.f[1] += fast_sin(hero.motion.rot.f[2]) * hero.unk234;
    do {
        probe.f[0] += fast_cos(hero.motion.rot.f[2]) * fwd * step;
        probe.f[1] += fast_sin(hero.motion.rot.f[2]) * fwd * step;
        qcopy(&top, &probe);
        top.f[2] += up + top_margin;
        qcopy(&low, &probe);
        low.f[2] += reach;
        if (collision_line(&top, &low, 4, hero.moby, 0)) {
            material = collision_hit_material();
            if (material != 9 && material != 12) {
                if (atan2_f(coll_hit.normal_z, vector_length_xy(&coll_hit.normal_x)) < max_slope)
                    found = 1;
            }
        }
        i++;
        if (found)
            break;
    } while (i < 4);
    if (!found)
        return 0;
    if (pos->f[2] + up < coll_hit.point.f[2])
        return 0;

    qcopy(&top, &coll_hit.point);
    ang = atan2_f(top.f[0] - pos->f[0], top.f[1] - pos->f[1]);
    if (top.f[2] - hero.ground_z.f < min_height)
        return 0;

    /* the wall below the top, tested at five heights */
    five = 5.0f;
    one = 1.0f;
    hit = 0;
    for (j = 0; j < 5; j++) {
        qcopy(&low, pos);
        qcopy(&wall, &top);
        circle_offset(&wall, ang, hero.unk234);
        wall.f[2] += drop * (one - j / five);
        low.f[2] = wall.f[2];
        if (collision_line(&low, &wall, 2, 0, 0)) {
            hit = 1;
            wall_yaw = atan2_f(coll_hit.normal_x, coll_hit.normal_y);
            break;
        }
    }
    if (!hit)
        return 0;

    if (fast_difference_between_rotations(*dir, fast_add_rotations(wall_yaw, 3.14159274f)) < 1.13446403f) {
        /* walk along the wall normal until the top ends */
        limit = 2.4f;
        inc = 0.07f;
        d = 0.0f;
        half = 0.5f;
        do {
            qcopy(&wall, &top);
            wall.f[2] = top.f[2];
            wall.f[0] += fast_cos(wall_yaw) * d;
            wall.f[1] += fast_sin(wall_yaw) * d;
            qcopy(&low, &wall);
            wall.f[2] += half;
            low.f[2] -= half;
            if (collision_line(&wall, &low, 4, hero.moby, 0)) {
                d += inc;
                continue;
            }
            /* edge found: its point is computed but unused, as in retail */
            qcopy(&edge, &wall);
            d = inc * half;
            d = -d;
            edge.f[2] = top.f[2];
            edge.f[0] += fast_cos(wall_yaw) * d;
            edge.f[1] += fast_sin(wall_yaw) * d;
            if (0.52359879f < fast_difference_between_rotations(fast_add_rotations(wall_yaw, 3.14159274f), *dir))
                return 0;
            return 1;
        } while (d < limit);
    }
    return 0;
}
#ifndef NON_MATCHING
INCLUDE_ASM("config/us/overlays/asm/FUN_L00_0020cd08.s", FUN_L00_0020cd08);
#else
struct LedgeSpot_20cd08 {
    Vec4 sphere;
    s32 *owner;
    s32 kind;
    u8 pad18[8];
};

extern struct LedgeSpot_20cd08 *D_L00_0015F70C;
extern s32 D_L00_0015F710;
extern s32 D_001413DC __attribute__((section(".data")));
extern f32 FUN_001f9b48(void *, void *);
extern f32 FUN_001f9b80(void *, void *);
extern f32 FUN_001f99c0(f32);
extern s32 FUN_L00_0025df68(void *, void *, void *, s32 *, f32 *, s32, f32, f32, f32);

int FUN_L00_0020cd08(void *from, void *outOwner, void *to, void *outI, void *outF,
                     void *outKind, int skip, int only)
{
    Vec4 pos;
    s32 gotI;
    f32 gotF;
    s32 i;
    s32 count = D_L00_0015F710;
    Vec4 *p = &pos;
    f32 distance_limit, height_limit, distance, height;

    *(u128 *)p = *(u128 *)from;
    i = 0;
    if (count > 0) do {
        if (skip != 0 && (int)D_L00_0015F70C[i].owner == skip)
            goto next_spot;
        if (only != 0 && (int)D_L00_0015F70C[i].owner != only)
            goto next_spot;
        if (*D_L00_0015F70C[i].owner == 0)
            goto next_spot;
        if (FUN_001f9b48(&D_L00_0015F70C[i], p) > D_L00_0015F70C[i].sphere.f[3])
            goto next_spot;
        if (!FUN_L00_0025df68(D_L00_0015F70C[i].owner, p, to, &gotI, &gotF,
                              D_L00_0015F70C[i].kind, 12.0f, 10.0f, 0.0f))
            goto next_spot;
        distance_limit = 0.9f;
        height_limit = 1.5f;
        if ((u32)D_001413DC < 2)
            distance_limit = 0.3f;
        if (hero.unk1CA != 0) {
            height_limit = 10.0f;
            distance_limit += 0.5f;
        }
        distance = FUN_001f9b80(p, to);
        height = FUN_001f99c0(p->f[2] - ((Vec4 *)to)->f[2]);
        if (!(distance < distance_limit && height < height_limit))
            goto next_spot;
        *(s32 **)outOwner = D_L00_0015F70C[i].owner;
        *(s32 *)outI = gotI;
        *(f32 *)outF = gotF;
        *(s32 *)outKind = D_L00_0015F70C[i].kind;
        return 1;
next_spot:
        i++;
    } while (i < D_L00_0015F710);
    return 0;
}
#endif /* NON_MATCHING */
#include "qcopy.h"
#include "rnc/overlay/hero.h"
#include "rnc/overlay/collision.h"
#include "rnc/overlay/quad.h"
typedef struct {
    f32 x, y, z, w;
} __attribute__((aligned(16))) V_cf58;
extern u8 D_0013D4DD_cf58 __asm__("D_0013D4DD") __attribute__((section(".data")));
f32 FUN_001f9b48_c(void *, V_cf58 *) __asm__("FUN_001f9b48");
#include "rnc/overlay/path.h"
void FUN_L00_0020cf58(void) {
    V_cf58 v0, v1, v2;

    s32 a, b, e;
    f32 c;
    s32 s;
    f32 d;
    if (D_0013D4DD_cf58 == 0)
        return;
    hero.unk56C = 0;
    if (hero.unk1C8 != 0)
        return;
    if (current_level_index == 16) {
        *(OvlQuad *)&v0 = 0;
        v0.x = 115.0f;
        v0.y = 264.0f;
        v0.z = 133.0f;
        if (12.0f < FUN_001f9b48_c(&hero.motion.pos, &v0)) {
            *(OvlQuad *)&v1 = 0;
            v1.x = 257.0f;
            v1.y = 301.0f;
            v1.z = 128.0f;
            if (12.0f < FUN_001f9b48_c(&hero.motion.pos, &v1))
                return;
        }
    } else if (current_level_index == 14) {
        *(OvlQuad *)&v0 = 0;
        v0.x = 157.0f;
        v0.y = 265.0f;
        v0.z = 51.0f;
        if (12.0f < FUN_001f9b48_c(&hero.motion.pos, &v0)) {
            *(OvlQuad *)&v1 = 0;
            v1.x = 162.0f;
            v1.y = 341.0f;
            v1.z = 48.0f;
            if (12.0f < FUN_001f9b48_c(&hero.motion.pos, &v1)) {
                *(OvlQuad *)&v2 = 0;
                v2.x = 308.0f;
                v2.y = 104.0f;
                v2.z = 69.0f;
                if (12.0f < FUN_001f9b48_c(&hero.motion.pos, &v2))
                    return;
            }
        }
    } else if (current_level_index == 6) {
        *(OvlQuad *)&v0 = 0;
        v0.x = 177.0f;
        v0.y = 304.0f;
        v0.z = 143.0f;
        if (14.0f < FUN_001f9b48_c(&hero.motion.pos, &v0))
            return;
    }
    s = hero.state.control_mode;
    if (s != 2 && s != 0 && s != 1) {
        if ((u32)(hero.state.current - 41) < 2 &&
            (hero.unk570 != 0 || hero.unk5C4 != 0)) {
        } else {
            if (s != 4)
                return;
            if (hero.unk41E == 0 && hero.unk1CA == 0)
                return;
        }
    }
    *(OvlQuad *)&v1 = *(OvlQuad *)&hero.motion.pos;
    if (!FUN_L00_0020cd08((OvlQuad *)&v1, &a, &v0, &b, &c, &e, 0, 0))
        return;
    if (hero.state.current == 41 && hero.unk5C4 != 0 && a == hero.unk560)
        return;
    d = hero.motion.pos.f[2] - v0.z;
    if (!(-0.5f < d))
        return;
    if (!(d < 0.57f) && hero.unk1CA == 0)
        return;
    qcopy(&hero.unk500, &v0);
    hero.unk560 = a;
    hero.unk564 = b;
    hero.unk568 = c;
    hero.unk584 = e;
    hero.unk56C = 1;
}
#define NOT_SDA

#define MACRO_ADDR

/* OUT = the camera-space point (0.3, 0, 1.34) in world space
   (func_L00_00233EE0). */
/* Ported from rac1-decomp (src/overlays/shared/help_0020CDF0.c: func_L00_0020D990), where it is exact; names translated to the US level program. */

extern void FUN_L00_00233660(float *, float, float, float);

void FUN_L00_0020d2f8(float *out) {
    FUN_L00_00233660(out, 0.3f, 0.0f, 1.34f);
}
typedef unsigned int u128_20d330 __attribute__((mode(TI), aligned(16)));
#include "qcopy.h"
typedef union {
    u128_20d330 q;
    float f[4];
} Vec4_20d330;
extern int D_0013CAE4_0020d330[] __asm__("D_0013CAE4");
void FUN_L00_0020d2f8_0020d330(Vec4_20d330 *) __asm__("FUN_L00_0020d2f8");
void FUN_L00_0020d330(void) {
    struct Hero *P = &hero;
    Vec4_20d330 a, b;
    Vec4_20d330 *pb;
    int i20, i24, i2C;
    float f28;
    float d, lim;
    P->unk5FC = 0;
    if (P->unk1E4 != 0)
        return;
    FUN_L00_0020d2f8_0020d330(&a);
    if ((P->state.control_mode == 4 && P->unk41E == 0) || P->state.control_mode == 2) {
        pb = &b;
        if (FUN_L00_0020cd08(&a, &i20, pb, &i24, &f28, &i2C, 0, 0)) {
            float bz, az;
            int fl;
            az = a.f[2];
            fl = D_0013CAE4_0020d330[0];
            bz = b.f[2];
            lim = -0.7f;
            d = az - bz;
            if (fl & 0x80)
                lim = -1.2f;
            if (lim < d && d < 0.4f) {
                qcopy(&hero.unk5E0, pb);
                hero.unk5F0 = (s32 *)i20;
                hero.unk5F4 = i24;
                hero.unk5F8 = f28;
                hero.unk60C = i2C;
                hero.unk5FC = 1;
            }
        }
    }
}
/* Returns the moby of item slot i when the slot is ready (state 2), else 0. */
s32 FUN_L00_0020d460(s32 i) {
    /* hero shifted by i slots, so items[0] is slot i */
    struct Hero *p = (struct Hero *)(((char *)&hero) + i * sizeof(struct HeroItemSlot));
    if (p->items[0].state == 2) {
        return (s32)p->items[0].moby;
    }
    return 0;
}
/* Returns the item id of slot i when the slot is ready (state 2), else -1. */
int FUN_L00_0020d498(int i) {
    /* hero shifted by i slots, so items[0] is slot i */
    struct Hero *p = (struct Hero *)(((char *)&hero) + i * sizeof(struct HeroItemSlot));
    switch (p->items[0].state) {
    case 2:
        return p->items[0].item_id;
    }
    return -1;
}
#define NOT_SDA

#define MACRO_ADDR

/* Whether func_L00_0020DB30(ARG) is one of 10, 17, 20 or 25. */
/* Ported from rac1-decomp (src/overlays/shared/help_0020CDF0.c: func_L00_0020DB68), where it is exact; names translated to the US level program. */

extern int FUN_L00_0020d498_u(int) __asm__("FUN_L00_0020d498");

/* True when FUN_L00_0020d498(arg) is 0x11, 10, 0x14 or 0x19. */
int FUN_L00_0020d4d0(int arg) {
    int v = FUN_L00_0020d498_u(arg);

    if (v == 0x11 || v == 10 || v == 0x14 || v == 0x19) {
        return 1;
    }
    return 0;
}
/* True when FUN_L00_0020d498(a) is 5, 6 or 7. */
s32 FUN_L00_0020d518(int a) {
    return (u32)(FUN_L00_0020d498_u(a) - 5) < 3;
}
int FUN_L00_0020d498_0020d540() __asm__("FUN_L00_0020d498");
/* True when FUN_L00_0020d498 returns 0x1C or 0x1D. */
int FUN_L00_0020d540(void) {
    return (unsigned)(FUN_L00_0020d498_0020d540() - 0x1c) < 2;
}
/* True when hero.state.control_mode is 0x11/0x12 or state.current is 0x6A, 0x75, 0x76 or 0x82. */
s32 FUN_L00_0020d568(void) {
    struct Hero *p = &hero;
    u32 a = p->state.control_mode;
    u32 b;
    if (a - 0x11 < 2) {
        goto one;
    }
    b = p->state.current;
    if (b == 0x6A) {
        goto one;
    }
    if (b == 0x82) {
        goto one;
    }
    if (b == 0x76) {
        goto one;
    }
    if (b != 0x75) {
        goto zero;
    }
one:
    return 1;
zero:
    return 0;
}
/* Returns a, or the byte at p+0xA5 when a is 0xFF. */
s32 FUN_L00_0020d5b8(u8 *p, s32 a) {
    if (a == 0xFF)
        a = p[0xA5];
    return a;
}
/* FUN_L00_0020d5d0 -- per-mode angle helper.
 *
 * Writes 0.0f to *out, then looks up the mode (0x1C..0x6F) in a jump table.
 * Modes 0x1C/0x1D/0x1F optionally overwrite *out with the sloped angle, modes
 * 0x32/0x33/0x5F/0x60/0x6B/0x6D/0x6E only report "handled", and everything
 * else (including a mode outside the table) falls through to 0.
 *
 * The 25.0f threshold is held in a local so it lands in $f1 and the load in $f0.
 * The case groups are written 33, then 22..., then 0/1/3: gcc emits the blocks
 * in source order, and retail lays them out in exactly that order.
 */


int FUN_L00_0020d5d0(int mode, float *out) __asm__("FUN_L00_0020d5d0");

int FUN_L00_0020d5d0(int mode, float *out) {
    int i;
    *out = 0.0f;
    i = mode - 0x1C;
    switch (i) {
    case 33:
        *out = -0.9599311f;
        return 1;
    case 22:
    case 23:
    case 63:
    case 64:
    case 79:
    case 81:
    case 82:
        return 1;
    case 0:
    case 1:
    case 3: {
        float c;
        c = 25.0f;
        if (c < hero.unkAA8) {
            *out = -1.3089969f;
        }
        return 1;
    }
    }
    return 0;
}
#define NOT_SDA

#define MACRO_ADDR

/* The value BACK entries ago (at most 31, and at most the entry count
   hero.unk21AC) in the 32-float ring hero.unk2128 whose newest entry is
   hero.unk21A8. Reading through a local hero pointer gives retail's
   base-first index add. */
/* Ported from rac1-decomp (src/overlays/shared/help_0020CDF0.c: func_L00_0020DCF0), where it is exact; names translated to the US level program. */

float FUN_L00_0020d658(int back) {
    struct Hero *b = &hero;
    int n = back < 32 ? back : 31;

    if (b->unk21AC < n) {
        n = b->unk21AC;
    }
    return b->unk2128[(b->unk21A8 - n + 31) % 32];
}
typedef struct {
    char p0[0x2084];
    int w2084;
    char p1[0x2D8 - 0x2088 + 0x2000];
} G_20d6b0;
typedef struct {
    char p0[0x140];
    float v140[4];
    char p1[0x154 - 0x150];
    float f154;
    float f158;
} C_20d6b0;
extern C_20d6b0 D_166C80_20d6b0 __asm__("D_L00_00166C80");
extern float dist_20d6b0(void *, void *) __asm__("FUN_001f9b48");
extern float atan2_20d6b0(float, float) __asm__("FUN_001f9e90");
extern float adiff_20d6b0(float, float) __asm__("FUN_001fa688");
extern float hdist_20d6b0(void *, void *) __asm__("FUN_001f9b80");
extern int f5e3b8_20d6b0(void *) __asm__("FUN_L00_0025e3b8");

float FUN_L00_0020d6b0(char *o, float yaw, float range, float ylim, float plim, int *out) {
    float v[4] __attribute__((aligned(16)));
    struct Hero *g;
    float d, a, s, p, m, r;

    *out = 0;
    qcopy(v, &hero.motion.pos);
    g = &hero;
    if (g->state.current == 0x14) {
        v[2] = g->ground_z.f;
    }
    d = dist_20d6b0(v, o + 0x10);
    if (range < d)
        *out = 1;
    a = adiff_20d6b0(atan2_20d6b0(*(float *)(o + 0x10) - v[0], *(float *)(o + 0x14) - v[1]), yaw);
    s = a;
    m = a;
    p = adiff_20d6b0(atan2_20d6b0(hdist_20d6b0(v, o + 0x10), *(float *)(o + 0x18) - v[2]), 0.0f);
    if (g->state.current == 1 || g->state.current == 0x1E) {
        C_20d6b0 *c = &D_166C80_20d6b0;
        float b = adiff_20d6b0(
            atan2_20d6b0(*(float *)(o + 0x10) - c->v140[0], *(float *)(o + 0x14) - c->v140[1]),
            c->f158);
        p = adiff_20d6b0(
            atan2_20d6b0(hdist_20d6b0(c->v140, o + 0x10), *(float *)(o + 0x18) - c->v140[2]),
            -c->f154);
        m = p;
        s = b + p;
        if (p < b)
            m = b;
    }
    if (0.0f < ylim && ylim < m)
        *out = 1;
    if (0.0f < plim && plim < p)
        *out = 1;
    r = d + s * d;
    if (f5e3b8_20d6b0(o))
        r += 7.0f;
    return r;
}
extern char *D_L00_001ABA00[] __attribute__((section(".data")));
float *FUN_002141f8_20d8f8(char *) __asm__("FUN_002141f8");
float FUN_L00_0020d6b0(char *, float, float, float, float, int *);
char *FUN_L00_0020d8f8(float a, float b, float c, float d) {
    char *best = 0;
    float bd = 1.0e8f;
    int i = 0;
    char *o;
    while ((o = D_L00_001ABA00[i]) != 0) {
        float *f = FUN_002141f8_20d8f8(o);
        if (f != 0 && *f != 0.0f && (*(unsigned short *)(o + 0x34) & 0x1000)) {
            int out;
            float dist = FUN_L00_0020d6b0(o, b, a, c, d, &out);
            if (out == 0 && dist < bd) {
                bd = dist;
                best = o;
            }
        }
        i++;
    }
    return best;
}
/* Maps 1, 2, 3 to 0x79, 0x77, 0x75; others to 0. */
s32 FUN_L00_0020da10(s32 a0) {
    switch (a0) {
    case 1:
        return 0x79;
    case 2:
        return 0x77;
    case 3:
        return 0x75;
    }
    return 0;
}
extern float D_0015ED60_20da68 __asm__("D_0015ED60");
extern unsigned char D_0013D4C6_20da68 __asm__("D_0013D4C6") __attribute__((section(".data")));
unsigned char *FUN_002141f8_20da68(int) __asm__("FUN_002141f8");
int FUN_L00_0020da10_20da68(int) __asm__("FUN_L00_0020da10");
float FUN_001fa6c0_20da68(int) __asm__("FUN_001fa6c0");
int FUN_L00_0020d498_20da68(int) __asm__("FUN_L00_0020d498");
char *FUN_L00_0024f028_20da68(char *, int) __asm__("FUN_L00_0024f028");
float FUN_00213ed8_20da68(void *, float, float) __asm__("FUN_00213ed8");
void FUN_L00_0024f0e8_20da68(char *, char **) __asm__("FUN_L00_0024f0e8");
int FUN_001f96f8_20da68(int) __asm__("FUN_001f96f8");
void FUN_L00_0024f3e0_20da68(char *, char *, int, int, int, int) __asm__("FUN_L00_0024f3e0");
void FUN_L00_0024f190_20da68(char *, char *) __asm__("FUN_L00_0024f190");
void FUN_L00_0020da68(void) {
    int on, anim, r, c;
    float spd, t;
    unsigned char *m;
    char *q;
    char *q2;
    anim = 0;
    spd = 1.0f;
    on = 0;
    if (hero.unk2274) {
        on = 1;
        m = FUN_002141f8_20da68(hero.unk2274);
        anim = 0x79;
        if (m && m[0x3C]) {
            anim = FUN_L00_0020da10_20da68(m[0x3C]);
            if (hero.state.control_mode == 1)
                spd = 0.7f;
        }
    }
    if (hero.unk1DC) {
        on = 1;
        anim = FUN_L00_0020da10_20da68(hero.unk22CE);
    }
    if (hero.health.hp == 1) {
        on = 1;
        c = (unsigned char)((char *)hero.moby)[0x53];
        if (c == 0x54 || c == 0x82 || c == 0x5A) {
            if (!hero.unkA9C)
                on = 0;
        }
        spd = 0.8f;
        anim = 0x7B;
    }
    if (hero.state.control_mode == 0x11 && !D_0013D4C6_20da68) {
        on = 1;
        anim = 0x78;
        t = FUN_001fa6c0_20da68(hero.unk22A0) / FUN_001fa6c0_20da68(10000);
        t = 1.0f - t;
        spd = t + 0.25f;
        if (1.0f < spd)
            spd = 1.0f;
    }
    r = FUN_L00_0020d498_20da68(0);
    if ((unsigned)(r - 0xF) < 2 || r == 0x13) {
        if (hero.unk20A8) {
            spd = 0.8f;
            on = 1;
            anim = 0x76;
        }
    }
    if (on) {
        if (!hero.unkD10) {
            hero.unkD10 = (u8 *)FUN_L00_0024f028_20da68((char *)hero.moby, 0x18);
            *(int *)(hero.unkD10 + 8) = 0;
        }
    } else {
        if (!hero.unkD10)
            return;
        if (FUN_00213ed8_20da68(hero.unkD10 + 8, 0.0f, D_0015ED60_20da68 * 0.05f) == 0.0f) {
            FUN_L00_0024f0e8_20da68((char *)hero.moby, (char **)&hero.unkD10);
        }
    }
    q = hero.unkD10;
    if (q && on) {
        FUN_00213ed8_20da68(q + 8, spd, D_0015ED60_20da68 * 0.05f);
        q2 = hero.unkD10;
        if ((unsigned char)q2[0x23] != anim) {
            FUN_L00_0024f3e0_20da68((char *)hero.moby, hero.unkD10, anim, 0, FUN_001f96f8_20da68(8), 1);
        } else {
            FUN_L00_0024f190_20da68((char *)hero.moby, q2);
        }
    }
}
INCLUDE_ASM("config/us/overlays/asm/FUN_L00_0020dd20.s", FUN_L00_0020dd20);
typedef struct {
    u8 p[0x28];
    s32 i28;
    u8 p2[0x4C - 0x2C];
} R_0020e360;
extern R_0020e360 D_L00_00179AC0_0020e360[] __asm__("D_L00_00179AC0")
    __attribute__((section(".data")));
extern s32 D_L00_0015F6A0_0020e360[2] __asm__("D_L00_0015F6A0") __attribute__((sda));
s32 FUN_L00_0020d498_0020e360(s32) __asm__("FUN_L00_0020d498");
u8 *FUN_L00_0024f028_0020e360(u8 *, s32) __asm__("FUN_L00_0024f028");
s32 FUN_001f96f8_0020e360(s32) __asm__("FUN_001f96f8");
void FUN_L00_0024f3e0_0020e360(u8 *, u8 *, s32, s32, s32, s32) __asm__("FUN_L00_0024f3e0");
void FUN_L00_0020e360(s32 a, s32 b) {
    s32 t, i;
    u8 *o;
    if (hero.unk20A4)
        return;
    if (!hero.unk20A8)
        return;
    if (!hero.unk20AA)
        return;
    if (a)
        return;
    if (!b)
        return;
    t = FUN_L00_0020d498_0020e360(0);
    t = D_L00_00179AC0_0020e360[t].i28;
    if (t == -1)
        return;
    for (i = 0; i < 2; i++) {
        if (hero.unkD08[i] != 0)
            continue;
        if (i == 1 && hero.unk20AB != 2)
            break;
        {
            o = FUN_L00_0024f028_0020e360((u8 *)hero.moby, D_L00_0015F6A0_0020e360[i]);
            hero.unkD08[i] = o;
            if (o) {
                hero.unkD14 = 0;
                *(s32 *)(o + 8) = 0;
                FUN_L00_0024f3e0_0020e360((u8 *)hero.moby, o, t, 0,
                                          FUN_001f96f8_0020e360(0xF), 1);
                *(f32 *)(o + 0x28) = 1.0f;
            }
        }
    }
}

typedef struct {
    u8 p0[0x18];
    s32 f18;
    u8 p1[0x24 - 0x1C];
    s32 f24;
    s32 f28;
    s32 f2C;
    s32 f30;
    u8 p2[0x4C - 0x34];
} ID_20e4c8;

extern ID_20e4c8 D_L00_00179AC0_c[] __asm__("D_L00_00179AC0");
extern s32 D_L00_0015F6A0[2] __asm__("D_L00_0015F6A0") __attribute__((sda));
extern s32 FUN_L00_0020d498_c(s32) __asm__("FUN_L00_0020d498");
extern s32 FUN_001f96f8_c(s32) __asm__("FUN_001f96f8");
extern u8 *FUN_L00_0024f028(u8 *, s32);
extern void FUN_L00_0024f0e8(u8 *, u8 **);
extern void FUN_L00_0024f3e0(u8 *, u8 *, s32, s32, s32, s32);
extern void FUN_L00_002323b8_c(s32, s32, f32) __asm__("FUN_L00_002323b8");

void FUN_L00_0020e4c8(void) {
    s32 t, v19, v20, v21, i;
    u8 *o;
    struct Hero *P;
    t = FUN_L00_0020d498_c(0);
    if (t == -1 || t == 0)
        return;
    P = &hero;
    P->unk2298 = t;
    v19 = D_L00_00179AC0_c[t].f24;
    v21 = D_L00_00179AC0_c[t].f28;
    if ((s32)P->state.control_mode == 12)
        v21 = D_L00_00179AC0_c[t].f2C;
    P->unk20A8 = 1;
    {
        s32 k = D_L00_00179AC0_c[t].f30;
        P->unk20AA = k;
    }
    v20 = FUN_001f96f8_c(10);
    if (D_L00_00179AC0_c[t].f18 == 0)
        v20 = FUN_001f96f8_c(11);
    if (P->state.control_mode == 0 && P->unk22C8 == 0) {
        P->unk2294 = v19;
        FUN_L00_002323b8_c(v19, 0, (f32)v20);
        return;
    }
    if (v21 == -1)
        return;
    for (i = 0; i < 2 && (i != 1 || hero.unk20AB == 2); i++) {
        if (hero.unkD08[i] != 0) {
            FUN_L00_0024f0e8((u8 *)hero.moby, &hero.unkD08[i]);
        }
        o = FUN_L00_0024f028((u8 *)hero.moby, D_L00_0015F6A0[i]);
        hero.unkD08[i] = o;
        if (o != 0) {
            hero.unk2294 = v21;
            hero.unkD14 = 0;
            *(f32 *)(o + 8) = 1.0f;
            FUN_L00_0024f3e0((u8 *)hero.moby, o, hero.unk2294, 0, v20, 1);
        }
    }
}
#define NOT_SDA

#define MACRO_ADDR

/* Ported from rac1-decomp (src/overlays/shared/help_0020CDF0.c: func_L00_0020ED30), where it is exact; names translated to the US level program. */

extern int FUN_L00_00205000(int);
extern void FUN_L00_002323b8(int, int, float);

void FUN_L00_0020e698(void) {
    struct Hero *g = &hero;
    if (g->unk20A8 != 0) {
        if (g->unkD08[0] != 0) {
            g->unkD14 = 1;
        } else if (g->state.current == 0) {
            unsigned char *m = (unsigned char *)g->moby;
            if (m[0x53] == g->unk2294) {
                int r = FUN_L00_00205000(0);
                FUN_L00_002323b8(r, 0, -2.0f);
            }
        }
        hero.unk20A8 = 0;
        hero.unk20AA = 0;
    }
}
INCLUDE_ASM("config/us/overlays/asm/FUN_L00_0020e728.s", FUN_L00_0020e728);
INCLUDE_ASM("config/us/overlays/asm/FUN_L00_0020ea80.s", FUN_L00_0020ea80);
#define NOT_SDA

#define MACRO_ADDR

/* Ported from rac1-decomp (src/overlays/shared/help_0020CDF0.c: func_L00_0020F750), where it is exact; names translated to the US level program. */

float absolute_float(float input) __asm__("func_001F99C0");

float FUN_L00_0020f0b8(float *a, float *b) {
    float s = 0.0f;
    int i, j;
    for (i = 0; i < 3; i++) {
        float *q = (float *)((i << 4) + (int)b);
        float *p = (float *)((i << 4) + (int)a);
        for (j = 0; j < 3; j++) {
            s += absolute_float(*p++ - *q++);
        }
    }
    return s;
}
INCLUDE_ASM("config/us/overlays/asm/FUN_L00_0020f160.s", FUN_L00_0020f160);
INCLUDE_ASM("config/us/overlays/asm/FUN_L00_0020f580.s", FUN_L00_0020f580);
typedef struct {
    char pad[0x20];
    unsigned char t;
    char pad2[0x74 - 0x21];
    void (*fn)(void);
} O;
void mark_moby_for_removal(void *) __asm__("FUN_0020c828");
void FUN_L00_0020fca8(int i, int v) {
    struct Hero *e; /* hero shifted by i slots, so items[0] is slot i */
    {
        struct Hero *f = (struct Hero *)(((char *)&hero) + i * sizeof(struct HeroItemSlot));
        O *o;
        f->items[0].unk14 = v;
        if (f->items[0].state != 3) {
            o = (O *)f->items[0].moby;
            f->items[0].state = 3;
            if (o && o->t != 0xfe && o->t != 0xfd && o->fn)
                o->fn();
        }
    }
    e = (struct Hero *)(((char *)&hero) + i * sizeof(struct HeroItemSlot));
    e->items[0].state = 0;
    e->items[0].item_id = 0;
    if (e->items[0].moby) {
        mark_moby_for_removal(e->items[0].moby);
        e->items[0].moby = 0;
    }
    if (e->items[0].moby2 && i != 3) {
        mark_moby_for_removal(e->items[0].moby2);
        e->items[0].moby2 = 0;
    }
}
#define NOT_SDA

#define MACRO_ADDR

/* Ported from rac1-decomp (src/overlays/shared/help_0020CDF0.c: func_L00_00210418), where it is exact; names translated to the US level program. */

extern int scale_game_frames(int) __asm__("FUN_001f96f8");

/* For the listed ids sets hero.unk22CE to 3 and hero.unk1DC to scale_game_frames(0x46). */
void FUN_L00_0020fd80(int id) {
    struct Hero *base;

    switch (id) {
    case 9:
    case 11:
    case 13:
    case 16:
    case 23:
        base = &hero;
        base->unk22CE = 3;
        base->unk1DC = scale_game_frames(0x46);
        break;
    }
}
#define NOT_SDA

#define MACRO_ADDR

/* Ported from rac1-decomp (src/overlays/shared/help_0020CDF0.c: func_L00_00210478), where it is exact; names translated to the US level program. */

extern int scale_game_frames(int) __asm__("FUN_001f96f8");

/* Sets the short at hero.unk1DA to scale_game_frames(0x46) for the listed ids. */
void FUN_L00_0020fde0(int id) {
    switch (id) {
    case 9:
    case 11:
    case 13:
    case 14:
    case 15:
    case 16:
    case 18:
    case 19:
    case 22:
    case 23:
    case 26:
        hero.unk1DA = scale_game_frames(0x46);
        break;
    }
}
s32 FUN_L00_00233f38_0020fe30(void) __asm__("FUN_L00_00233f38");
extern s32 D_L00_0015F5C4_0020fe30 __asm__("D_L00_0015F5C4");
/* True when 00233f38, D_L00_0015F5C4 and hero.unk20A4 are 0, control_mode <3 or 4, and base_condition is 0. */
s32 FUN_L00_0020fe30(void) {
    struct Hero *b;
    u32 s;
    if (FUN_L00_00233f38_0020fe30())
        return 0;
    if (D_L00_0015F5C4_0020fe30)
        return 0;
    b = &hero;
    if (b->unk20A4)
        return 0;
    s = b->state.control_mode;
    if (s < 3 || s == 4)
        return b->base_condition == 0;
    return 0;
}
/* Applies the wrench/item selection for slot i: resolves pending, queued and requested items and refreshes the slot when it changes. */
/* Ported from rac1-decomp (src/overlays/shared/help_0020CDF0.c: func_L00_00210558), where it is exact; names translated to the US level program. */


typedef struct {
    char pad[0x20];
    int f20;
    char pad2[0x28];
} ItemDef;

extern char D_0013C940[];
extern char D_00141660[];
extern unsigned char D_0013D4C0[];
extern int D_0015ED8C;
extern int D_0015ED90;
extern int D_0015ED94;
extern ItemDef D_L00_00179AC0[];
extern int FUN_001f9770(void *);
extern int FUN_L00_0020d568_c() __asm__("FUN_L00_0020d568");
extern int FUN_L00_00216de8(int, int);
extern int FUN_L00_00257b90(int, int);
extern void FUN_L00_0020a500(void);
extern void FUN_L00_0020e698_c(void) __asm__("FUN_L00_0020e698");
extern void FUN_L00_002cdcc0(void);
s32 FUN_L00_0020fe30_c(void) __asm__("FUN_L00_0020fe30");
void FUN_L00_0020fd80_c(int id) __asm__("FUN_L00_0020fd80");
void FUN_L00_0020fde0_c(int id) __asm__("FUN_L00_0020fde0");
void blend_moby_animation(void *arg0, int arg1, int arg2, int arg3) __asm__("FUN_00212f90");

void FUN_L00_0020fea0(int i) {
    int changed;
    int flag6;
    int flag4;
    unsigned char st;

    if (i == 0) {
        int v;
        struct Hero *g = &hero;
        v = g->items[0].item_id;
        if (v != 8 && v != 0x17 && v != 9 && g->items[0].unk1C == 2) {
            g->items[0].unk1C = 0;
        }
    }
    if (i == 0) {
        struct Hero *g = &hero;
        if (g->unk20A7 != 0 && g->items[0].item_id != 8) {
            g->unk20A6 = 1;
        }
    }
    if (i == 0) {
        struct Hero *g = &hero;
        if (g->unk20A7 != 0 && g->items[0].item_id == 8) {
            if (g->pending_item[0] == 0x1F) {
                g->pending_item[0] = 0;
            }
            if (g->pending_item[0] != 0x18 && g->pending_item[0] != 0x24) {
                return;
            }
        }
    }
    {
        struct Hero *g = &hero;
        if (g->unk20AC != 0 && i == 0) {
            if (g->unk20A6 == 0 || g->items[0].item_id == 8) {
                g->unk20A6 = 0;
                return;
            }
        }
    }
    changed = 0;
    {
        char *pad = D_0013C940;
        if ((*(int *)(pad + 0x1A4) & 0x80) || hero.unk20A6 != 0) {
            if (i == 0) {
                int v;
                struct Hero *g = &hero;
                v = g->items[0].item_id;
                if (v != 8) {
                    if (g->unk20A6 != 0 && v != 0 && v != 0x1F) {
                        g->saved_item[0] = v;
                    }
                    hero.selected_item[i] = 8;
                    changed = 1;
                }
            }
        }
    }
    if (i == 0) {
        char *pad = D_0013C940;
        if (*(int *)(pad + 0x1A4) & 0x20) {
            struct Hero *g = &hero;
            if (g->unk20A7 == 0) {
                if (g->items[0].item_id != *(int *)(D_00141660) && *(int *)(D_00141660) != 0) {
                    g->selected_item[0] = *(int *)(D_00141660);
                    changed = 1;
                }
            }
        }
    }
    if (i == 1) {
        struct Hero *g;
        if (FUN_L00_0020d568_c() || hero.state.current == 0x12) {
            int v;
            g = &hero;
            v = g->items[1].item_id;
            if (v != 0) {
                g->saved_item[1] = v;
                g->pending_item[1] = 0x26;
            }
        }
        g = &hero;
        if (g->state.control_mode == 0xF && D_0013D4C0[0x1D] != 0) {
            if (*(int *)(D_00141660 + 4) != 0x1D || *(int *)((char *)g + i * 0x50 + 0x10B8) == 0) {
                int v;
                g->pending_item[1] = 0x1D;
                v = *(int *)((char *)g + i * 0x50 + 0x10B8);
                if (v != 0) {
                    g->saved_item[i] = v;
                } else {
                    g->saved_item[i] = 0x26;
                }
            }
        }
        g = &hero;
        if (g->unk12E7 != 0 && D_0013D4C0[0x1C] != 0) {
            if (*(int *)(D_00141660 + 4) != 0x1C || *(int *)((char *)g + i * 0x50 + 0x10B8) == 0) {
                int v;
                g->pending_item[1] = 0x1C;
                v = *(int *)((char *)g + i * 0x50 + 0x10B8);
                if (v != 0) {
                    g->saved_item[i] = v;
                } else {
                    g->saved_item[i] = 0x26;
                }
            }
        }
    }
    flag6 = 0;
    if (i == 2) {
        struct Hero *g = &hero;
        struct Hero *h;
        struct Hero *h2;
        if (g->state.control_mode == 0x11 || g->state.current == 0x76 || g->state.current == 0x6A || g->state.current == 0x82 ||
            g->unk22CB != 0) {
            if (((int *)(D_00141660))[i] != 6 ||
                (h2 = &hero, *(int *)((char *)h2 + i * 0x50 + 0x10B8) == 0)) {
                h = &hero;
                if (*(int *)((char *)h + i * 0x50 + 0x10B8) != 6 && h->selected_item[i] != 6 &&
                    D_0013D4C0[6] != 0) {
                    int v;
                    h->pending_item[i] = 6;
                    flag6 = 1;
                    v = *(int *)((char *)h + i * 0x50 + 0x10B8);
                    if (v != 0) {
                        h->saved_item[i] = v;
                    } else {
                        h->saved_item[i] = 0x26;
                    }
                }
            }
        } else if (g->items[2].item_id == 6 && g->saved_item[2] != 0) {
            g->restore_item[2] = 1;
        }
    }
    flag4 = 0;
    if (i == 3) {
        struct Hero *g;
        if (FUN_L00_0020d568_c() || hero.state.current == 0x12) {
            if (*(int *)(D_00141660 + 0xC) != 4) {
                int v;
                g = &hero;
                v = g->items[3].item_id;
                if (v != 4 && D_0013D4C0[4] != 0) {
                    g->saved_item[3] = v;
                    flag4 = 1;
                    g->pending_item[3] = 4;
                }
            }
        } else if (hero.items[3].item_id == 4 && hero.saved_item[3] != 0) {
            hero.restore_item[3] = 1;
        }
        if (hero.state.current == 8 && ((int *)(D_00141660))[i] == 4) {
            hero.pending_item[i] = 2;
        }
    }
    {
        struct Hero *g = &hero;
        int *qb = g->restore_item;
        int *q = qb + i;
        if (*q != 0) {
            int *r;
            int *rb;
            int w;
            *q = 0;
            rb = g->saved_item;
            r = rb + i;
            w = *r;
            if (w != 0 && w != *(int *)((char *)g + i * 0x50 + 0x10B8)) {
                if (w == 0x26) {
                    w = 0;
                }
                *r = 0;
                ((int *)(D_00141660))[i] = w;
                g->selected_item[i] = w;
                if (i == 0) {
                    D_L00_00179AC0[g->selected_item[0]].f20 = 0x20;
                }
                changed = 1;
            }
        }
    }
    {
        struct Hero *g = &hero;
        int *s;
        int *sb;
        if (g->unk1FF5 != 0) {
            FUN_L00_002cdcc0();
            g->pending_item[i] = 0;
        }
        sb = g->pending_item;
        s = sb + i;
        if (*s == 0x1F) {
            if (FUN_L00_0020fe30_c()) {
                int v;
                if (g->unk22DE == 0) {
                    FUN_L00_00216de8(0x18, 0);
                    g->unk22DE = 0x12;
                    g->unk22DC = 1;
                }
                changed = 1;
                g->selected_item[i] = *s;
                v = ((int *)(D_00141660))[i];
                ((int *)(D_00141660))[i] = *s;
                D_0015ED8C = v;
            }
            hero.pending_item[i] = 0;
        }
    }
    {
        int v;
        struct Hero *g = &hero;
        int *ab = g->pending_item;
        int *a = ab + i;
        v = *a;
        if (v != 0) {
            int *bb = g->selected_item;
            int *b = bb + i;
            if (v != *b) {
                if (v == 0x26) {
                    *b = 0;
                    ((int *)(D_00141660))[i] = 0;
                } else {
                    struct Hero *h;
                    int u;
                    if (i == 0 && g->pending_item[0] != 0x24 && g->items[0].item_id != 8) {
                        D_0015ED8C = *(int *)(D_00141660);
                    }
                    h = &hero;
                    u = h->pending_item[i];
                    h->selected_item[i] = u;
                    if (u != 0x24 && (flag6 == 0 || u != 6) && (flag4 == 0 || u != 4)) {
                        ((int *)(D_00141660))[i] = u;
                    }
                    if (i == 0) {
                        struct Hero *k = &hero;
                        D_L00_00179AC0[k->selected_item[0]].f20 = 0x20;
                    }
                }
                changed = 1;
            } else {
                *a = 0;
            }
        }
    }
    {
        struct Hero *s = (struct Hero *)(((char *)&hero) + i * sizeof(struct HeroItemSlot));
        st = s->items[0].unk1C;
        if (st == 2) {
            changed = 0;
        }
        if (st == 1 && s->items[0].timer == 0) {
            s->items[0].timer = s->items[0].timer_reload;
        }
    }
    if (FUN_001f9770(&hero.items[i].timer) == 0) {
        changed = 0;
    }
    if (changed) {
        struct Hero *g = &hero;
        *(int *)((char *)g + i * 0x50 + 0x10B0) = 3;
        FUN_L00_0020a500();
        g->unk1010 =
            FUN_L00_00257b90(scale_game_frames(0x32), scale_game_frames(0x5A));
        FUN_L00_0020fde0_c(*(hero.selected_item + i));
        FUN_L00_0020fd80_c(*(hero.selected_item + i));
        if (g->unk20A8 != 0) {
            FUN_L00_0020e698_c();
        }
        if (i == 0) {
            if (*hero.selected_item == 8) {
                D_0015ED90 = 1;
            } else {
                D_0015ED90 = 0;
            }
        }
        if (i == 3) {
            if (hero.items[3].item_id == 3) {
                D_0015ED94 = 1;
            } else {
                D_0015ED94 = 0;
            }
        }
        {
            struct Hero *k = &hero;
            struct Hero *s = (struct Hero *)((char *)k + i * sizeof(struct HeroItemSlot));
            s->items[0].unk1A = 0;
            k->pending_item[i] = 0;
            k->unk20A6 = 0;
            if (k->unkD00 != 0) {
                *(int *)(k->unkD00 + 0x34) = 1;
            }
            if (k->unkD04 != 0) {
                *(int *)(k->unkD04 + 0x34) = 1;
            }
            if (s->items[0].moby != 0) {
                blend_moby_animation(s->items[0].moby, 2, 0, 2);
            }
            if (s->items[0].moby2 != 0 && i != 3) {
                blend_moby_animation(s->items[0].moby2, 2, 0, 2);
            }
        }
        {
            struct Hero *e = (struct Hero *)(((char *)&hero) + i * sizeof(struct HeroItemSlot));
            e->items[0].state = 3;
        }
    }
}
#ifndef NON_MATCHING
INCLUDE_ASM("config/us/overlays/asm/FUN_L00_00210748.s", FUN_L00_00210748);
#else
#include "rnc/gameplay/entities/moby.h"
extern void FUN_L00_00205168(void *);
extern void FUN_L00_00257880(void *, int, int, int);
extern s32 D_L00_0015F3F8;

void FUN_L00_00210748(void) {
    int i = 0;
    do {
        struct Hero *slot_hero = (struct Hero *)(((char *)&hero) + i * 0x50);
        struct Moby *moby = slot_hero->items[0].moby;
        if (moby == 0) {
            FUN_L00_0020fea0(i);
        } else {
            if (slot_hero->items[0].state == 2) {
                slot_hero->items[0].unk20++;
                FUN_L00_0020fea0(i);
                if (i == 0) {
                    char *p = (char *)&hero;
                    struct HeroEase *e = &hero.unk18F0[0];
                    char *end = p + 0x210;
                    do {
                        if (((struct HeroEase *)(p + 0x18F0))->unkA0 != -1) {
                            ((struct HeroEase *)(p + 0x18F0))->kind = 5;
                            FUN_L00_00205168(e);
                        }
                        p += 0xB0;
                        e++;
                    } while (p < end);
                }
                if ((moby->unk70 & 2) && moby->prev_seq == 0)
                    FUN_L00_00257880(moby, 1, 0, 2);
            } else if (slot_hero->items[0].state == 3) {
                slot_hero->items[0].unk1B++;
                if ((moby->unk70 & 2) || i == 1 || i == 0)
                    FUN_L00_0020fca8(i, D_L00_0015F3F8 + 2);
            }
            if (moby->state != 0xfe && moby->state != 0xfd && i != 6 && moby->update)
                moby->update(moby);
        }
        i++;
    } while (i < 7);
}
#endif /* NON_MATCHING */
s32 FUN_L00_0020d568_u() __asm__("FUN_L00_0020d568");
void FUN_L00_0020ea80();
void FUN_L00_0020f580();
void FUN_L00_00234808();
void FUN_L00_002080b0();
void FUN_L00_00210748();
void FUN_L00_00210928(void) {
    if (hero.unk308 == 1 || (u32)(hero.state.control_mode - 0x15) < 2 ||
        FUN_L00_0020d568_u()) {
        hero.unk20A7 = 1;
        hero.unk20AC = 1;
    }
    if (FUN_L00_0020d568_u() || hero.state.control_mode == 0x15 ||
        hero.state.control_mode == 0x16 || hero.state.control_mode == 3 ||
        hero.state.current == 0x12) {
        hero.unk20AE = 1;
    } else {
        hero.unk20AE = 0;
    }
    FUN_L00_0020ea80();
    FUN_L00_0020f580();
    FUN_L00_00234808();
    FUN_L00_002080b0();
    FUN_L00_00210748();
}
void FUN_L00_0020e698_210a08(void) __asm__("FUN_L00_0020e698");
void FUN_L00_00210748_210a08(void) __asm__("FUN_L00_00210748");
void FUN_L00_00262840_210a08(void *) __asm__("FUN_L00_00262840");
void FUN_L00_00232fe8_210a08(void) __asm__("FUN_L00_00232fe8");
void FUN_L00_00206c08_210a08(void) __asm__("FUN_L00_00206c08");
void FUN_L00_00205538_210a08(void) __asm__("FUN_L00_00205538");
void FUN_L00_00211380_210a08(void) __asm__("FUN_L00_00211380");
void FUN_L00_00232628_210a08(void) __asm__("FUN_L00_00232628");
void FUN_L00_00257024_210a08(char *) __asm__("FUN_L00_00257024");
void FUN_L00_00207a58_210a08(void) __asm__("FUN_L00_00207a58");
extern int hero_set_state(int, int) __asm__("FUN_L00_002223f8");
void FUN_L00_00210a08(int mode, int b, char *m) {
    struct Hero *g;
    FUN_L00_0020e698_210a08();
    g = &hero;
    g->unk20A6 = 1;
    FUN_L00_00210748_210a08();
    g->moby = (struct Moby *)g->unkA88;
    FUN_L00_00262840_210a08(&g->trail);
    *(int *)((char *)g->moby + 0x98) = -1;
    FUN_L00_00232fe8_210a08();
    FUN_L00_00206c08_210a08();
    FUN_L00_00205538_210a08();
    g->unk20A4 = mode;
    g->unkA84 = (u8 *)m;
    g->moby = (struct Moby *)m;
    FUN_L00_00211380_210a08();
    g->unk220 = g->unk228;
    g->unk224 = g->unk22C;
    *(unsigned short *)((char *)g->moby + 0x34) |= 6;
    g->unkA90 = 1.0f;
    g->unkA94 = 1.0f;
    FUN_L00_00232628_210a08();
    FUN_L00_00257024_210a08((char *)g->moby);
    FUN_L00_00207a58_210a08();
    g->unk22CC = b;
    switch (mode) {
    case 1:
        g->health.unk22B0 = *(unsigned short *)&g->health.hp;
        g->health.hp = g->health.unk22AC;
        break;
    case 2:
        g->unk1630 = 200;
        break;
    }
    hero_set_state(b, 1);
}
extern s32 D_L00_0015F5C4_210b30 __asm__("D_L00_0015F5C4");
extern void FUN_0020c828_210b30(void *) __asm__("FUN_0020c828");
extern void FUN_001ff570_210b30(int, int) __asm__("FUN_001ff570");
extern void FUN_L00_00205538_210b30(void) __asm__("FUN_L00_00205538");
extern void FUN_L00_00206c08_210b30(void) __asm__("FUN_L00_00206c08");
extern void FUN_L00_00232628_210b30(void) __asm__("FUN_L00_00232628");
extern int hero_set_state(int, int) __asm__("FUN_L00_002223f8");

void FUN_L00_00210b30(void) {
    struct Hero *g = &hero;
    unsigned char *m;
    if (g->unk20A4 == 1) {
        g->health.unk22AC = g->health.hp;
        g->health.hp = g->health.unk22B0;
        if (g->unk1620) {
            FUN_0020c828_210b30(g->unk1620);
            g->unk1620 = 0;
        }
        if (g->unk1624) {
            FUN_0020c828_210b30(g->unk1624);
            g->unk1624 = 0;
        }
    }
    {
        struct Hero *g2 = &hero;
        if (g2->unk20A4 == 2 && g2->unk1634 != -1) {
            FUN_001ff570_210b30(g2->unk1634, 0);
            g2->unk1634 = -1;
        }
        FUN_L00_00205538_210b30();
    }
    {
        struct Hero *g3 = &hero;
        g3->unk20A4 = 0;
        m = g3->unkA84;
        if (m) {
            *(u16 *)(m + 0x34) &= ~6;
        }
        g3->unkA84 = 0;
        if (g3->unkA8C) {
            FUN_0020c828_210b30(g3->unkA8C);
            g3->unkA8C = 0;
        }
        FUN_L00_00206c08_210b30();
        {
            unsigned char *o = g3->unkA88;
            g3->moby = (struct Moby *)o;
            qcopy(o + 0x10, &g3->motion.pos);
            *(int *)(o + 0x98) = 0;
        }
        g3->unkA94 = 1.0f;
        FUN_L00_00232628_210b30();
        if (g3->state.current != 100 ||
            (D_L00_0015F5C4_210b30 != 2 && D_L00_0015F5C4_210b30 != 6)) {
            hero_set_state(0, 1);
        }
    }
}
#define NOT_SDA

#define MACRO_ADDR

/* Ported from rac1-decomp (src/overlays/shared/help_0020CDF0.c: func_L00_00211338), where it is exact; names translated to the US level program. */

extern void FUN_001f9c48(float *, float *, float);

/* Scales x/y by s and sets or scales z, per component or through FUN_001f9c48. */
void FUN_L00_00210c80(float *v, int each, float s, float z) {
    if (each) {
        v[0] *= s;
        v[1] *= s;
        v[2] *= z;
    } else {
        FUN_001f9c48(v, v, s);
        v[2] = z;
    }
}

typedef struct {
    u8 pad0[0x10];
    OvlQuad v10;
    u8 *p20;
    s32 i24;
    u8 b28;
    u8 pad29[3];
    f32 f2C;
    s32 i30;
    u8 *p34;
    u8 pad38[8];
} T_210ce8;

typedef union {
    OvlQuad q;
    f32 f[4];
    s32 i[4];
} V_210ce8;

extern s32 D_L00_0015F5C4_210ce8 __asm__("D_L00_0015F5C4");
extern T_210ce8 D_L00_00178100_210ce8[] __asm__("D_L00_00178100");
extern s32 D_0015ED84_210ce8 __asm__("D_0015ED84");
extern s32 D_0013DF88_210ce8[] __asm__("D_0013DF88");
extern s32 D_0015EEA8_210ce8 __asm__("D_0015EEA8");
extern f32 D_0015ED6C_210ce8 __asm__("D_0015ED6C");

s32 FUN_001fa6d0_210ce8(f32) __asm__("FUN_001fa6d0");
void FUN_L00_00206c08_210ce8(void) __asm__("FUN_L00_00206c08");
void FUN_001f9a28_210ce8(void *, void *, void *) __asm__("FUN_001f9a28");
f32 FUN_001fa580_210ce8(f32, f32) __asm__("FUN_001fa580");
f32 FUN_001f9dc8_210ce8(f32) __asm__("FUN_001f9dc8");
f32 FUN_001f9de0_210ce8(f32) __asm__("FUN_001f9de0");
void FUN_001f9a10_210ce8(void *, void *, void *) __asm__("FUN_001f9a10");
extern int hero_set_state(int, int) __asm__("FUN_L00_002223f8");
void FUN_L00_00216de8_210ce8(s32, s32) __asm__("FUN_L00_00216de8");
void FUN_L00_002a9be0_210ce8(void) __asm__("FUN_L00_002a9be0");
void FUN_001f99f8_210ce8(void *) __asm__("FUN_001f99f8");
void FUN_L00_00210c80_210ce8(void *, s32, f32, f32) __asm__("FUN_L00_00210c80");

s32 FUN_L00_00210ce8(s32 arg) {
    u8 *m;
    T_210ce8 *tbl;
    u8 *mob;
    s32 flag;
    s32 id;
    f32 a, b, e;
    V_210ce8 v;

    if (hero.state.control_mode == 0x14) {
        return 0;
    }
    if (hero.state.control_mode == 7) {
        return 0;
    }
    if (hero.state.current == 0x32) {
        return 0;
    }
    if (hero.unk1C0 != 0) {
        return 0;
    }
    if (D_L00_0015F5C4_210ce8 != 0) {
        return 0;
    }
    hero.unk2280 = 0;
    m = ((u8 *)hero.moby);
    if (m[0xA4] == 0xFF) {
        return 0;
    }
    tbl = &D_L00_00178100_210ce8[m[0xA4]];
    if (tbl->p34 != m) {
        return 0;
    }
    if (hero.unk20A4 == 2) {
        if (!(tbl->i24 & 2)) {
            return 0;
        }
    } else if ((tbl->i24 ^ 1) & 1) {
        return 0;
    }
    D_0013DF88_210ce8[D_0015ED84_210ce8]++;
    hero.unk2280 = (struct Moby *)tbl->p20;
    D_0015EEA8_210ce8++;
    if (hero.state.control_mode == 0xF) {
        hero.unk5BE = 1;
        return 0;
    }
    if (hero.unk20A4 == 2) {
        hero.unk1630 -= FUN_001fa6d0_210ce8(tbl->f2C);
        if (hero.unk1630 < 0) {
            hero.unk1630 = 0;
        }
    }
    if (arg == 0) {
        return 1;
    }
    FUN_L00_00206c08_210ce8();
    flag = 0;
    if (tbl->i30 & 1) {
        qcopy(&v, &tbl->v10);
        if (*(f32 *)((u8 *)tbl + 0x1C) == 5627.9248046875f) {
            flag = 1;
        }
    } else if (tbl->p20 != 0) {
        FUN_001f9a28_210ce8(&v, &hero.motion.pos, tbl->p20 + 0x10);
    } else {
        v.f[0] = FUN_001f9dc8_210ce8(FUN_001fa580_210ce8(hero.motion.rot.f[2], 3.1415927f));
        v.f[1] = FUN_001f9de0_210ce8(FUN_001fa580_210ce8(hero.motion.rot.f[2], 3.1415927f));
        v.i[2] = 0;
    }
    switch (hero.unk20A4) {
    case 0:
        mob = ((u8 *)hero.unk2280);
        if (mob != 0 && (*(s16 *)(mob + 0xA6) == 0x4EB || *(s16 *)(mob + 0xA6) == 0x558)) {
            id = 0x80;
        call_ret:
            hero_set_state(id, 1);
            return 1;
        }
        if (hero.state.control_mode == 0x16) {
            hero_set_state(0x6D, 1);
            hero.motion.unk120.f[2] = D_0015ED6C_210ce8 * 7.0f;
            return 1;
        }
        if (hero.state.control_mode == 0x12) {
            mob = ((u8 *)hero.unk2280);
            if (mob != 0 && *(s16 *)(mob + 0xA6) == 0x28F) {
                id = 0x82;
                goto call_ret;
            }
            hero_set_state(0x75, 1);
        } else if (hero.state.control_mode == 0x11) {
            mob = ((u8 *)hero.unk2280);
            if (mob != 0 && *(s16 *)(mob + 0xA6) == 0x28F) {
                id = 0x82;
                goto call_ret;
            }
            if (D_0015ED84_210ce8 == 0xF || D_0015ED84_210ce8 == 0x11) {
                mob = ((u8 *)hero.unk2280);
                if (mob != 0 && (*(s16 *)(mob + 0xA6) == 0x28F || *(s16 *)(mob + 0xA6) == 0x7B ||
                                 *(s16 *)(mob + 0xA6) == 0x29D)) {
                    FUN_L00_00216de8_210ce8(0x1C, 0);
                }
            }
            hero_set_state(0x76, 1);
        } else if (hero.state.control_mode == 3) {
            mob = ((u8 *)hero.unk2280);
            if (mob != 0) {
                id = 0x82;
                if (*(s16 *)(mob + 0xA6) == 0x28F) {
                    goto call_ret;
                }
            }
            hero_set_state(0x16, 1);
        } else {
            hero_set_state(0x16, 1);
        }
        e = D_0015ED6C_210ce8;
        a = e * 5.7f;
        b = e * 2.4f;
        if (hero.unk12E7 != 0) {
            a = 0.0f;
            b = e * 1.7f;
        }
        FUN_L00_00210c80_210ce8(&v, flag, a, b);
        if (flag != 0 && tbl->b28 == 4) {
            v.f[2] += v.f[2];
        }
        break;
    case 1:
        hero_set_state(0x46, 1);
        FUN_L00_00210c80_210ce8(&v, flag, D_0015ED6C_210ce8 * 5.0f, D_0015ED6C_210ce8 * 3.0f);
        break;
    case 2:
        if ((tbl->i24 & 4) || hero.unk1630 <= 0) {
            hero_set_state(0x5D, 1);
            FUN_L00_002a9be0_210ce8();
            if (hero.air_frames.s == 0) {
                FUN_L00_00210c80_210ce8(&v, flag, D_0015ED6C_210ce8 * 7.0f,
                                        D_0015ED6C_210ce8 * 3.5f);
                break;
            }
        }
        FUN_001f99f8_210ce8(&v);
        break;
    case 3:
        hero_set_state(0x56, 1);
        FUN_L00_00210c80_210ce8(&v, flag, D_0015ED6C_210ce8 * 5.0f, D_0015ED6C_210ce8 * 2.4f);
        break;
    }
    FUN_001f9a10_210ce8(&hero.motion.velocity, &hero.motion.velocity, &v);
    FUN_001f9a10_210ce8(&hero.motion.unk100, &hero.motion.unk100, &v);
    return 1;
}
extern s32 D_0015ED84_211250 __asm__("D_0015ED84");
extern s32 D_0015EEAC_211250 __asm__("D_0015EEAC");
extern s32 D_0013DFD8_211250[] __asm__("D_0013DFD8");
extern s32 D_0014E990_211250[][16] __asm__("D_0014E990");
extern s32 D_0014EE90_211250[] __asm__("D_0014EE90");
extern s32 D_L00_0015F5A4_211250 __asm__("D_L00_0015F5A4");
extern void FUN_L00_00203a28_211250(void) __asm__("FUN_L00_00203a28");
extern int FUN_001f96f8_211250(int) __asm__("FUN_001f96f8");
extern void FUN_001f4a58_211250(int) __asm__("FUN_001f4a58");

void FUN_L00_00211250(void) {
    s32 lvl = D_0015ED84_211250;
    char *m;
    u32 t;
    D_0013DFD8_211250[lvl]++;
    D_0015EEAC_211250++;
    if (((char *)hero.unk2280) != 0 && *(s16 *)(((char *)hero.unk2280) + 0xA6) == 0x4D &&
        lvl == 15) {
        D_L00_0015F5A4_211250 = 1;
    }
    FUN_L00_00203a28_211250();
    m = ((char *)hero.unk2280);
    if (m != 0 && *(u8 *)(m + 0xB0) != 0xFF) {
        D_0014E990_211250[D_0015ED84_211250][*(u8 *)(m + 0xB0)]++;
        D_0014EE90_211250[*(u8 *)(m + 0xB0)]++;
    }
    FUN_001f4a58_211250(FUN_001f96f8_211250(0x10));
    hero.unk20B1 = 1;
}
typedef struct {
    u8 pad[0xA6];
    s16 f;
} K2;
/* True when p is non-null and its field f is 0x47. */
s32 FUN_L00_00211360(K2 *p) {
    if (p == 0) {
        return 0;
    }
    if (p->f == 0x47) {
        return 1;
    }
    return 0;
}
extern f32 D_0015ED60_211380 __asm__("D_0015ED60");
extern f32 D_0015ED64_211380 __asm__("D_0015ED64");
extern f32 D_0015ED6C_211380 __asm__("D_0015ED6C");
f32 FUN_001f9b80_211380(void *, void *) __asm__("FUN_001f9b80");
f32 approach_value_211380(f32, f32, f32 *) __asm__("FUN_00213ed8");
void FUN_L00_0025b8c0_211380(f32 *, f32 *, f32, f32, f32, f32) __asm__("FUN_L00_0025b8c0");
void FUN_L00_00211380(void) {
    switch (hero.unk20A4) {
    case 0:
        hero.unk228 = 0.8f;
        hero.unk22C = 0.7f;
        hero.unk230 = 0.45f;
        break;
    case 1:
        hero.unk228 = 0.59999996f;
        hero.unk22C = 0.45000002f;
        hero.unk230 = 0.3f;
        break;
    case 2:
        hero.unk228 = 5.25f;
        hero.unk22C = 4.45f;
        hero.unk230 = 3.75f;
        break;
    case 3:
        hero.unk228 = 0.8f;
        hero.unk22C = 0.6f;
        hero.unk230 = 0.45f;
        break;
    }
    if (hero.state.control_mode == 4) {
        if (hero.state_timer > hero.unk420 && hero.unk41E == 0)
            hero.unk22C = hero.unk434;
    } else if (hero.state.current == 6) {
        hero.unk22C = 0.5f;
    } else if (hero.state.current == 4) {
        hero.unk228 = 0.35000002f;
    } else if ((u32)(hero.state.control_mode - 0x11) < 2) {
        hero.unk228 = 0.0f;
        hero.unk22C = 0.0f;
    } else if (hero.unk12E2 && hero.unk300) {
        hero.unk228 = 0.8f;
        hero.unk22C = 0.9f;
    } else if (hero.state.current == 0x7F) {
        hero.unk230 = 0.8f;
    }
    if (!hero.unk257 || hero.state.prev_control_mode == 0x12 || hero.state.control_mode == 0x11 || hero.base_condition ||
        FUN_001f9b80_211380(hero.unk210.f, hero.motion.pos.f) > hero.unk234 * 0.5f) {
        f32 *q = &hero.unk220;
        struct Hero *b = &hero;
        approach_value_211380(b->unk228, D_0015ED60_211380 * 0.02f, q);
        approach_value_211380(b->unk22C, D_0015ED60_211380 * 0.02f, q + 1);
        FUN_L00_0025b8c0_211380(q + 5, q + 6, b->unk230, D_0015ED64_211380 * 0.02f,
                                D_0015ED64_211380 * 0.3f, D_0015ED6C_211380 * 4.0f);
    }
}
#ifndef NON_MATCHING
INCLUDE_ASM("config/us/overlays/asm/FUN_L00_00211670.s", FUN_L00_00211670);
#else
extern u8 FUN_L00_00233440(void);
extern f32 FUN_L00_00211830(void);
extern f32 FUN_L00_001ff408(void *);
extern void FUN_L00_00217970(void);
extern void FUN_L00_001ffa70(void *, void *);
extern void FUN_L00_001ff9e8(void *);
extern void matrix_from_basis_rows(void *, void *) __asm__("FUN_L00_001ffcf8");
extern void FUN_L00_00221310(void);
extern void FUN_L00_002215c8(void);
extern u8 D_0013C940_211670[] __asm__("D_0013C940");

void FUN_L00_00211670(void)
{
    s32 index;
    s32 buttons;
    u8 mode;
    struct Hero *p;
    u8 *source;
    Vec4 *positions;

    mode = FUN_L00_00233440();
    p = &hero;
    p->unk20B3 = mode;
    p->unk229C = FUN_L00_00211830();
    p->unk240 = 0;
    source = D_0013C940_211670;
    p->unk1D20 = *(f32 *)(source + 0x108);
    p->unk1D24 = *(f32 *)(source + 0x10C);
    if (FUN_L00_001ff408(&p->unk1D20) < 0.25f) {
        buttons = *(s32 *)(source + 0x1B0);
        p->unk1D20 = (f32)(((buttons >> 13) & 1) - ((buttons >> 15) & 1));
        p->unk1D24 = (f32)(((buttons >> 14) & 1) - ((buttons >> 12) & 1));
    }
    FUN_L00_00217970();

    p->unk2128[p->unk21A8] = p->motion.rot.f[2];
    p->unk21A8 = (p->unk21A8 + 1) % 32;
    ++p->unk21AC;
    if (p->unk21AC > 0x20)
        p->unk21AC = 0x20;

    positions = p->unk1B00;
    index = p->unk21B0;
    qcopy_nc(&positions[index], &p->motion.pos);
    p->unk21B0 = (index + 1) % 32;
    ++p->unk21B4;
    if (p->unk21B4 > 0x20)
        p->unk21B4 = 0x20;

    FUN_L00_001ffa70(p, &p->motion.rot);
    FUN_L00_001ff9e8(p->unk40);
    matrix_from_basis_rows(p->unk40, p);
    FUN_L00_00211380();
    FUN_L00_00221310();
    FUN_L00_002215c8();
}
#endif /* NON_MATCHING */
#define NOT_SDA

#define MACRO_ADDR

/* Ported from rac1-decomp (src/overlays/shared/help_0020CDF0.c: func_L00_00211EE8), where it is exact; names translated to the US level program. */

extern float FUN_001f9b20(void *);

/* Length from FUN_001f9b20 on hero.unk1D20, capped at 1. */
float FUN_L00_00211830(void) {
    float len = FUN_001f9b20(&hero.unk1D20);

    if (1.0f < len) {
        len = 1.0f;
    }
    return len;
}
#define NOT_SDA

#define MACRO_ADDR

/* Whether T lies in the window that ends at D_0013F450 + 0xAA8 and is
   +0xAAC long (T before the end, within that length of it). */
/* Ported from rac1-decomp (src/overlays/shared/help_0020CDF0.c: func_L00_00211F28), where it is exact; names translated to the US level program. */


/* True when t is before the time at hero.unkAA8 by at most the span hero.unkAAC. */
int FUN_L00_00211870(float t) {
    float end = hero.unkAA8;

    if (t < end) {
        if (end - t <= hero.unkAAC) {
            return 1;
        }
    }
    return 0;
}
/* Clears hero.target_speed and unk194 as words. */
void FUN_L00_002118b0(void) {
    struct Hero *p = &hero;
    *(int *)&p->target_speed = 0;
    *(int *)&p->ground_speed = 0;
}
typedef union {
    OvlQuad q;
    float f[4];
} V_2118c8;
extern unsigned char D_0015EDB4_2118c8 __asm__("D_0015EDB4");
extern float D_L00_00166DD8_2118c8 __asm__("D_L00_00166DD8") __attribute__((section(".data")));
extern unsigned char D_L00_00166FD0_2118c8[] __asm__("D_L00_00166FD0")
    __attribute__((section(".data")));
extern float FUN_001f99c0_2118c8(float) __asm__("FUN_001f99c0");
extern float FUN_001f9b20_2118c8(void *) __asm__("FUN_001f9b20");
extern void FUN_L00_001ff378_2118c8(void *, void *, float) __asm__("FUN_L00_001ff378");
extern float FUN_L00_002332d0_2118c8(void) __asm__("FUN_L00_002332d0");
extern void FUN_001f9cf8_2118c8(void *, void *, void *) __asm__("FUN_001f9cf8");
extern float FUN_001f9e90_2118c8(float, float) __asm__("FUN_001f9e90");
extern int FUN_001fa6d0_2118c8(float) __asm__("FUN_001fa6d0");
extern float FUN_001fa6c0_2118c8(int) __asm__("FUN_001fa6c0");
extern float FUN_001fa580_2118c8(float, float) __asm__("FUN_001fa580");

void FUN_L00_002118c8(float scale, int mode) {
    V_2118c8 v;
    V_2118c8 q;
    float x;
    float len;
    float y;

    v.f[1] = hero.unk1D24;
    v.f[0] = hero.unk1D20;
    if (mode == 1) {
        if (FUN_001f99c0_2118c8(v.f[1]) > 0.7f && FUN_001f99c0_2118c8(v.f[0]) < 0.12f) {
            v.f[0] = 0.0f;
        }
        if (FUN_001f99c0_2118c8(v.f[0]) > 0.7f && FUN_001f99c0_2118c8(v.f[1]) < 0.12f) {
            v.f[1] = 0.0f;
        }
    }
    len = FUN_001f9b20_2118c8(&v);
    if (len > 1.0f) {
        FUN_L00_001ff378_2118c8(&v, &v, len);
    }
    if (v.f[0] == 0.0f && v.f[1] == 0.0f) {
        hero.target_speed = 0.0f;
        if (hero.unk20B3) {
            hero.motion.unk180 = FUN_L00_002332d0_2118c8();
        } else {
            hero.motion.unk180 = hero.motion.rot.f[2];
        }
        q.q = 0;
        q.f[0] = 1.0f;
        FUN_001f9cf8_2118c8(&hero.motion.unk170, &q, (char *)hero.moby + 0xC0);
        return;
    }
    hero.motion.unk180 = FUN_001f9e90_2118c8(-v.f[1], -v.f[0]);
    if (mode == 2) {
        hero.motion.unk180 =
            FUN_001fa6c0_2118c8(FUN_001fa6d0_2118c8((hero.motion.unk180 + 3.1415927f) * 0.63662f + 0.5f) & 3) *
                1.5707964f -
            3.1415927f;
    }
    if (mode == 3) {
        hero.motion.unk180 =
            FUN_001fa6c0_2118c8(FUN_001fa6d0_2118c8((hero.motion.unk180 + 3.1415927f) * 1.27324f + 0.5f) & 7) *
                0.785398f -
            3.1415927f;
    }
    if (mode == 4) {
        hero.motion.unk180 = FUN_001fa580_2118c8(hero.motion.unk180, hero.motion.rot.f[2]);
    } else {
        hero.motion.unk180 = FUN_001fa580_2118c8(hero.motion.unk180, D_L00_00166DD8_2118c8);
    }
    x = v.f[0];
    y = v.f[1];
    v.f[1] = -x;
    v.f[0] = -y;
    v.f[2] = v.f[3] = 0.0f;
    if (D_0015EDB4_2118c8) {
        v.f[1] = x;
    }
    FUN_001f9cf8_2118c8(&hero.motion.unk170, &v, D_L00_00166FD0_2118c8);
    hero.target_speed = scale * FUN_001f9b20_2118c8(&v);
}
extern float D_L00_0017BDB8[];

/* Hero speed clamp after a move update (twin of FUN_L01_00232290): in state 0x3F it scales unk190 by 3.5 frame steps with a floor; otherwise it picks a table speed, and in state 0x73 it slows by 0.8 down to a floor. */
void FUN_L00_00211be8(void) {
    FUN_L00_002118c8(1.0f, 0);
    if (hero.state.current == 0x3F) {
        float min = frame_time + frame_time;
        hero.target_speed = frame_time * 3.5f * hero.target_speed;
        if (hero.target_speed < min)
            hero.target_speed = min;
        return;
    }
    if (0.0f < hero.target_speed) {
        if (hero.target_speed < D_L00_0017BDB8[3])
            hero.target_speed = D_L00_0017BDB8[2] * frame_time;
        else
            hero.target_speed = D_L00_0017BDB8[6] * frame_time;
    }
    if (hero.state.current == 0x73) {
        float v = hero.target_speed * 0.8f;
        float m = frame_time * 2.5f;
        hero.target_speed = v;
        if (v < m)
            hero.target_speed = m;
    }
}
#define NOT_SDA

#define MACRO_ADDR

/* Ported from rac1-decomp (src/overlays/shared/help_0020CDF0.c: func_L00_002123B0), where it is exact; names translated to the US level program. */

extern char D_0013E533[];
extern void FUN_001fa050(void *, void *);
extern void FUN_001fa378(void *, void *, void *);
extern void FUN_00214598(void *, void *);

/* Multiplies the 001fa050 matrices of (x, y, z) and of hero.unk40, stored back by 00214598. */
void FUN_L00_00211cf8(float x, float y, float z) {
    float in[3];
    float t[16], u[16];
    in[0] = x;
    in[1] = y;
    in[2] = z;
    FUN_001fa050(t, in);
    FUN_001fa050(u, D_0013E533 + 0xEAD);
    FUN_001fa378(u, u, t);
    FUN_00214598(u, D_0013E533 + 0xEAD);
}
typedef float V4_211d78[4] __attribute__((aligned(16)));
void FUN_001f9d20(void *, void *, void *);
float FUN_001f9e90(float, float);
void FUN_L00_00211cf8(float, float, float);
extern float FUN_L00_0025bc98(char *, char *, int, float, float, float, float);
void FUN_L00_00211d78(int a, float x, float y, float z) {
    V4_211d78 t;
    float out;
    float zero = 0.0f;
    float r;
    FUN_001f9d20(t, &hero.motion.unk170, hero.unk40);
    r = FUN_001f9e90(t[0], t[1]);
    out = zero;
    hero.motion.unk188 = FUN_L00_0025bc98((char *)&out, (char *)&hero.motion.unk184, a, r, x, y, z);
    FUN_L00_00211cf8(zero, zero, out);
}
#define NOT_SDA

#define MACRO_ADDR

/* Ported from rac1-decomp (src/overlays/shared/help_0020CDF0.c: func_L00_002124E8), where it is exact; names translated to the US level program. */

extern float FUN_L00_0025bc98(char *, char *, int, float, float, float, float);
extern void FUN_L00_00211d78(int, float, float, float);

/* Calls 00211d78 when hero.unk20B3 is set, else updates hero.motion.unk188 via 0025bc98. */
void FUN_L00_00211e30(int a, float x, float y, float z) {
    struct Hero *g = &hero;
    if (g->unk20B3 != 0) {
        FUN_L00_00211d78(a, x, y, z);
    } else {
        g->motion.unk188 =
            FUN_L00_0025bc98(&g->motion.rot.f[2], &g->motion.unk184, a, g->motion.unk180, x, y, z);
    }
}
#define NOT_SDA

#define MACRO_ADDR

/* Ported from rac1-decomp (src/overlays/shared/help_0020CDF0.c: func_L00_00212550), where it is exact; names translated to the US level program. */

extern int FUN_L00_0020d498_u(int) __asm__("FUN_L00_0020d498");
extern void FUN_L00_00211e30(int, float, float, float);

void FUN_L00_00211e98(void) {
    float a, b, c;
    if (FUN_L00_0020d498_u(0) == 16) {
        a = frame_scale_sq * 0.006f;
        b = frame_scale_sq * 0.07f;
        c = frame_time * 13.962634086608887f;
    } else {
        a = frame_scale_sq * 0.002f;
        b = frame_scale_sq * 0.07f;
        c = frame_time * 6.981317043304443f;
    }
    FUN_L00_00211e30(0, a, b, c);
}
extern float D_0015ED64_211f38 __asm__("D_0015ED64");
extern float D_0015ED6C_211f38 __asm__("D_0015ED6C");
extern int FUN_L00_0020d498_211f38(int) __asm__("FUN_L00_0020d498");
extern void FUN_L00_00211e30_211f38(int, float, float, float) __asm__("FUN_L00_00211e30");

void FUN_L00_00211f38(void) {
    struct Hero *g = &hero;
    float t, a, b, c;
    t = (g->unk229C + 1.0f) * 0.5f;
    a = D_0015ED64_211f38 * 0.019f * t;
    b = D_0015ED64_211f38 * 0.1f;
    c = D_0015ED6C_211f38 * 9.948377f * t;
    if (g->unk3BE) {
        a *= 1.1f;
        c *= 1.2f;
    }
    switch (FUN_L00_0020d498_211f38(0)) {
    case 15:
    case 16:
    case 21:
        if (g->unk20A8) {
            a = D_0015ED64_211f38 * 0.003f;
            b = D_0015ED64_211f38 * 0.04f;
            c = D_0015ED6C_211f38 * 4.3633232f;
        }
        break;
    }
    FUN_L00_00211e30_211f38(0, a, b, c);
}
void FUN_00213ed8_00212088(f32 *, f32, f32) __asm__("FUN_00213ed8");
/* Approaches field b toward a, at rate x while below it and y otherwise. */
void FUN_L00_00212088(f32 x, f32 y) {
    struct Hero *p = &hero;
    if (p->ground_speed < p->target_speed)
        FUN_00213ed8_00212088(&p->ground_speed, p->target_speed, x);
    else
        FUN_00213ed8_00212088(&p->ground_speed, p->target_speed, y);
}
extern float fast_cos(float) __asm__("FUN_001f9dc8");

/* Builds a direction vector into hero.motion.velocity: either func_00215C00's
   spherical formula from the hero.ground_speed radius, the clamped angle arg0
   (falling back to hero.motion.rot.z above pi) and hero +0x2E4, or, when
   hero.unk20B3 is set, a flat vector (r,0,0) rotated by the matrix
   func_001FA218 builds from the hero moby's +0x40 axis. */
/* Ported from rac1-decomp (src/overlays/shared/help_0020CDF0.c: func_L00_00212790), where it is exact; names translated to the US level program. */

extern float fast_sin(float) __asm__("FUN_001f9de0");
extern void func_001F9EE8(void *, void *, void *) __asm__("FUN_001f9d20");
extern void func_001FA218(void *, void *) __asm__("FUN_001fa050");
extern void func_00215C00(void *, float, float, float) __asm__("FUN_00214db0");

void FUN_L00_002120d8(float radians) {
    struct Hero *g = &hero;
    float y;
    float r;
    float out[4];

    y = g->motion.rot.f[2];
    if (radians <= 3.14159274f) {
        y = radians;
    }
    r = g->ground_speed;

    if (g->unk20B3 != 0) {
        float matrix[16];
        float vec[4];

        vec[0] = fast_cos(0.0f) * r;
        vec[1] = fast_sin(0.0f) * r;
        vec[2] = 0.0f;

        func_001FA218(matrix, ((char *)g->moby) + 0x40);
        func_001F9EE8(vec, vec, matrix);

        qcopy(out, vec);
    } else {
        func_00215C00(out, r, y, g->unk2E4.f);
    }

    qcopy(&hero.motion.velocity, out);
}
typedef unsigned int u128_2121c0_002121c0 __attribute__((mode(TI), aligned(16)));
typedef union {
    u128_2121c0_002121c0 q_002121c0;
    float f[4];
} V_2121c0_002121c0;
extern float D_0015ED70_002121c0 __asm__("D_0015ED70");
extern float FUN_001f9b20_002121c0(void *) __asm__("FUN_001f9b20");
extern float FUN_001f9e90_002121c0(float, float) __asm__("FUN_001f9e90");
extern void FUN_00125180_002121c0(void *, void *) __asm__("FUN_00125180");
extern void FUN_001f9a68_002121c0(void *, void *, float) __asm__("FUN_001f9a68");
extern void FUN_001f9a10_002121c0(void *, void *, void *) __asm__("FUN_001f9a10");

void FUN_L00_002121c0(void) {
    struct Hero *g = &hero;
    V_2121c0_002121c0 v;
    float d, x;
    if (g->air_frames.s == 0)
        return;
    if (!(g->ground_distance < 0.15f))
        return;
    if (!(0.0f < g->motion.unk100.f[2]))
        return;
    if (g->unk257 == 0)
        return;
    if (!(0.0f < g->unk200.f[2]))
        return;
    if (!(0.87266463f <= FUN_001f9e90_002121c0(g->unk200.f[2], FUN_001f9b20_002121c0(&g->unk200))))
        return;
    qcopy(&v, &g->unk200);
    v.f[2] = 0.0f;
    FUN_00125180_002121c0(&v, &v);
    d = -g->motion.velocity.f[0] * v.f[0] - g->motion.velocity.f[1] * v.f[1];
    if (0.0f < d) {
        FUN_001f9a68_002121c0(&v, &v, d);
        FUN_001f9a10_002121c0(&g->motion.velocity, &g->motion.velocity, &v);
        x = D_0015ED70_002121c0 * 54.0f;
        g->motion.velocity.f[2] -= x + x;
    }
}
typedef struct {
    f32 f[4];
} V_212318;
typedef struct {
    u8 p0[0x18];
    s32 i18;
    s32 i1C;
    u8 p1[0x40 - 0x20];
    V_212318 v40;
} X_212318;
extern char D_0013F3D0_212318[] __asm__("D_0013F3D0") __attribute__((section(".data")));
extern X_212318 D_L00_00173E40_212318 __asm__("D_L00_00173E40") __attribute__((section(".data")));
extern s32 D_L00_00173E5C_212318 __asm__("D_L00_00173E5C") __attribute__((section(".data")));
extern f32 D_0015ED6C_212318 __asm__("D_0015ED6C");
extern f32 FUN_L00_002339d0_212318(void *) __asm__("FUN_L00_002339d0");
extern f32 FUN_001f9b20_212318(void *) __asm__("FUN_001f9b20");
extern f32 FUN_001f9dc8_212318(f32) __asm__("FUN_001f9dc8");
extern f32 FUN_001f9de0_212318(f32) __asm__("FUN_001f9de0");
extern void FUN_001f9a68_212318(void *, void *, f32) __asm__("FUN_001f9a68");
extern void FUN_001f9a10_212318(void *, void *, void *) __asm__("FUN_001f9a10");
extern int FUN_001efa68_212318(void *, void *, int, void *, int) __asm__("FUN_001efa68");
extern int FUN_001f0b58_212318(void) __asm__("FUN_001f0b58");
extern f32 FUN_001f9e90_212318(f32, f32) __asm__("FUN_001f9e90");
extern void FUN_00125180_212318(void *, void *) __asm__("FUN_00125180");
#define X D_L00_00173E40_212318

void FUN_L00_00212318(int force) {
    V_212318 a, d1, b, d2;
    char *src;
    struct Hero *g;
    f32 off, k, c, ang, t;
    int r;

    if (hero.unk308 != 0)
        return;
    if (FUN_L00_002339d0_212318(&hero.motion.velocity) < D_0015ED6C_212318 * 0.1f)
        return;
    off = 0.3700000047683716f;
    k = 0.5f;
    if ((u32)(hero.state.control_mode - 0x11) < 2) {
        off = 0.0f;
        k = 0.7f;
    } else if (hero.unk20A4 == 1) {
        off = 0.35f;
        k = 0.27000001072883606f;
    } else if (hero.unk20A4 == 2) {
        off = 1.5f;
        k = 5.0f;
    }
    src = D_0013F3D0_212318;
    qcopy(&a, src);
    a.f[2] += off;
    qcopy(&b, src);
    b.f[2] += off * 0.3f;
    if (force || FUN_001f9b20_212318(src + 0x60) < 0.01f) {
        g = (struct Hero *)(src - 0x80);
        c = 1.4f;
        d1.f[0] = FUN_001f9dc8_212318(g->motion.rot.f[2]) * k;
        d1.f[1] = FUN_001f9de0_212318(g->motion.rot.f[2]) * k;
        *(s32 *)&d1.f[2] = 0;
        d2.f[0] = FUN_001f9dc8_212318(g->motion.rot.f[2]) * k * c;
        d2.f[1] = FUN_001f9de0_212318(g->motion.rot.f[2]) * k * c;
        *(s32 *)&d2.f[2] = 0;
    } else {
        qcopy(&d1, src + 0x60);
        *(s32 *)&d1.f[2] = 0;
        FUN_001f9a68_212318(&d1, &d1, k / FUN_001f9b20_212318(&d1));
        qcopy(&d2, &d1);
        FUN_001f9a68_212318(&d2, &d2, 1.4f);
    }
    FUN_001f9a10_212318(&d1, &d1, &a);
    FUN_001f9a10_212318(&d2, &d2, &b);
    r = -1;
    if (FUN_001efa68_212318(&b, &d2, 4, hero.moby, 0) && D_L00_00173E5C_212318 > 0)
        r = FUN_001f0b58_212318();
    ang = 0.0f;
    if (FUN_001efa68_212318(&a, &d1, 4, hero.moby, 0) && X.i1C > 0)
        ang = FUN_001f9e90_212318(X.v40.f[2], FUN_001f9b20_212318(&X.v40));
    if (0.8726646304130554f <= ang || r == 8 || r == 12) {
        hero.unk240 = X.i18;
        *(s32 *)&X.v40.f[2] = 0;
        FUN_00125180_212318(&X.v40, &X.v40);
        t = -hero.motion.velocity.f[0] * X.v40.f[0] - hero.motion.velocity.f[1] * X.v40.f[1];
        if (0.0f < t) {
            FUN_001f9a68_212318(&X.v40, &X.v40, t);
            FUN_001f9a10_212318(&hero.motion.velocity, &hero.motion.velocity, &X.v40);
        }
    }
}
typedef unsigned int u128_002126b8 __attribute__((mode(TI), aligned(16)));
typedef struct {
    float x, y, z, w_002126b8;
} __attribute__((aligned(16))) Vec4_002126b8;
void FUN_001f9bf8_002126b8(Vec4_002126b8 *, void *, float) __asm__("FUN_001f9bf8");
void FUN_001f9a10_002126b8(void *, void *, void *) __asm__("FUN_001f9a10");
void FUN_L00_0025d238_002126b8(Vec4_002126b8 *, void *) __asm__("FUN_L00_0025d238");
void FUN_L00_002126b8(Vec4_002126b8 *a, Vec4_002126b8 *b, int mode, float fa, float fb) {
    Vec4_002126b8 t[2];
    if (mode) {
        char *up = (char *)&hero.unk290;
        char *base = up - 0x210;
        FUN_001f9bf8_002126b8(&t[0], up, -fb);
        FUN_001f9a10_002126b8(b, base, &t[0]);
        FUN_001f9bf8_002126b8(&t[0], up, -fa);
        FUN_001f9a10_002126b8(a, base, &t[0]);
        *(u128_002126b8 *)&t[1] = *(u128_002126b8 *)a;
        FUN_L00_0025d238_002126b8(&t[1], b);
    } else {
        qcopy(&t[0], &hero.motion.pos);
        qcopy(b, &t[0]);
        b->z += fb;
        if (b->z < 0.0f)
            b->z = 0.0f;
        qcopy(a, &t[0]);
        a->z += fa;
    }
}
typedef union {
    OvlQuad q;
    f32 f[4];
} V;
extern u8 D_L00_00173E40[] __attribute__((section(".data")));
extern u8 D_L00_00173E60[] __attribute__((section(".data")));
extern f32 D_L00_00173E68 __attribute__((section(".data")));

void FUN_001f99f8_c(void *) __asm__("FUN_001f99f8");
void FUN_L00_002126b8_c(void *, void *, s32, f32, f32) __asm__("FUN_L00_002126b8");
s32 FUN_001efa68(void *, void *, s32, void *, s32);
s32 FUN_L00_001f3608(void);
s32 FUN_001f0b58(void);
f32 resolve_camera_surface_height(void *, void *) __asm__("FUN_002135f0");
s32 FUN_L00_0025e3b8(s32);
u8 *FUN_002141f8(s32);
f32 FUN_001f9b48(void *, void *);
void FUN_00125180(void *, void *);
f32 FUN_L00_00233d30(void *);
f32 FUN_001f9e90_c(f32, f32) __asm__("FUN_001f9e90");
void FUN_001f9a28(void *, void *, void *);
f32 FUN_001f9ab0_c(void *, void *) __asm__("FUN_001f9ab0");
void FUN_001f9a68_c(void *, void *, f32) __asm__("FUN_001f9a68");
void FUN_001f9bf8_c(void *, void *, f32) __asm__("FUN_001f9bf8");
void FUN_L00_00216078(void *, void *);
void FUN_L00_002335c8(void *, f32, f32, f32);
f32 FUN_001f99c0(f32);

extern CollisionHit HH __asm__("D_L00_00173E40") __attribute__((section(".data")));
#define HI(o) (*(s32 *)(D_L00_00173E40 + (o)))
#define HF(o) (*(f32 *)(D_L00_00173E40 + (o)))

void FUN_L00_002127b8(void) {
    V v0, v10, v20, v30, v40, v50, v60;
    f32 f;
    s32 r;
    s32 i;
    f32 a;
    u8 *p;

    s32 k;
    f32 g;

    hero.unk270.f[2] = 1.0f;
    hero.air_frames.u++;
    hero.unk30C.u++;
    hero.unk270.i[0] = 0;
    hero.unk270.i[1] = 0;
    hero.unk2E0.i = 0;
    hero.ground_z.i = 0;
    FUN_001f99f8_c(&hero.ground_point);
    hero.unk30A = 0;
    hero.ground_distance = 32.0f;
    hero.ground_moby = 0;
    if (hero.unk2F8 != 0) {
        hero.unk2F8++;
    }
    k = 0;
    if (hero.unk20B3)
        k = 1;
    g = hero.unk234 * 2.2f;
    if (hero.state.control_mode == 2) {
        g = hero.unk234 * 2.9f;
    }
    FUN_L00_002126b8_c(&v10, &v0, k, g, -48.0f);
    if (FUN_001efa68(&v10, &v0, 2, hero.moby, 0) == 0) {
        goto tail;
    }
    r = FUN_L00_001f3608();
    if (r == -1) {
        r = 3;
    }
    hero.unk12ED = r;
    hero.unk12E0 = FUN_001f0b58();
    if (hero.unk12E0 == 0) {
        hero.height_threshold = resolve_camera_surface_height(D_L00_00173E60, &hero.unk280);
        if (hero.motion.pos.f[2] < hero.height_threshold && hero.unk2F8 <= 0) {
            hero.unk2F8 = 1;
        }
        if (FUN_001efa68(&v10, &v0, 0x24, hero.moby, 0) == 0) {
            goto d1;
        }
        r = FUN_L00_001f3608();
        if (current_level_index == 1 || current_level_index == 0x12) {
            r = 3;
        }
        hero.unk12ED = r;
    }
    if (hero.unk12E0 == 0xD) {
        hero.height_threshold = D_L00_00173E68;
        v10.f[2] = D_L00_00173E68 - 0.01f;
        if (FUN_001efa68(&v10, &v0, 4, hero.moby, 0) == 0) {
            goto d1;
        }
    }
    if (hero.unk12E0 == 3) {
        hero.unk2F4 = D_L00_00173E68;
        v10.f[2] = D_L00_00173E68 - 0.01f;
        if (FUN_001efa68(&v10, &v0, 4, hero.moby, 0) == 0) {
            goto d1;
        }
    }
    if (hero.unk12E0 == 0xB) {
        hero.unk2F4 = D_L00_00173E68;
        goto d1;
    }
    if (hero.unk12E0 == 1 && (u32)(hero.state.current - 0x7C) < 2) {
        goto d1;
    }
    if (HH.moby != 0) {
        if (FUN_L00_0025e3b8(HH.moby)) {
            hero.unk30A = 1;
        }
        p = FUN_002141f8(HH.moby);
        if (p != 0 && (*(u16 *)(p + 0x1E) & 8)) {
            hero.unk30A = 1;
        }
    }
    if (HH.unk1C > 0) {
        qcopy(&hero.ground_point, &HH.point);
        hero.ground_z.f = HH.point.f[2];
        hero.ground_distance = FUN_001f9b48(&hero.motion.pos, &hero.ground_point);
        hero.ground_moby = (struct Moby *)HH.moby;
        FUN_00125180(&hero.unk270, (u8 *)&HH.normal_x);
        hero.unk2E0.f = FUN_L00_00233d30((u8 *)&HH.normal_x);
        hero.unk2EC = FUN_001f9e90_c(HH.normal_x, HH.normal_y);
        FUN_001f9a28(&v20, &hero.ground_point, &hero.motion.pos);
        if (0.0f < FUN_001f9ab0_c(&v20, &hero.unk270)) {
            hero.ground_distance = -hero.ground_distance;
        }
        if (hero.ground_distance < 0.02f) {
            hero.unk30C.s = 0;
            if (hero.unk2E0.f <= 0.87266463f || hero.unk20B3 == 1 || hero.state.control_mode == 0x16) {
                hero.air_frames.s = 0;
                hero.unkA80 = HH.moby;
            }
        }
    }
tail:
    if (hero.air_frames.s != 0) {
        hero.unk300 = 0;
    } else {
        hero.unk300++;
        qcopy(&hero.unk2B0, &hero.ground_point);
    }
    if (hero.motion.pos.f[2] > hero.height_threshold) {
        hero.unk2F8 = 0;
    }
d1:
    FUN_001f99f8_c(&hero.unk290);
    switch (hero.unk20B3) {
    case 0:
        hero.unk290.f[2] = -1.0f;
        break;
    case 1:
        qcopy(&hero.unk290, &hero.unk270);
        FUN_001f9a68_c(&hero.unk290, &hero.unk290, -1.0f);
        break;
    case 2:
        FUN_001f9a28(&hero.unk290, &hero.motion.unkB0, &hero.motion.pos);
        FUN_001f9bf8_c(&hero.unk290, &hero.unk290, 1.0f);
        break;
    }
    hero.unk2E4.i = 0;
    hero.unk2E8.i = 0;
    hero.unk2D0.i[0] = 0;
    hero.unk2D0.i[1] = 0;
    hero.unk2C8.i[0] = 0;
    hero.unk2C8.i[1] = 0;
    hero.unk2C0.i[0] = 0;
    hero.unk2C0.i[1] = 0;
    if (hero.state.control_mode == 0xF || hero.state.control_mode == 0x15 || hero.state.control_mode == 6 || hero.state.control_mode == 4 ||
        hero.state.control_mode == 5 || hero.state.control_mode == 3) {
        return;
    }
    if (!(hero.ground_distance < 0.25f)) {
        return;
    }
    FUN_L00_00216078(&hero.unk270, &v20);
    if (-0.78539819f < v20.f[1] && v20.f[1] < 0.78539819f) {
        hero.unk2E4.f = v20.f[1];
    }
    if (-0.78539819f < v20.f[0] && v20.f[0] < 0.78539819f) {
        hero.unk2E8.f = v20.f[0];
    }
    for (i = 0; i < 2; i++) {
        a = 1.5707964f;
        if (i == 1) {
            a = -a;
        }
        FUN_L00_002335c8(&v30, 0.2f, a, 0.45f);
        FUN_L00_002335c8(&v40, 0.2f, a, -0.45f);
        if (FUN_001efa68(&v30, &v0, 0x22, hero.moby, 0)) {
            f = HH.point.f[2] - hero.ground_z.f;
            hero.unk2C0.f[i] = f;
            if (0.4f < FUN_001f99c0(f)) {
                hero.unk2C0.f[i] = 0.0f;
            }
            FUN_00125180(&v60, (u8 *)&HH.normal_x);
            FUN_L00_00216078(&v60, &v50);
            if (-0.78539819f < v50.f[1] && v50.f[1] < 0.78539819f) {
                hero.unk2C8.f[i] = v50.f[1];
            }
            if (-0.78539819f < v50.f[0] && v50.f[0] < 0.78539819f) {
                hero.unk2D0.f[i] = v50.f[0];
            }
        } else {
            hero.unk2C0.i[i] = 0;
            hero.unk2C8.f[i] = hero.unk2E4.f;
            hero.unk2D0.f[i] = hero.unk2E8.f;
        }
    }
}
/* Snaps the hero's follow position toward its target, stepping up by a bounded amount. */
/* Ported from rac1-decomp (src/overlays/shared/help_0020CDF0.c: func_L00_002136A8), where it is exact; names translated to the US level program. */

extern f32 D_0015ED6C_c __asm__("D_0015ED6C");
extern f32 dot_vectors_xyz(void *, void *) __asm__("func_001F9AB0");
extern f32 vector_length_xyz(void *) __asm__("FUN_001f9af0");
extern float D_0015ED60_c __asm__("D_0015ED60");
extern float FUN_001f9b80(void *, void *);
extern float FUN_L00_0025b8c0(float *p, float *v, float t, float u1, float u2, float eps);
extern void add_vector_xyz(void *, void *, void *) __asm__("FUN_001f9a10");
extern void normalize_vector_xyz(void *, void *, f32) __asm__("FUN_001f9bf8");
extern void subtract_vector_xyz(void *, void *, void *) __asm__("FUN_001f9a28");
float absolute_float(float input) __asm__("func_001F99C0");
extern float func_L00_0025C918_2136A8(float *p, float t, float *v, float u1, float u2, float eps) __asm__("FUN_L00_0025b8c0");

void FUN_L00_00212ff0(void) {
    struct Hero *globals = &hero;
    float v[4];
    if (globals->unk20B3 != 0) {
        float f2 = dot_vectors_xyz(&globals->motion.velocity, &globals->unk270);
        float f1;
        float len;
        if (globals->air_frames.s != 0) return;
        f1 = globals->ground_distance;
        if (!(f1 < 0.0f)) return;
        if (f1 < f2 + 0.0001f || globals->state.current == 0x3E) {
            qcopy(&globals->motion.pos, &globals->ground_point);
            return;
        }
        subtract_vector_xyz(v, &globals->ground_point, &globals->motion.pos);
        len = vector_length_xyz(v);
        if (len < D_0015ED60_c * 0.21f) {
            if (D_0015ED60_c * 0.05f < len) len = D_0015ED60_c * 0.05f;
        } else {
            len = len * 0.5f;
        }
        normalize_vector_xyz(v, v, len);
        add_vector_xyz(&hero.motion.pos, &hero.motion.pos, v);
    } else {
        if (globals->air_frames.s == 0 && globals->motion.pos.f[2] < globals->ground_z.f) {
            float x = absolute_float(globals->motion.pos.f[2] - globals->ground_z.f);
            float y = absolute_float(globals->motion.velocity.f[2]) + 0.01f;
            if (x < y) {
                if (globals->unk257 != 0) {
                    float d = FUN_001f9b80(&globals->unk210, &globals->motion.pos);
                    if (globals->unk234 * 0.5f < d) {
                        globals->motion.pos.f[2] = globals->ground_z.f;
                        return;
                    }
                } else {
                    globals->motion.pos.f[2] = globals->ground_z.f;
                    return;
                }
                func_L00_0025C918_2136A8((float *)(&globals->motion.pos.f[2]), globals->ground_z.f, (float *)(&globals->unk304), frame_scale_sq * 0.057f, frame_scale_sq * 0.3f, D_0015ED6C_c * 2.0f);
            } else {
                float f2 = globals->motion.unk100.f[2];
                char *q;
                if (f2 < 0.0f) {
                    float n = globals->motion.pos.f[2] - f2;
                    float lim = globals->ground_z.f;
                    globals->motion.pos.f[2] = n;
                    if (lim < n) globals->motion.pos.f[2] = lim;
                }
                q = D_0013E533 + 0xEA5;
                func_L00_0025C918_2136A8((float *)q, *(float *)(q + 0x250), (float *)(q + 0x27C), frame_scale_sq * 0.057f, frame_scale_sq * 0.3f, D_0015ED6C_c + D_0015ED6C_c);
            }
        } else {
            struct Hero *h = &hero;
            *(int *)&h->unk304 = 0;
        }
    }
}
#define NOT_SDA

#define MACRO_ADDR

/* Ported from rac1-decomp (src/overlays/shared/help_0020CDF0.c: func_L00_00213970), where it is exact; names translated to the US level program. */

extern char D_0013E533[];
extern float FUN_001f9af0(void *);
extern void clear_u64_value(void *) __asm__("FUN_001f99f8");
extern void FUN_001f9a68(void *, void *, float);
extern void FUN_001f9bf8(void *, void *, float);
void build_spherical_offset(f32 *out, f32 scale, f32 a, f32 b) __asm__("FUN_00214db0");

void FUN_L00_002132b8(float a, float b) {
    char *p = D_0013E533 + 0x173D;
    char *q = p - 0x920;
    float v;
    build_spherical_offset(p, *(float *)(q + 0x930), *(float *)(q + 0x938), *(float *)(q + 0x934));
    FUN_001f9a68(p, p, a);
    v = FUN_001f9af0(p);
    if (v <= b) {
        clear_u64_value(p);
    } else {
        FUN_001f9bf8(p, p, v - b);
    }
}
typedef unsigned int u128_213350 __attribute__((mode(TI), aligned(16)));
typedef struct {
    float x, y, z, w;
} __attribute__((aligned(16))) Vec4_213350;
float FUN_001f9dc8(float);
float FUN_001f9de0(float);
void FUN_001f9ab0(void *, Vec4_213350 *);
/* dot_vectors_xyz of v with (cos, sin, 0) of the angle hero.motion.rot.z. */
void FUN_L00_00213350(u128_213350 *v) {
    u128_213350 a[2];
    struct Hero *g = &hero;
    a[0] = *v;
    ((Vec4_213350 *)&a[1])->x = FUN_001f9dc8(g->motion.rot.f[2]);
    ((Vec4_213350 *)&a[1])->y = FUN_001f9de0(g->motion.rot.f[2]);
    ((Vec4_213350 *)&a[1])->z = 0.0f;
    FUN_001f9ab0(&a[0], (Vec4_213350 *)&a[1]);
}
typedef unsigned int u128_2133a8 __attribute__((mode(TI), aligned(16)));
#include "qcopy.h"
typedef union {
    u128_2133a8 q;
    f32 f[4];
} V_2133a8;
extern u128_2133a8 coll_2133a8[] __asm__("D_L00_00173E70") __attribute__((section(".data")));
extern void vzero_2133a8(void *) __asm__("FUN_001f99f8");
extern void f2347c0_2133a8(void) __asm__("FUN_L00_002347c0");
extern void f233810_2133a8(void *, void *, f32) __asm__("FUN_L00_00233810");
extern void f2334d0_2133a8(void *, void *, f32) __asm__("FUN_L00_002334d0");
extern void vadd_2133a8(void *, void *, void *) __asm__("FUN_001f9a10");
extern void vsub_2133a8(void *, void *, void *) __asm__("FUN_001f9a28");
extern f32 vlen_2133a8(void *) __asm__("FUN_001f9af0");
extern s32 coll1_2133a8(void *, s32, s32, f32) __asm__("FUN_L00_001f0d60");
extern s32 coll2_2133a8(void *, s32, f32, s32, f32) __asm__("FUN_L00_001f19a0");
extern s32 coll3_2133a8(void *, f32) __asm__("FUN_L00_001f3170");
extern void vscl_2133a8(void *, void *, f32) __asm__("FUN_001f9bf8");
s32 FUN_L00_002133a8(s32 mode) {
    V_2133a8 old;
    V_2133a8 v;
    V_2133a8 w;
    s32 mask;
    s32 i;
    u128_2133a8 *c;
    f32 h;
    if (hero.unk1CC != 0) {
        return 1;
    }
    qcopy(&old, &hero.motion.pos.q);
    vzero_2133a8(&v);
    if (hero.unk22DA != 0) {
        f2347c0_2133a8();
        hero.unk22DA = 0;
    }
    if (hero.state.control_mode != 0x11) {
        if (hero.unk20B3 != 0 || hero.unk1F8 != 0) {
            if (hero.unk20B3 == 1 || hero.unk1F8 != 0) {
                f233810_2133a8(&v, &v, 0.6f);
            } else {
                f2334d0_2133a8(&v, &v, -hero.unk224);
            }
        } else {
            v.f[2] = hero.unk224;
        }
    }
    vadd_2133a8(&hero.motion.pos.q, &hero.motion.pos.q, &v);
    mask = 0x24;
    if (hero.state.current == 0x7F) {
        mask = 0xD24;
    }
    for (i = 0; i < 8; i++) {
        if (hero.unk20B3 != 0) {
            if (!coll1_2133a8(&hero.motion.pos.q, mask, ((s32)hero.moby), frame_scale * 0.4f))
                break;
        } else if (hero.state.control_mode == 0x11) {
            if (!coll1_2133a8(&hero.motion.pos.q, mask, ((s32)hero.moby), 0.6f))
                break;
        } else if (hero.state.control_mode == 0xF) {
            if (!coll1_2133a8(&hero.motion.pos.q, mask, ((s32)hero.moby), frame_scale * 0.45f))
                break;
        } else {
            s32 a;
            h = hero.unk220 - hero.unk224;
            if (h < 0.05f) {
                h = 0.05f;
            }
            a = coll2_2133a8(&hero.motion.pos.q, mask, hero.unk234, ((s32)hero.moby), h);
            if (!(a | coll3_2133a8(&hero.motion.pos.q, hero.unk234)))
                break;
        }
        c = coll_2133a8;
        qcopy(&hero.motion.pos.q, c);
        qcopy(&hero.unk200.q, c + 1);
        qcopy(&hero.unk210.q, c - 1);
        hero.unk257 = 1;
        hero.coll_hit_moby = ((u8 **)c)[-6];
    }
    vsub_2133a8(&hero.motion.pos.q, &hero.motion.pos.q, &v);
    vsub_2133a8(&w, &hero.motion.pos.q, &old);
    h = vlen_2133a8(&w);
    if (hero.unk234 * 1.5f < h) {
        if (mode == 0xF) {
            if (512.0f < w.f[0])
                w.f[0] = 512.0f;
            else if (w.f[0] < -512.0f)
                w.f[0] = -512.0f;
            if (512.0f < w.f[1])
                w.f[1] = 512.0f;
            else if (w.f[1] < -512.0f)
                w.f[1] = -512.0f;
            if (512.0f < w.f[2])
                w.f[2] = 512.0f;
            else if (w.f[2] < -512.0f)
                w.f[2] = -512.0f;
            vscl_2133a8(&w, &w, hero.unk234);
            vadd_2133a8(&hero.motion.pos.q, &old, &w);
        }
        return -1;
    }
    return 1;
}
/* Ported from rac1-decomp (src/overlays/shared/help_0020CDF0.c: func_L00_00213E60), where it is exact; names translated to the US level program. */

typedef struct {
    int x, y, z, w;
} Quad;

extern int FUN_L00_002133a8_002137a8(int index) __asm__("FUN_L00_002133a8");

void FUN_L00_002137a8(void) {
    Quad *dst = (Quad *)&hero.motion.pos;
    Quad *table = (Quad *)hero.unk1B00;
    int i;

    for (i = 0; i < 16; i++) {
        struct Hero *base;

        if (FUN_L00_002133a8_002137a8(i) == 1)
            return;

        base = &hero;
        if (base->unk21B4 >= 2) {
            base->unk21B4--;
            base->unk21B0 = (base->unk21B0 + 31) % 32;
        }
        qcopy(dst, &table[base->unk21B0]);
    }
}
#include "rnc/gameplay/state/usage_stats.h"
#include "eetypes.h"
#include "qcopy.h"
/*
 * Hero movement step (FUN_L01_00233de0 twin; control mode 0xF caps the horizontal speed, 0xD and 0xE skip the cap): clamps the velocity, moves the hero by it (plus the
 * one-frame impulse at unk920 and the push at unkF0), runs collision, then
 * derives this frame's movement vectors and speeds:
 *   motion.unk100  position change this frame
 *   motion.unk110  movement direction scaled by the velocity along it
 *   motion.unk120  same, without the gravity-up component
 *   motion.unk130  same, gravity-up part only
 *   motion.unk140  displacement caused by the push
 *   motion.speed_xy  speed, unk164 horizontal speed, unk168 forward speed
 *   motion.unk16C  slope: vertical / horizontal change, clamped to +-0.5
 */


/* The FUN_L00_00233xxx helpers work in the hero's gravity frame (hero byte
   0x20B3: 0 = world z up, otherwise the frame of the hero's moby). */
extern void FUN_L00_00233f80(s32, void *, void *);
extern f32 gravity_length_xy(void *) __asm__("FUN_L00_002339d0");
extern f32 gravity_z(void *) __asm__("FUN_L00_00233a78");
extern void gravity_set_z(void *, void *, f32) __asm__("FUN_L00_00233b20");
extern void gravity_flatten(void *, void *) __asm__("FUN_L00_002338d0");
extern void FUN_L00_00233ba0(float *, float *, float);
extern f32 forward_component(void *) __asm__("FUN_L00_00213350");  /* dot with (cos, sin) of the hero yaw */

extern void normalize_vector_xyz(void *, void *, f32) __asm__("FUN_001f9bf8");
extern f32 vector_length_xyz(void *) __asm__("FUN_001f9af0");
extern f32 dot_vectors_xyz(void *, void *) __asm__("FUN_001f9ab0");
extern f32 vector_length_xy(void *) __asm__("FUN_001f9b20");
extern void add_vector_xyz(void *, void *, void *) __asm__("FUN_001f9a10");
extern void subtract_vector_xyz(void *, void *, void *) __asm__("FUN_001f9a28");
extern void scale_vector_xyz(void *, void *, f32) __asm__("FUN_001f9a68");
extern void clear_vector(void *) __asm__("FUN_001f99f8");
extern void normalize_vector_xy(void *, void *, f32) __asm__("FUN_001f9c48");

extern void FUN_L00_002137a8(void);
extern void FUN_L00_002127b8(void);
extern void FUN_L00_00212ff0(void);

void FUN_L00_00213880(void)
{
    Vec4 old_pos;
    Vec4 tmp;
    Vec4 tmp2;
    f32 limit;
    f32 d;
    f32 w;

    qcopy(&old_pos, &hero.motion.pos);
    FUN_L00_00233f80(hero.unk4F8, &hero.motion.unkF0, &hero.motion.rot);

    /* cap the speed; states 0x22 and 0x14 cap the horizontal part and the fall speed */
    if (hero.state.current == 0x22 || hero.state.current == 0x14) {
        if (hero.unk1CC == 0) {
            d = gravity_length_xy(&hero.motion.velocity);
            limit = hero.unk234 - 0.02f;
            if (limit < d) {
                normalize_vector_xyz(&hero.motion.velocity, &hero.motion.velocity, limit);
            }
        }
        d = gravity_z(&hero.motion.velocity);
        limit = -hero.ground_distance;
        if (d < limit) {
            if (0.0f < limit) {
                limit = 0.0f;
            }
            gravity_set_z(&hero.motion.velocity, &hero.motion.velocity, limit);
        }
    } else if (hero.state.control_mode == 0xF) {
        if (hero.unk1CC == 0) {
            d = vector_length_xy(&hero.motion.velocity);
            limit = hero.unk234 - 0.02f;
            if (limit < d) {
                normalize_vector_xy(&hero.motion.velocity, &hero.motion.velocity, limit);
            }
        }
    } else if (hero.state.control_mode != 0xD) {
        if (hero.state.control_mode != 0xE && hero.unk1CC == 0) {
            d = vector_length_xyz(&hero.motion.velocity);
            limit = hero.unk234 - 0.02f;
            if (limit < d) {
                normalize_vector_xyz(&hero.motion.velocity, &hero.motion.velocity, limit);
            }
        }
    }

    add_vector_xyz(&hero.motion.pos, &hero.motion.pos, &hero.motion.velocity);
    add_vector_xyz(&hero.motion.pos, &hero.motion.pos, &hero.move_impulse);
    clear_vector(&hero.move_impulse);
    hero.unk257 = 0;
    hero.coll_hit_moby = 0;

    if (vector_length_xyz(&hero.motion.unkF0) <= 0.0001f) {
        FUN_L00_002137a8();
        FUN_L00_002127b8();
        subtract_vector_xyz(&hero.motion.unk100, &hero.motion.pos, &old_pos);
        FUN_L00_00212ff0();
    } else {
        FUN_L00_002127b8();
    }

    /* movement direction, scaled by the velocity along it (never negative) */
    subtract_vector_xyz(&hero.motion.unk110, &hero.motion.pos, &old_pos);
    qcopy(&hero.motion.unk130, &hero.motion.unk110);
    qcopy(&hero.motion.unk120, &hero.motion.unk110);
    normalize_vector_xyz(&hero.motion.unk110, &hero.motion.unk110, 1.0f);
    d = dot_vectors_xyz(&hero.motion.unk110, &hero.motion.velocity);
    if (d < 0.0f) {
        d = 0.0f;
    }
    normalize_vector_xyz(&hero.motion.unk110, &hero.motion.velocity, d);

    qcopy(&tmp, &hero.motion.velocity);
    gravity_flatten(&tmp, &tmp);
    gravity_flatten(&hero.motion.unk130, &hero.motion.unk130);
    normalize_vector_xyz(&hero.motion.unk130, &hero.motion.unk130, 1.0f);
    d = dot_vectors_xyz(&hero.motion.unk130, &tmp);
    if (d < 0.0f) {
        d = 0.0f;
    }
    normalize_vector_xyz(&hero.motion.unk130, &tmp, d);

    qcopy(&tmp2, &hero.motion.velocity);
    FUN_L00_00233ba0((float *)&tmp2, (float *)&tmp2, 0.0f);
    FUN_L00_00233ba0((float *)&hero.motion.unk120, (float *)&hero.motion.unk120, 0.0f);
    normalize_vector_xyz(&hero.motion.unk120, &hero.motion.unk120, 1.0f);
    d = dot_vectors_xyz(&hero.motion.unk120, &tmp2);
    if (d < 0.0f) {
        d = 0.0f;
    }
    normalize_vector_xyz(&hero.motion.unk120, &tmp2, d);

    hero.motion.speed_xy = vector_length_xyz(&hero.motion.unk110);
    hero.motion.unk164 = vector_length_xy(&hero.motion.unk110);
    /* read through the address, as retail reloads the base register here */
    tmp.q = (&hero.motion.unk110)->q;
    hero.motion.unk168 = forward_component(&tmp);
    if (hero.motion.unk168 < 0.0f) {
        hero.motion.unk168 = 0.0f;
    }

    /* apply the push, keeping its w */
    qcopy(&tmp, &hero.motion.pos);
    if (vector_length_xyz(&hero.motion.unkF0) > 0.0001f) {
        add_vector_xyz(&hero.motion.pos, &hero.motion.pos, &hero.motion.unkF0);
        w = hero.motion.unkF0.f[3];
        clear_vector(&hero.motion.unkF0);
        hero.motion.unkF0.f[3] = w;
        FUN_L00_002137a8();
        FUN_L00_002127b8();
        subtract_vector_xyz(&hero.motion.unk100, &hero.motion.pos, &old_pos);
        FUN_L00_00212ff0();
    }
    subtract_vector_xyz(&hero.motion.unk140, &hero.motion.pos, &tmp);
    {
        /* push w moves to unk140.w; a block-local keeps retail's order */
        f32 push_w = hero.motion.unkF0.f[3];

        hero.motion.unkF0.f[3] = 0.0f;
        hero.motion.unk140.f[3] = push_w;
    }

    subtract_vector_xyz(&hero.motion.unk100, &hero.motion.pos, &old_pos);
    hero.motion.unk16C = 0.0f;
    if (hero.motion.unk164 > 0.004f) {
        hero.motion.unk16C = hero.motion.unk100.f[2] / hero.motion.unk164;
        if (hero.motion.unk16C > 0.5f) {
            hero.motion.unk16C = 0.5f;
        } else if (hero.motion.unk16C < -0.5f) {
            hero.motion.unk16C = -0.5f;
        }
    }

    /* cap the step at 52 units per frame-rate unit */
    if (hero.motion.speed_xy > frame_time * 52.0f) {
        scale_vector_xyz(&hero.motion.unk100, &hero.motion.unk100, frame_time * 52.0f / hero.motion.speed_xy);
        hero.motion.speed_xy = frame_time * 52.0f;
    }
}
/* Ported from rac1-decomp (src/overlays/shared/help_0020CDF0.c: func_L00_002144A0), where it is exact; names translated to the US level program. */

/* Scales four vectors and one float of the hero by s. */
void FUN_L00_00213de8(float s) {
    char *p = D_0013E533 + 0xF1D;
    float *f;

    FUN_001f9a68(p, p, s);
    FUN_001f9a68(p + 0x10, p + 0x10, s);
    FUN_001f9a68(p - 0x20, p - 0x20, s);
    FUN_001f9a68(p + 0x50, p + 0x50, s);
    f = (float *)(p - 0x100);
    f[0x194 / 4] = f[0x194 / 4] * s;
}
INCLUDE_ASM("config/us/overlays/asm/FUN_L00_00213e68.s", FUN_L00_00213e68);
INCLUDE_ASM("config/us/overlays/asm/FUN_L00_00214108.s", FUN_L00_00214108);
