/* Level overlay code after ui/help; generated by `decomp overlays stubs`, stubs replaced by C as functions are matched. */
#include "types.h"
#include "rnc/gameplay/hero.h"
#include "asm.h"

#define NOT_SDA

#define MACRO_ADDR

/* Steps two floats of arg toward a target and clamps them to [-1, 1]. */
/* Ported from rac1-decomp (src/overlays/shared/help_00237B00.c: func_L05_00237B00), where it is exact; names translated to the US level program. */

extern f32 approach_value(f32 *, f32, f32) __asm__("FUN_00213ed8");
extern unsigned char D_0013E533[];

void FUN_L05_00237488(float *out, float *p, float step) {
    char *g = (char *)D_0013E533 + 0xE1D;
    float v[2];
    v[0] = -*(float *)(g + 0x1D20);
    v[1] = *(float *)(g + 0x1D24);
    approach_value(p + 2, v[0], step);
    if (p[2] > 1.0f)
        p[2] = 1.0f;
    if (p[2] < -1.0f)
        p[2] = -1.0f;
    out[0] = p[2];
    approach_value(p + 1, v[1], step);
    if (p[1] > 1.0f)
        p[1] = 1.0f;
    if (p[1] < -1.0f)
        p[1] = -1.0f;
    out[1] = p[1];
}

#include "sda.h"
int FUN_L05_0023b378(int id, float *out) {
    *out = 0.0f;
    if (hero.state.control_mode == 0x16 && hero.unk8CE
        && (unsigned)(*(unsigned char *)(((char *)hero.moby) + 0x53) - 0x69) < 4)
        return 1;
    switch (id) {
    case 0x37:
        *out = -0.95993108f; /* -55 degrees */
        return 1;
    case 0x1C: case 0x1D: case 0x1F:
        if (25.0f < hero.unkAA8) *out = -1.30899692f; /* -75 degrees */
        return 1;
    case 0x31: case 0x32: case 0x4A: case 0x4B: case 0x50: case 0x60: case 0x6D: case 0x6E:
        return 1;
    }
    return 0;
}

/* Applies the wrench/item selection for slot i: resolves pending, queued and requested items and refreshes the slot when it changes. */
/* Ported from rac1-decomp (src/overlays/shared/help_0020CDF0.c: func_L00_00210558), where it is exact; names translated to the US level program. */

/* L05 adds to FUN_L00_0020fea0 the state.control_mode / unk8CE test that guards the second
   unk20A6 set, and a new unguarded statement (the prologue's i!=0 branch lands
   on it, so it runs for every slot) that sets unk20A6 for items[0].item_id == 0x24 with
   state.control_mode != 0x16. The second condition is negated: retail's `beq` skips the
   store when state.control_mode == 0x16, which is what makes this spelling the only one
   that lands `beq` there. */


typedef struct {
    char pad[0x20];
    int f20;
    char pad2[0x28];
} ItemDef;

extern char D_0013C940[];
extern char D_00141660[];
extern unsigned char D_0013D4C0[];
extern int D_0015ED8C;
extern int D_0015ED90;
extern int D_0015ED94;
extern ItemDef D_L05_00179F20[];
extern int FUN_001f96f8(int);
extern int FUN_001f9770(void *);
extern int FUN_L00_0020d568();
extern int FUN_L00_00216de8(int, int);
extern int FUN_L00_00257b90(int, int);
extern void FUN_L00_0020a500(void);
extern void FUN_L00_0020e698(void);
extern void FUN_L00_002cdcc0(void);
s32 FUN_L00_0020fe30(void);
void FUN_L00_0020fd80(int id);
void FUN_L00_0020fde0(int id);
void blend_moby_animation(void *arg0, int arg1, int arg2, int arg3) __asm__("FUN_00212f90");

void FUN_L05_0023dc88(int i) {
    int changed;
    int flag6;
    int flag4;
    unsigned char st;

    if (i == 0) {
        int v;
        struct Hero *g = &hero;
        v = g->items[0].item_id;
        if (v != 8 && v != 0x17 && v != 9 && g->items[0].unk1C == 2) {
            g->items[0].unk1C = 0;
        }
    }
    if (i == 0) {
        struct Hero *g = &hero;
        if (g->unk20A7 != 0 && *(int *)((char *)g + 0x10B8) != 8) {
            if (g->state.control_mode != 0x16 || g->unk8CE == 0) {
                g->unk20A6 = 1;
            }
        }
    }
    {
        struct Hero *g = &hero;
        if (g->items[0].item_id == 0x24 && g->state.control_mode != 0x16) {
            g->unk20A6 = 1;
        }
    }
    if (i == 0) {
        struct Hero *g = &hero;
        if (g->unk20A7 != 0 && *(int *)((char *)g + 0x10B8) == 8) {
            if (g->pending_item[0] == 0x1F) {
                g->pending_item[0] = 0;
            }
            if (g->pending_item[0] != 0x18 && g->pending_item[0] != 0x24) {
                return;
            }
        }
    }
    {
        struct Hero *g = &hero;
        if (g->unk20AC != 0 && i == 0) {
            if (g->unk20A6 == 0 || *(int *)((char *)g + 0x10B8) == 8) {
                g->unk20A6 = 0;
                return;
            }
        }
    }
    changed = 0;
    {
        char *pad = D_0013C940;
        if ((*(int *)(pad + 0x1A4) & 0x80) || (&hero)->unk20A6 != 0) {
            if (i == 0) {
                int v;
                struct Hero *g = &hero;
                v = *(int *)((char *)g + 0x10B8);
                if (v != 8) {
                    if (g->unk20A6 != 0 && v != 0 && v != 0x1F) {
                        g->saved_item[0] = v;
                    }
                    (&hero)->selected_item[i] = 8;
                    changed = 1;
                }
            }
        }
    }
    if (i == 0) {
        char *pad = D_0013C940;
        if (*(int *)(pad + 0x1A4) & 0x20) {
            struct Hero *g = &hero;
            if (g->unk20A7 == 0) {
                if (g->items[0].item_id != *(int *)(D_00141660) && *(int *)(D_00141660) != 0) {
                    g->selected_item[0] = *(int *)(D_00141660);
                    changed = 1;
                }
            }
        }
    }
    if (i == 1) {
        struct Hero *g;
        if (FUN_L00_0020d568() || (&hero)->state.current == 0x12) {
            int v;
            g = &hero;
            v = *(int *)((char *)g + 0x1108);
            if (v != 0) {
                g->saved_item[1] = v;
                g->pending_item[1] = 0x26;
            }
        }
        g = &hero;
        if (g->state.control_mode == 0xF && D_0013D4C0[0x1D] != 0) {
            if (*(int *)(D_00141660 + 4) != 0x1D || *(int *)((char *)g + i * 0x50 + 0x10B8) == 0) {
                int v;
                g->pending_item[1] = 0x1D;
                v = *(int *)((char *)g + i * 0x50 + 0x10B8);
                if (v != 0) {
                    g->saved_item[i] = v;
                } else {
                    g->saved_item[i] = 0x26;
                }
            }
        }
        g = &hero;
        if (*(unsigned char *)((char *)g + 0x12E7) != 0 && D_0013D4C0[0x1C] != 0) {
            if (*(int *)(D_00141660 + 4) != 0x1C || *(int *)((char *)g + i * 0x50 + 0x10B8) == 0) {
                int v;
                g->pending_item[1] = 0x1C;
                v = *(int *)((char *)g + i * 0x50 + 0x10B8);
                if (v != 0) {
                    g->saved_item[i] = v;
                } else {
                    g->saved_item[i] = 0x26;
                }
            }
        }
    }
    flag6 = 0;
    if (i == 2) {
        struct Hero *g = &hero;
        struct Hero *h;
        struct Hero *h2;
        if (g->state.control_mode == 0x11 || g->state.current == 0x76 || g->state.current == 0x6A || g->state.current == 0x82 ||
            *(unsigned char *)((char *)g + 0x22CB) != 0) {
            if (((int *)(D_00141660))[i] != 6 ||
                (h2 = &hero, *(int *)((char *)h2 + i * 0x50 + 0x10B8) == 0)) {
                h = &hero;
                if (*(int *)((char *)h + i * 0x50 + 0x10B8) != 6 && h->selected_item[i] != 6 &&
                    D_0013D4C0[6] != 0) {
                    int v;
                    h->pending_item[i] = 6;
                    flag6 = 1;
                    v = *(int *)((char *)h + i * 0x50 + 0x10B8);
                    if (v != 0) {
                        h->saved_item[i] = v;
                    } else {
                        h->saved_item[i] = 0x26;
                    }
                }
            }
        } else if (*(int *)((char *)g + 0x1158) == 6 && g->saved_item[2] != 0) {
            g->restore_item[2] = 1;
        }
    }
    flag4 = 0;
    if (i == 3) {
        struct Hero *g;
        if (FUN_L00_0020d568() || (&hero)->state.current == 0x12) {
            if (*(int *)(D_00141660 + 0xC) != 4) {
                int v;
                g = &hero;
                v = *(int *)((char *)g + 0x11A8);
                if (v != 4 && D_0013D4C0[4] != 0) {
                    g->saved_item[3] = v;
                    flag4 = 1;
                    g->pending_item[3] = 4;
                }
            }
        } else if ((&hero)->items[3].item_id == 4 && (&hero)->saved_item[3] != 0) {
            (&hero)->restore_item[3] = 1;
        }
        if ((&hero)->state.current == 8 && ((int *)(D_00141660))[i] == 4) {
            (&hero)->pending_item[i] = 2;
        }
    }
    {
        struct Hero *g = &hero;
        int *qb = g->restore_item;
        int *q = qb + i;
        if (*q != 0) {
            int *r;
            int *rb;
            int w;
            *q = 0;
            rb = g->saved_item;
            r = rb + i;
            w = *r;
            if (w != 0 && w != *(int *)((char *)g + i * 0x50 + 0x10B8)) {
                if (w == 0x26) {
                    w = 0;
                }
                *r = 0;
                ((int *)(D_00141660))[i] = w;
                g->selected_item[i] = w;
                if (i == 0) {
                    D_L05_00179F20[g->selected_item[0]].f20 = 0x20;
                }
                changed = 1;
            }
        }
    }
    {
        struct Hero *g = &hero;
        int *s;
        int *sb;
        if (*(unsigned char *)((char *)g + 0x1FF5) != 0) {
            FUN_L00_002cdcc0();
            g->pending_item[i] = 0;
        }
        sb = g->pending_item;
        s = sb + i;
        if (*s == 0x1F) {
            if (FUN_L00_0020fe30()) {
                int v;
                if (*(short *)((char *)g + 0x22DE) == 0) {
                    FUN_L00_00216de8(0x18, 0);
                    *(short *)((char *)g + 0x22DE) = 0x12;
                    *(short *)((char *)g + 0x22DC) = 1;
                }
                changed = 1;
                g->selected_item[i] = *s;
                v = ((int *)(D_00141660))[i];
                ((int *)(D_00141660))[i] = *s;
                D_0015ED8C = v;
            }
            (&hero)->pending_item[i] = 0;
        }
    }
    {
        int v;
        struct Hero *g = &hero;
        int *ab = g->pending_item;
        int *a = ab + i;
        v = *a;
        if (v != 0) {
            int *bb = g->selected_item;
            int *b = bb + i;
            if (v != *b) {
                if (v == 0x26) {
                    *b = 0;
                    ((int *)(D_00141660))[i] = 0;
                } else {
                    struct Hero *h;
                    int u;
                    if (i == 0 && g->pending_item[0] != 0x24 && *(int *)((char *)g + 0x10B8) != 8) {
                        D_0015ED8C = *(int *)(D_00141660);
                    }
                    h = &hero;
                    u = h->pending_item[i];
                    h->selected_item[i] = u;
                    if (u != 0x24 && (flag6 == 0 || u != 6) && (flag4 == 0 || u != 4)) {
                        ((int *)(D_00141660))[i] = u;
                    }
                    if (i == 0) {
                        struct Hero *k = &hero;
                        D_L05_00179F20[k->selected_item[0]].f20 = 0x20;
                    }
                }
                changed = 1;
            } else {
                *a = 0;
            }
        }
    }
    {
        struct Hero *s = (struct Hero *)(((char *)&hero) + i * sizeof(struct HeroItemSlot));
        st = s->items[0].unk1C;
        if (st == 2) {
            changed = 0;
        }
        if (st == 1 && s->items[0].timer == 0) {
            s->items[0].timer = s->items[0].timer_reload;
        }
    }
    if (FUN_001f9770(&hero.items[i].timer) == 0) {
        changed = 0;
    }
    if (changed) {
        struct Hero *g = &hero;
        *(int *)((char *)g + i * 0x50 + 0x10B0) = 3;
        FUN_L00_0020a500();
        *(int *)((char *)g + 0x1010) = FUN_L00_00257b90(FUN_001f96f8(0x32), FUN_001f96f8(0x5A));
        FUN_L00_0020fde0(*(hero.selected_item + i));
        FUN_L00_0020fd80(*(hero.selected_item + i));
        if (g->unk20A8 != 0) {
            FUN_L00_0020e698();
        }
        if (i == 0) {
            if (*hero.selected_item == 8) {
                D_0015ED90 = 1;
            } else {
                D_0015ED90 = 0;
            }
        }
        if (i == 3) {
            if ((&hero)->items[3].item_id == 3) {
                D_0015ED94 = 1;
            } else {
                D_0015ED94 = 0;
            }
        }
        {
            struct Hero *k = &hero;
            struct Hero *s = (struct Hero *)((char *)k + i * sizeof(struct HeroItemSlot));
            s->items[0].unk1A = 0;
            k->pending_item[i] = 0;
            k->unk20A6 = 0;
            if (*(char **)((char *)k + 0xD00) != 0) {
                *(int *)(*(char **)((char *)k + 0xD00) + 0x34) = 1;
            }
            if (*(char **)((char *)k + 0xD04) != 0) {
                *(int *)(*(char **)((char *)k + 0xD04) + 0x34) = 1;
            }
            if (s->items[0].moby != 0) {
                blend_moby_animation(s->items[0].moby, 2, 0, 2);
            }
            if (s->items[0].moby2 != 0 && i != 3) {
                blend_moby_animation(s->items[0].moby2, 2, 0, 2);
            }
        }
        {
            struct Hero *e = (struct Hero *)(((char *)&hero) + i * sizeof(struct HeroItemSlot));
            e->items[0].state = 3;
        }
    }
}
INCLUDE_ASM("config/us/overlays/asm/FUN_L05_0024bdc0.s", FUN_L05_0024bdc0);
/* Adapted from the exact FUN_L00_002279b0 (src/overlays/shared/ui/help/00221310.c): L05 has a wider head guard and its own level data. */

extern float D_L05_00174268 __attribute__((section(".data")));
extern int D_L05_0015F5CC;
extern int FUN_001f0b58(void);
extern int FUN_L00_00216de8_c(int a, int b) __asm__("FUN_L00_00216de8");
extern int func_L00_001EFFF0(void *, void *, int, int, int) __asm__("FUN_001efa68");
extern void FUN_L00_002126b8(void *, void *, int, float, float);
extern int hero_set_state(int, int) __asm__("FUN_L05_0024cee8");
float absolute_float(float input) __asm__("FUN_001f99c0");


int FUN_L05_002515d0(void) {
    struct Hero *p = &hero;
    struct Hero *q;
    struct Hero *u;
    int r;
    float v1[4];
    float v2[4];
    float t;
    float scale;
    if ((unsigned)(p->state.control_mode - 0x15) < 2) {
        return 0;
    }
    if (p->state.current == 0x6F || p->state.current == 0x6D || p->state.current == 0x6E || p->state.current == 0x6A) {
        return 0;
    }
    r = 0;
    if (p->base_condition != 0) {
        if (p->state.control_mode == 0x11) {
            if (p->state.step != 1) {
                if (0.0f < p->motion.unk100.f[2]) {
                    if (p->height_threshold - 0.4f < p->motion.pos.f[2]) {
                        r = 1;
                    }
                }
            }
        } else if (p->state.control_mode != 0x12 && p->state.control_mode != 3) {
            t = 0.2f;
            if (t < absolute_float(p->motion.velocity.f[2]) + 0.07f) {
                t = absolute_float(p->motion.velocity.f[2]) + 0.07f;
            }
            if (absolute_float(p->height_threshold - (p->motion.pos.f[2] + 0.45f)) < t) {
                if (p->state.control_mode != 4 || p->unk41E != 0) {
                    if (0.8f < p->unk22A4 && p->motion.unk100.f[2] < 0.0f) {
                        r = 1;
                    }
                }
            }
            q = &hero;
            if (q->motion.pos.f[2] < q->height_threshold - 0.8f) {
                if (q->state.control_mode != 4 || q->unk41E != 0) {
                    r = 1;
                }
            }
        }
    }
    p = &hero;
    t = 0.27f;
    if (t < absolute_float(p->motion.velocity.f[2]) + 0.07f) {
        t = absolute_float(p->motion.velocity.f[2]);
    }
    if (p->state.current == 0x12) {
        if (p->unk41E != 0) {
            if (p->motion.pos.f[2] < p->height_threshold - 0.7f) {
                r = 1;
            }
        }
    }
    u = &hero;
    if (u->state.control_mode - 0x11 >= 2u && u->state.control_mode != 7 &&
        u->state.control_mode != 0x14 && u->state.current != 0x12 &&
        (D_L05_0015F5CC & 0xF) == 0) {
        scale = 4.0f;
        if ((D_L05_0015F5CC & 0x3F) == 0) {
            scale = 16.0f;
        }
        FUN_L00_002126b8(v1, v2, 0, scale, 1.3f);
        if (func_L00_001EFFF0(v1, v2, 2, *(int *)&u->moby, 0) != 0) {
            int s = FUN_001f0b58();
            u->unk12E0 = s;
            if ((short)s == 0) {
                v1[2] = D_L05_00174268 - 0.01f;
                if (func_L00_001EFFF0(v1, v2, 2, *(int *)&u->moby, 0) == 0) {
                    hero_set_state(0x34, 1);
                    return 1;
                }
            }
        }
    }
    if (r != 0) {
        hero_set_state(0x37, 1);
        FUN_L00_00216de8_c(3, 0);
    }
    return r;
}
INCLUDE_ASM("config/us/overlays/asm/FUN_L05_00251be8.s", FUN_L05_00251be8);
/* Hero idle: picks the idle animation from the stick direction, and occasionally plays a fidget or the
 * look-around when standing still. */
/* Ported from rac1-decomp (src/overlays/shared/help_00237B00.c: func_L05_00254030), where it is exact; names translated to the US level program. */

typedef struct {
    int bank;
    int seq;
} SndPair_254030;


extern SndPair_254030 D_L05_00179BC0[];
extern char D_0013CAE0[];
extern float FUN_L00_00232b90(float a, float b, float c);
extern int FUN_L05_002551b8_c(void) __asm__("FUN_L05_002551b8");
extern s32 scale_game_frames(s32) __asm__("func_001F96F8");
extern s32 truncate_float_to_s32(f32) __asm__("func_001FA6D0");
extern void FUN_L00_002323b8(int, int, float);
extern void FUN_L00_002325e0(int bank, int seq);

void FUN_L05_00253850(void) {
    struct Hero *g = &hero;
    int pad;
    g->unk888 =
        truncate_float_to_s32(FUN_L00_00232b90(60.0f, g->unk860, -1.0f));
    if (g->unk88D != 0 && ((pad = *(int *)(D_0013CAE0)) & 0xF) != 0) {
        g->unk88F = 0;
        if (pad & 8)
            g->unk88F = 1;
        else if (pad & 1)
            g->unk88F = 2;
        else if (pad & 2)
            g->unk88F = 3;
        {
            struct Hero *h = &hero;
            int a = h->unk88F + 0x69;
            if (((unsigned char *)*(char **)&h->moby)[0x53] != a) {
                FUN_L00_002323b8(a, 2, (float)scale_game_frames(5));
                FUN_L00_002325e0(D_L05_00179BC0[h->unk88F].bank,
                                 D_L05_00179BC0[h->unk88F].seq);
            } else if ((float)h->unkAB0 - 2.0f < h->unkAA8) {
                h->unk6E0[h->unk88F] = 1;
                h->unk6F8 += 1;
            }
        }
    }
    {
        struct Hero *k = &hero;
        if ((k->air_frames.s == 0 || (*(int *)(D_0013CAE0) & 0xF) == 0) &&
            (unsigned int)(((unsigned char *)((char *)k->moby))[0x53] - 0x69) < 4 &&
            k->unkA9C == 0 &&
            k->unkAB0 < ((unsigned char *)((char *)k->moby))[0x51] &&
            ((unsigned char *)((char *)k->moby))[0x51] < k->unkAB4) {
            int t = k->unk888;
            if (t > scale_game_frames(0x1E)) {
                int x = FUN_L05_002551b8_c();
                FUN_L00_002323b8(x, 9, (float)scale_game_frames(0x11));
            } else {
                t = k->unk888;
                if (t < scale_game_frames(0xA))
                    t = scale_game_frames(0xA);
                FUN_L00_002323b8(FUN_L05_002551b8_c(), 0xD, (float)t);
            }
        }
    }
    {
        struct Hero *h = &hero;
        if (h->unk8BC != 0) {
            int a = ((unsigned char *)((char *)h->moby))[0x53];
            if (a == 0x52 || a == 0x7D || a == 0x68 || a == 0x7E) {
                int x = FUN_L05_002551b8_c();
                FUN_L00_002323b8(x, 0xB, (float)scale_game_frames(0xA));
            }
        }
    }
    {
        struct Hero *h = &hero;
        if ((h->unkA98 & 2) && h->unk30C.s != 0) {
            int x = FUN_L05_002551b8_c();
            FUN_L00_002323b8(x, 9, (float)scale_game_frames(7));
        }
    }
}
INCLUDE_ASM("config/us/overlays/asm/FUN_L05_00253b48.s", FUN_L05_00253b48);
#ifndef NON_MATCHING
INCLUDE_ASM("config/us/overlays/asm/FUN_L05_00254058.s", FUN_L05_00254058);
#else
#include "rnc/gameplay/state/usage_stats.h"
extern u8 D_0013D388;
extern struct UsageStats D_00141848;
extern s32 D_0015EEA4;
extern s32 D_0015ED84 __attribute__((sda));
extern s32 D_0015EEA4_sda __asm__("D_0015EEA4") __attribute__((sda));
extern f32 D_L05_002169F8[] __asm__("D_L05_002169F8");
extern f32 FUN_001f96b0(f32) __asm__("FUN_L05_0022dbc8");

void FUN_L05_00254058(void) {
    int i;
    int total;
    int step;
    struct { f32 values[5]; } table;
    f32 frames;

    if (D_0013D388 == 0) return;
    if (*(s32 *)((char *)&hero + 0x8A8) != 0) {
        s32 duration = D_0015EEA4_sda;
        if (D_00141848.stat[30].count <= 0xFFFE) {
            D_00141848.stat[30].count++;
            duration = *(s32 *)0x0015EEA4;
        }
        if (D_00141848.stat[30].unk2 < scale_game_frames(duration) / 600)
            D_00141848.stat[30].unk2 = scale_game_frames(D_0015EEA4_sda) / 600;
        D_00141848.stat[30].level_mask |= (1 << D_0015ED84) | 0x80000000;
    }
    {
        s32 *counter = (s32 *)((char *)&hero + 0x700);
        for (i = 2; i >= 0; i--, counter++) {
            if (absolute_float(*(f32 *)(counter - 12)) > 3.3161256f) {
                f32 rotation = *(f32 *)(counter - 12);
                s32 count = *counter;
                if (0.0f < rotation) rotation -= 6.2831855f;
                else rotation += 6.2831855f;
                *(f32 *)(counter - 12) = rotation;
                *counter = count + 1;
            }
        }
    }
    *(s32 *)((char *)&hero + 0x70C) = 0;
    for (i = 0; i < 3; i++) {
        if (*(s32 *)((char *)&hero + 0x70C) < *(s32 *)((char *)&hero + 0x700 + i * 4))
            *(s32 *)((char *)&hero + 0x70C) = *(s32 *)((char *)&hero + 0x700 + i * 4);
    }
    *(s32 *)((char *)&hero + 0x710) = 0;
    total = *(s32 *)((char *)&hero + 0x70C);
    if (total > 0) {
        step = 100;
        do {
            *(s32 *)((char *)&hero + 0x710) += step;
            step += 50;
        } while (--total != 0);
    }
    *(s32 *)((char *)&hero + 0x6F0) = 0;
    for (i = 0; i < 4; i++) {
        if (*(s32 *)((char *)&hero + 0x6E0 + i * 4) != 0) (*(s32 *)((char *)&hero + 0x6F0))++;
    }
    table = *(typeof(table) *)D_L05_002169F8;
    *(f32 *)((char *)&hero + 0x6F4) = table.values[*(s32 *)((char *)&hero + 0x6F0)];
    frames = FUN_001f96b0(1.0f);
    *(s32 *)((char *)&hero + 0x6FC) = truncate_float_to_s32((f32)((*(s32 *)((char *)&hero + 0x6F8) * 100) / (s32)(frames * 60.0f)));
    *(s32 *)((char *)&hero + 0x6FC) += *(s32 *)((char *)&hero + 0x6F0) * 25;
    *(s32 *)((char *)&hero + 0x6FC) = truncate_float_to_s32((f32)*(s32 *)((char *)&hero + 0x6FC) * *(f32 *)((char *)&hero + 0x6F4));
    *(s32 *)((char *)&hero + 0x714) = *(s32 *)((char *)&hero + 0x710) + *(s32 *)((char *)&hero + 0x6FC);
}
#endif
#ifndef NON_MATCHING
INCLUDE_ASM("config/us/overlays/asm/FUN_L05_00254358.s", FUN_L05_00254358);
#else
extern char *D_L05_001B0930[];
extern f32 FUN_001f9e90(f32, f32);
extern f32 fast_difference_between_rotations(f32, f32) __asm__("FUN_001fa688");
extern f32 FUN_001f9b80(void *, void *);
extern void clear_u64_value(void *) __asm__("FUN_001f99f8");
extern f32 find_ground_height(f32, void *, s32) __asm__("FUN_00213508");
extern s32 current_level_index __asm__("D_0015ED84") __attribute__((sda));

typedef struct {
    f32 x, y, z, w;
} __attribute__((aligned(16))) HelpPathPoint;

typedef struct {
    s32 count;
    u8 pad[12];
    HelpPathPoint points[1];
} HelpPath;

void FUN_L05_00254358(f32 *position, f32 *direction) {
    char *g = (char *)&hero;
    HelpPath *path;
    f32 best;
    s32 index = 0;
    s32 selected = 0;
    HelpPathPoint point;
    HelpPathPoint *p;
    char *origin = g + 0x80;

    if (*(void **)(g + 0x86C) == 0) {
        *(HelpPathPoint *)position = *(HelpPathPoint *)origin;
        *(HelpPathPoint *)direction = *(HelpPathPoint *)(origin + 0x10);
        return;
    }
    path = (HelpPath *)D_L05_001B0930[*(s32 *)(*(char **)(*(char **)(g + 0x86C) + 0x78) + 0x24)];
    best = 9999999.0f;
    if (path->count > 0) do {
        f32 a;
        s32 next;
        f32 b;
        p = &path->points[index];
        a = FUN_001f9e90(p->x - *(f32 *)(origin + 0), p->y - *(f32 *)(origin + 4));
        next = (index + (path->count + 2)) % path->count;
        b = FUN_001f9e90(path->points[next].x - p->x, path->points[next].y - p->y);
        if (fast_difference_between_rotations(a, b) > 1.5707964f) {
            if (current_level_index == 0x10 && *(void **)(g + 0x8B4) != 0) {
                f32 a = *(f32 *)(origin + *(s16 *)(g + 0x8C8) * 16 + 0x18);
                f32 b = *(f32 *)(origin + *(s16 *)(g + 0x898) * 16 + 0x18);
                f32 high = b;
                if (!(a < b)) high = a;
                if (absolute_float(high - p->z) > 4.0f) {
                    goto next_point;
                }
            }
            {
                f32 distance = FUN_001f9b80(origin, p);
                if (distance < best) {
                    best = distance;
                    selected = index;
                }
            }
        } else {
            selected = index;
        }
next_point:
        index += 2;
    } while (index < path->count);
    p = &path->points[selected];
    *(HelpPathPoint *)position = *p;
    point = *(HelpPathPoint *)position;
    point.z += 2.0f;
    position[2] = find_ground_height(0.5f, &point, 0);
    clear_u64_value(direction);
    direction[2] = FUN_001f9e90(p[1].x - p->x, p[1].y - p->y);
}
#endif
INCLUDE_ASM("config/us/overlays/asm/FUN_L05_00254608.s", FUN_L05_00254608);
#include "sda.h"

/* Ported from rac1-decomp (src/overlays/shared/help_00237B00.c: func_L05_002559A0), where it is exact; names translated to the US level program. */


int FUN_L05_002551b8(void) {
    unsigned char b = hero.unk8CE; // selected help mode
    int r = 0x7F;
    if (b == 0)
        r = 0x55;
    return r;
}
int FUN_L05_002551d0(void) {
    struct Hero *p = &hero;
    int f = p->unk8CE;
    if (p->unk884 == 0) {
        int r = 0x7D;
        if (f == 0)
            r = 0x52;
        return r;
    }
    { return f == 0 ? 0x68 : 0x7E; }
}
#define NOT_SDA

#define MACRO_ADDR

INCLUDE_ASM("config/us/overlays/asm/FUN_L05_00255208.s", FUN_L05_00255208);
/* Ported from rac1-decomp (src/overlays/shared/help_00237B00.c: func_L05_0025BDA8), where it is exact; names translated to the US level program. */

extern char D_L05_0017C068[];
extern unsigned char D_0013E533[];

void FUN_L05_0025b538(void) {
    char *g = (char *)D_0013E533 + 0xE1D;
    int v = *(int *)(g + 0x86C);

    *(int *)(g + 0x2278) = 0;
    *(int *)(g + 0x227C) = 0;
    if (v != 0) {
        if ((unsigned)(*(int *)(g + 0x208C) - 0x15) < 2) {
            *(int *)(g + 0x2278) = v;
            *(int *)(g + 0x227C) = (int)D_L05_0017C068;
        }
    }
}
