/* Level overlay code after unclassified; generated by `decomp overlays stubs`, stubs replaced by C as functions are matched. */
#include "types.h"
#include "rnc/globals.h"
#include "rnc/math_consts.h"
#include "asm.h"
#include "rnc/math/vector.h"
#include "rnc/gameplay/entities/moby.h"

#define NOT_SDA

#define MACRO_ADDR

/* finds the first of eight linked entries whose direction lines up with the moby */
/* Ported from rac1-decomp (src/overlays/l08_batalia/vendor_002E0258.c: func_L08_002E15A0), where it is exact; names translated to the US level program. */

extern char D_L08_001675C0[];
extern float FUN_001f9ab0(void *, void *);
extern float FUN_001f9dc8(float);
extern void FUN_001f9a28(void *, void *, void *);
extern void FUN_001f9bf8(void *, void *, float);
void build_spherical_offset(f32 *out, f32 scale, f32 a, f32 b) __asm__("FUN_00214db0");

int FUN_L08_002e0228(struct Moby *m) {
    float a[4];
    float b[4];
    int *p = (int *)((char *)m->pvars + 0x60);
    int i;
    for (i = 0; i < 8; i++) {
        if (p[i] != 0) {
            float d;
            build_spherical_offset(a, 1.0f, m->rot.z, -m->rot.y);
            FUN_001f9a28(b, (char *)p[i] + 0x10, D_L08_001675C0);
            FUN_001f9bf8(b, b, 1.0f);
            d = FUN_001f9ab0(b, a);
            if (FUN_001f9dc8(0.06981317f) < d)
                return p[i];
        }
    }
    return 0;
}
#define NOT_SDA

#define MACRO_ADDR

/* Ported from rac1-decomp (src/overlays/l08_batalia/vendor_002E0258.c: func_L08_002E2A10), where it is exact; names translated to the US level program. */

extern int hero_set_state(int, int) __asm__("FUN_L08_00230b38");

/* Sets the moby's byte 0xBC and calls hero_set_state(0x32, 1). */
void FUN_L08_002e1698(struct Moby *arg) {
    arg->unkBC = 1;
    hero_set_state(0x32, 1);
}
#include "qcopy.h"

/* Ported from rac1-decomp (src/overlays/l08_batalia/vendor_002E0258.c: func_L08_002E3010), where it is exact; names translated to the US level program. */

extern char *func_0020D348_m(int);
extern char D_0013E533[];
extern void FUN_L00_0024f7c8(void *, int, void *);
extern void FUN_L00_00250df8(void *);

void *FUN_L08_002e1c98(struct Moby *parent, int oClass, int joint, int pjoint) {
    unsigned char *m = func_0020D348_m(oClass);
    float v0[4], v10[4];
    if (m != 0) {
        m[0x30] = 0xFF;
        *(short *)(m + 0x32) = 0xFF;
        m[0x31] = 1;
        *(unsigned short *)(m + 0x34) |= 0x4000;
        *(long *)(m + 0x38) = *(long *)(*(char **)(D_0013E533 + 0x2E9D) + 0x38);
        qcopy(m + 0x40, &parent->rot);
        FUN_L00_0024f7c8(m, joint, v0);
        FUN_L00_0024f7c8(parent, pjoint, v10);
        FUN_001f9a28(m + 0x10, v10, v0);
        FUN_L00_00250df8(m);
    }
    return m;
}
/* builds a basis from a direction vector and writes the orientation into the moby */
/* Ported from rac1-decomp (src/overlays/l08_batalia/vendor_002E0258.c: func_L08_002E6130), where it is exact; names translated to the US level program. */

extern void clear_u64_value(void *) __asm__("FUN_001f99f8");
extern void FUN_001fa050(float *, float *);
extern void FUN_00214598(void *, void *);
extern void fast_vec_cross(void *, void *, void *) __asm__("FUN_001f9ad8");

void FUN_L08_002e4db8(struct Moby *a, float *v) {
    float m[16];
    float n[16];
    float r[4];
    float s[4];
    char *d = (char *)a->pvars;
    r[1] = v[2];
    r[2] = v[0];
    r[0] = -v[1];
    fast_vec_cross(r, v, r);
    fast_vec_cross(s, r, v);
    qcopy(m, r);
    qcopy(m + 4, s);
    qcopy(m + 8, v);
    clear_u64_value(m + 12);
    d += 0x10;
    m[15] = 1.0f;
    FUN_00214598(m, d);
    FUN_001fa050(n, (float *)d);
    n[15] = 42.0f;
}
/* spawns the child mobys this object owns and fills its part table */
/* Ported from rac1-decomp (src/overlays/l08_batalia/vendor_002E0258.c: func_L08_002E9B60), where it is exact; names translated to the US level program. */

extern int FUN_L08_002e1c98_c() __asm__("FUN_L08_002e1c98");

void FUN_L08_002e8788(char *moby) {
    char *data = *(char **)(moby + 0x78);
    char *e = data + 0xBC;
    int i = 0;
    char *c;
    char *c2;
    char *c3;
    *(char **)(data + 0x60) = moby;
    *(int *)(data + 0x64) = 0;
    *(int *)(data + 0x68) = 0;
    *(int *)(data + 0x6C) = 0;
    *(char **)(data + 0x90) = FUN_L08_002e1c98_c(moby, 0x1C0, 1, 0);
    *(char **)(data + 0x94) = moby;
    *(int *)(data + 0x98) = 1;
    *(int *)(data + 0x9C) = 0;
    c = FUN_L08_002e1c98_c(moby, 0x1BD, 0, 2);
    *(char **)(data + 0x70) = c;
    *(int *)(data + 0x7C) = 2;
    *(char **)(data + 0x74) = moby;
    *(int *)(data + 0x78) = 0;
    *(float *)(c + 0x2C) = *(float *)(*(char **)(c + 0x24) + 0x24) * 0.75f;
    c2 = FUN_L08_002e1c98_c(moby, 0x1BA, 1, 1);
    *(char **)(data + 0x80) = c2;
    *(char **)(data + 0x84) = moby;
    *(int *)(data + 0x88) = 1;
    *(int *)(data + 0x8C) = 1;
    c3 = FUN_L08_002e1c98_c(c2, 0x1B9, 0, 0);
    *(char **)(data + 0xA0) = c3;
    *(char **)(data + 0xA4) = *(char **)(data + 0x80);
    *(int *)(data + 0xA8) = 0;
    *(int *)(data + 0xAC) = 0;
    do {
        int j = i + 2;
        i++;
        *(char **)(e - 0xC) = FUN_L08_002e1c98_c(*(char **)(data + 0x90), 0x1BB, 0, j);
        *(char **)(e - 8) = *(char **)(data + 0x90);
        *(int *)(e - 4) = 0;
        *(int *)e = j;
        e += 0x10;
    } while (i < 8);
}
/* Re-aims the twelve child mobys of a parent, adjusts the parent's spin, then runs the children's follow-up. */
/* Ported from rac1-decomp (src/overlays/l08_batalia/vendor_002E0258.c: func_L08_002E9F78), where it is exact; names translated to the US level program. */

extern float D_0015ED6C_d __asm__("D_0015ED6C");
extern float fast_add_rotations(float, float) __asm__("FUN_001fa580");
extern short D_L08_00161D28_d __asm__("D_L08_00161D28") __attribute__((sda));
extern void FUN_001f9a10(void *, void *, void *);
extern void FUN_001f9a28(void *, void *, void *);
extern void FUN_L00_0024f7c8(void *, int, void *);
extern void FUN_L00_00250df8(void *);

void FUN_L08_002e8ba0(struct Moby *a) {
    char *data = (char *)a->pvars;
    float v0[4], v10[4], v20[4];
    char *base = data + 0x60;
    int i;
    for (i = 0; i < 12; i++) {
        int *e = (int *)(base + 0x1C + i * 16);
        char *m = (char *)e[-3];
        if (m != 0) {
            *(float *)(m + 0x48) = a->rot.z;
            FUN_L00_0024f7c8(m, e[-1], v0);
            FUN_L00_0024f7c8((void *)e[-2], e[0], v10);
            FUN_001f9a28(v20, v10, v0);
            FUN_001f9a10(m + 0x10, m + 0x10, v20);
        }
    }
    if (*(int *)(data + 0x90) != 0) {
        char *r = *(char **)(data + 0x90);
        *(float *)(*(char **)(data + 0x90) + 0x40) = fast_add_rotations(
            *(float *)(r + 0x40),
            *(float *)&D_L08_00161D28_d * DEG_TO_RAD * D_0015ED6C_d);
    }
    for (i = 0; i < 12; i++) {
        char *m = *(char **)(base + 0x10 + i * 16);
        if (m != 0)
            FUN_L00_00250df8(m);
    }
}
/* Ported from rac1-decomp (src/overlays/l08_batalia/vendor_002E0258.c: func_L08_002EADF0), where it is exact; names translated to the US level program. */

extern short D_L08_00161D38_d __asm__("D_L08_00161D38") __attribute__((sda));
extern void FUN_001f9a68(void *, void *, float);

void FUN_L08_002e9a18(struct Moby *arg) {
    char *data = (char *)arg->pvars;
    float v0[4];
    float v1[4];
    float v2[4];
    int i;
    char *p;
    char *parts = data + 0x60;
    for (i = 0; i < 16; i++) {
        char *e = parts + 0x1C + i * 16;
        char *part = *(char **)(e - 0xC);
        if (part != 0) {
            *(float *)(part + 0x48) = arg->rot.z;
            FUN_L00_0024f7c8(part, *(int *)(e - 4), v0);
            FUN_L00_0024f7c8(*(void **)(e - 8), *(int *)e, v1);
            FUN_001f9a28(v2, v1, v0);
            FUN_001f9a10(part + 0x10, part + 0x10, v2);
        }
    }
    if (*(char **)(data + 0x90) != 0) {
        *(float *)(*(char **)(data + 0x90) + 0x40) =
            fast_add_rotations(*(float *)(*(char **)(data + 0x90) + 0x40),
                               *(float *)&D_L08_00161D38_d * DEG_TO_RAD * D_0015ED6C_d);
    }
    p = parts + 0x10;
    for (i = 0; i < 16; i++) {
        char *o = *(char **)p;
        if (o != 0) {
            FUN_L00_00250df8(o);
            o = *(char **)p;
            if (*(unsigned short *)(o + 0x34) & 0x8000) {
                FUN_001f9a68(o + 0xD0, o + 0xD0, -1.0f);
            }
        }
        p += 16;
    }
}

INCLUDE_ASM("config/us/overlays/asm/FUN_L08_002deee0.s", FUN_L08_002deee0);
INCLUDE_ASM("config/us/overlays/asm/FUN_L08_002e0328.s", FUN_L08_002e0328);
#include "sda.h"

/* Update function for moby classes 441-443 on level 08 (falling debris): picks its spin, falls with a smoke trail, bursts into particles near the ground, then falls on until out of bounds. */
/* Ported from rac1-decomp (src/overlays/l08_batalia/vendor_002E0258.c: func_L08_002E2A38), where it is exact; names translated to the US level program. */

typedef struct {
    float vel[4];              /* 0x00 */
    float spin_x;              /* 0x10 */
    float spin_y;              /* 0x14 */
    int life;                  /* 0x18 */
} Data_2E2A38;

typedef struct {
    char pad0[0x10];
    float pos[4];              /* 0x10 */
    unsigned char state;       /* 0x20 */
    char pad21[0x1F];
    float rot[4];              /* 0x40 */
    char pad50[0x28];
    Data_2E2A38 *data;         /* 0x78 */
} Moby_2E2A38;

typedef struct {
    int v[2];
} Pair_2E2A38;

extern Pair_2E2A38 D_L08_00161C30 __attribute__((section(".data")));
extern f32 fast_add_rotations_c(f32, f32) __asm__("func_001FA580");
extern f32 fast_cos(f32) __asm__("func_001F9DC8");
extern f32 fast_sin(f32) __asm__("func_001F9DE0");
extern f32 random_angle_radians_c(void) __asm__("func_00213308");
extern f32 random_float_between_c2(f32, f32) __asm__("func_002132A8");
extern float D_0015ED6C_c __asm__("D_0015ED6C") __attribute__((section(".sdata")));
extern float D_0015ED70 __attribute__((section(".sdata")));
extern float FUN_001f96b0_c(float) __asm__("FUN_001f96b0");
extern int D_L08_00161C00 __attribute__((sda));
extern int D_L08_00161C04 __attribute__((sda));
extern int D_L08_00161C08 __attribute__((sda));
extern float D_L08_00161C0C __attribute__((sda));
extern float D_L08_00161C10 __attribute__((sda));
extern float D_L08_00161C14 __attribute__((sda));
extern float D_L08_00161C18 __attribute__((sda));
extern int D_L08_00161C1C __attribute__((sda));
extern int D_L08_00161C20 __attribute__((sda));
extern int D_L08_00161C24 __attribute__((sda));
extern float D_L08_00161C28 __attribute__((sda));
extern float D_L08_00161C2C __attribute__((sda));
extern int FUN_00218888();
extern int FUN_L00_00257b90(int, int);
extern int scale_game_frames_alt(int) __asm__("FUN_001f96f8");
extern s32 random_integer_below_c(s32) __asm__("func_00213260");
extern s32 truncate_float_to_s32_c2(f32) __asm__("func_001FA6D0");
extern void add_vector_xyz(void *, void *, void *) __asm__("FUN_001f9a10");
extern void clear_u64_value(void *) __asm__("func_001F99F8");
extern void mark_moby_for_removal_c(void *) __asm__("func_0020C828");
void FUN_L00_0026a9f0(void *pos, void *dir, int col, int d, int n, int b1A, int b18, int b19, float x, float y);
extern void func_L00_0026B890_2E2A38(void *, void *, int, int, int, int, int, int, float, float) __asm__("FUN_L00_0026a9f0");
extern char *func_00219780_2E2A38(void *, void *, void *, int, int, int, int, int, int) __asm__("FUN_00218888");

void FUN_L08_002e16c0(Moby_2E2A38 *m) {
    Data_2E2A38 *d = m->data;
    float v10[4];
    Pair_2E2A38 tab;
    float v30[4];
    float a40[4];
    int i;

    switch (m->state) {
    case 1:
        d->spin_x = random_float_between_c2(-(D_0015ED6C_c * 1.5707964f), D_0015ED6C_c * 1.5707964f);
        d->spin_y = random_float_between_c2(-(D_0015ED6C_c * 1.5707964f), D_0015ED6C_c * 1.5707964f);
        d->life = (int)random_float_between_c2((float)scale_game_frames_alt(0x5A), (float)scale_game_frames_alt(0x96));
        m->state = 2;
    case 2:
        d->vel[2] -= D_0015ED70 * 10.8f * 0.5f;
        add_vector_xyz(m->pos, m->pos, d);
        m->rot[0] = fast_add_rotations_c(m->rot[0], d->spin_x);
        m->rot[1] = fast_add_rotations_c(m->rot[1], d->spin_y);
        if (m->pos[0] < 8.0f || m->pos[1] < 8.0f || m->pos[0] > 500.0f || m->pos[1] > 500.0f ||
            m->pos[2] > 500.0f) {
            mark_moby_for_removal_c(m);
            return;
        }
        if (random_integer_below_c(3) == 0) {
            int *q;
            int a;
            int b;
            clear_u64_value(v10);
            tab = D_L08_00161C30;
            q = &tab.v[random_integer_below_c(2)];
            {
                int lo = scale_game_frames_alt(15), hi = scale_game_frames_alt(20);
                a = FUN_L00_00257b90(lo, hi);
            }
            {
                int lo = scale_game_frames_alt(25);
                b = FUN_L00_00257b90(lo, scale_game_frames_alt(30));
            }
            func_L00_0026B890_2E2A38(m->pos, v10, 0x2F3F3F7F, *q, a, b, 0, 0, 400000.0f,
                                     random_float_between_c2(8.0f, 16.0f) * D_0015ED6C_c);
        }
        if (m->pos[2] < 15.2f) {
            for (i = 0; i < D_L08_00161C00; i++) {
                float ang = random_angle_radians_c();
                int c1;
                int c2;
                int c3;
                qcopy(a40, m->pos);
                a40[0] += random_float_between_c2(-3.0f, 3.0f);
                a40[1] += random_float_between_c2(-3.0f, 3.0f);
                v10[2] = D_L08_00161C0C * D_0015ED6C_c;
                v10[0] += fast_cos(ang) * D_L08_00161C14;
                v10[1] += fast_sin(ang) * D_L08_00161C14;
                v30[2] = D_L08_00161C10 * D_0015ED6C_c;
                v30[0] += fast_cos(ang) * D_L08_00161C18;
                v30[1] += fast_sin(ang) * D_L08_00161C18;
                v10[3] = D_L08_00161C28;
                v30[3] = D_L08_00161C2C;
                c1 = truncate_float_to_s32_c2(FUN_001f96b0_c(random_float_between_c2((float)D_L08_00161C1C, (float)(D_L08_00161C1C * 2))));
                c2 = truncate_float_to_s32_c2(FUN_001f96b0_c(random_float_between_c2((float)D_L08_00161C20, (float)(D_L08_00161C20 * 2))));
                c3 = truncate_float_to_s32_c2(FUN_001f96b0_c(random_float_between_c2((float)D_L08_00161C24, (float)(D_L08_00161C24 * 2))));
                func_00219780_2E2A38(a40, v10, v30, D_L08_00161C04, D_L08_00161C08, c1, c2, c3, -1);
            }
            m->state = 3;
        }
        break;
    case 3:
        d->vel[2] -= D_0015ED70 * 10.8f * 0.5f;
        add_vector_xyz(m->pos, m->pos, d);
        m->rot[0] = fast_add_rotations_c(m->rot[0], d->spin_x);
        m->rot[1] = fast_add_rotations_c(m->rot[1], d->spin_y);
        if (m->pos[0] < 8.0f || m->pos[1] < 8.0f || m->pos[2] < 8.0f || m->pos[0] > 500.0f ||
            m->pos[1] > 500.0f) {
            mark_moby_for_removal_c(m);
        }
        break;
    }
}
/* Builds the target board: spawns the frame, the three rows of eight targets
 * and their mounts, and records each piece with the piece it hangs from. */

typedef struct {
    struct Moby *moby;
    struct Moby *anchor;
    s32 joint;   /* joint on this piece */
    s32 pjoint;  /* joint on the anchor it hangs from */
} TargetSlot;

typedef struct {
    u8 pad0[0x60];
    TargetSlot slots[34];
    u8 pad280[0xC];
    s16 points;
} TargetBoardVars;

void FUN_L08_002e1d70(struct Moby *moby) {
    TargetBoardVars *vars = (TargetBoardVars *)moby->pvars;
    struct Moby *m;
    s32 i;
    s32 pjoint;

    vars->slots[0].moby = moby;
    vars->slots[0].anchor = 0;
    vars->slots[0].joint = 0;
    vars->slots[0].pjoint = 0;
    vars->slots[3].moby = FUN_L08_002e1c98((char *)moby, 0x1C1, 0, 2);
    vars->slots[3].anchor = moby;
    vars->slots[3].joint = 0;
    vars->slots[3].pjoint = 2;
    pjoint = 3;
    vars->slots[1].moby = FUN_L08_002e1c98((char *)moby, 0x1C2, 0, pjoint);
    vars->slots[1].anchor = moby;
    vars->slots[1].joint = 0;
    vars->slots[1].pjoint = pjoint;
    m = FUN_L08_002e1c98((char *)moby, 0x1C2, 0, 4);
    vars->slots[2].moby = m;
    m->flags |= 0x8000;
    vars->slots[2].anchor = moby;
    vars->slots[2].joint = 0;
    vars->slots[2].pjoint = 4;
    vars->slots[7].moby = FUN_L08_002e1c98((char *)moby, 0x1C0, 0, 0);
    vars->slots[7].anchor = moby;
    vars->slots[7].joint = 0;
    vars->slots[7].pjoint = 0;
    vars->slots[8].moby = FUN_L08_002e1c98((char *)moby, 0x1C0, 1, 1);
    vars->slots[8].anchor = moby;
    vars->slots[8].joint = 1;
    vars->slots[8].pjoint = 1;
    vars->slots[9].moby = FUN_L08_002e1c98((char *)vars->slots[8].moby, 0x1C0, 1, 0);
    vars->slots[9].anchor = vars->slots[8].moby;
    vars->slots[9].joint = 1;
    vars->slots[9].pjoint = 0;
    vars->slots[5].moby = FUN_L08_002e1c98((char *)vars->slots[9].moby, 0x1BD, 0, 0);
    vars->slots[5].anchor = vars->slots[9].moby;
    vars->slots[5].joint = 0;
    vars->slots[5].pjoint = 0;
    vars->slots[6].moby = FUN_L08_002e1c98((char *)vars->slots[7].moby, 0x1BA, 1, 1);
    vars->slots[6].anchor = vars->slots[7].moby;
    vars->slots[6].joint = 1;
    vars->slots[6].pjoint = 1;
    vars->slots[4].moby = FUN_L08_002e1c98((char *)moby, 0x1B9, 0, 0);
    vars->slots[4].anchor = vars->slots[6].moby;
    vars->slots[4].joint = 0;
    vars->slots[4].pjoint = 0;
    for (i = 0; i < 8; i++) {
        vars->slots[10 + i].moby = FUN_L08_002e1c98((char *)vars->slots[7].moby, 0x1BB, 0, i + 2);
        vars->slots[10 + i].anchor = vars->slots[7].moby;
        vars->slots[10 + i].joint = 0;
        vars->slots[10 + i].pjoint = i + 2;
    }
    for (i = 0; i < 8; i++) {
        vars->slots[18 + i].moby = FUN_L08_002e1c98((char *)vars->slots[8].moby, 0x1BB, 0, i + 2);
        vars->slots[18 + i].anchor = vars->slots[8].moby;
        vars->slots[18 + i].joint = 0;
        vars->slots[18 + i].pjoint = i + 2;
    }
    for (i = 0; i < 8; i++) {
        vars->slots[26 + i].moby = FUN_L08_002e1c98((char *)vars->slots[9].moby, 0x1BB, 0, i + 2);
        vars->slots[26 + i].anchor = vars->slots[9].moby;
        vars->slots[26 + i].joint = 0;
        vars->slots[26 + i].pjoint = i + 2;
    }
}
#include "rnc/gameplay/hero.h"
extern float D_L08_00161C3C __attribute__((sda));
extern f32 FUN_001f9e90(f32, f32);

typedef struct {
    struct Moby *part;      /* moved along with the anchor's joint */
    struct Moby *anchor;
    int part_joint;
    int anchor_joint;
} PartLink;

typedef struct {
    u8 pad0[0x60];
    PartLink links[34];     /* 0x60: entry 0 is unused */
} LinkedPartsVars;

/* Keeps the 33 linked parts glued to their anchors' joints and facing the moby, spins three of them (the middle
   one backwards), turns link 3 towards the hero, then updates every part. */
void FUN_L08_002e2078(struct Moby *m) {
    LinkedPartsVars *v = (LinkedPartsVars *)m->pvars;
    PartLink *links = v->links;
    float a[4];
    float b[4];
    float d[4];
    int i;

    for (i = 1; i < 34; i++) {
        struct Moby *part = v->links[i].part;
        if (part != 0) {
            part->rot.z = m->rot.z;
            FUN_L00_0024f7c8(part, v->links[i].part_joint, a);
            FUN_L00_0024f7c8(v->links[i].anchor, v->links[i].anchor_joint, b);
            FUN_001f9a28(d, b, a);
            FUN_001f9a10(&part->pos, &part->pos, d);
        }
    }
    if (v->links[7].part != 0) {
        v->links[7].part->rot.x = fast_add_rotations(v->links[7].part->rot.x, D_L08_00161C3C * DEG_TO_RAD * D_0015ED6C_d);
    }
    if (v->links[8].part != 0) {
        v->links[8].part->rot.x = fast_add_rotations(v->links[8].part->rot.x, -(D_L08_00161C3C * DEG_TO_RAD * D_0015ED6C_d));
    }
    if (v->links[9].part != 0) {
        v->links[9].part->rot.x = fast_add_rotations(v->links[9].part->rot.x, D_L08_00161C3C * DEG_TO_RAD * D_0015ED6C_d);
    }
    if (v->links[3].part != 0) {
        v->links[3].part->rot.z = FUN_001f9e90(hero.motion.pos.f[0] - v->links[3].part->pos.x, hero.motion.pos.f[1] - v->links[3].part->pos.y);
    }
    for (i = 1; i < 34; i++) {
        if (links[i].part != 0) {
            FUN_L00_00250df8(links[i].part);
        }
    }
}
#ifndef NON_MATCHING
INCLUDE_ASM("config/us/overlays/asm/FUN_L08_002e2250.s", FUN_L08_002e2250);
#else
extern int target_board_check_hit(struct Moby *, int, int) __asm__("FUN_L00_0025a420");
extern void FUN_L00_0025f090(void *, void *, s32, f32, f32);
extern void FUN_001f9a28(void *, void *, void *);
extern void normalize_vector_xyz(void *, void *, f32) __asm__("FUN_001f9bf8");
extern f32 random_float_between(f32, f32) __asm__("FUN_002132a8");
extern s32 truncate_float_to_s32(f32) __asm__("FUN_001fa6d0");
extern s32 allocate_voice_for_target_entry(s32, s32, struct Moby *) __asm__("FUN_0022da68");
extern float D_0015ED6C;

void FUN_L08_002e2250(struct Moby *moby) {
    u8 mark = 0xff;
    int selected = 0;
    TargetBoardVars *vars = (TargetBoardVars *)moby->pvars;
    TargetSlot *slots = vars->slots;
    TargetSlot *slot = slots;
    int i = 0;
    int hits = 0;
    int sound = -1;
    int total;

    do {
        if (slot->moby != 0) {
            if (target_board_check_hit(slot->moby, 0x10000, 0) != 0) {
                if (i < 7) {
                    if (hits < 1) {
                        hits = 1;
                        sound = 1;
                        goto mark_hit;
                    }
                } else if (i < 10) {
                    if (hits < 2) {
                        hits = 2;
                        sound = 1;
                        goto mark_hit;
                    }
                } else if (hits < 4) {
                    hits += 4;
                    selected = i;
                    sound = 2;
                    goto mark_hit;
                }
mark_hit:
                slot->moby->unkA4 = mark;
            }
        }
        i++;
        slot++;
    } while (i < 34);
    vars->points = (u16)vars->points + hits;
    total = vars->points;
    if (total >= 8) {
        vars->points = total - (total / 8) * 8;
        sound = 0;
        if (selected != 0) {
            u8 *vector;
            slot = (TargetSlot *)((char *)vars + 0x60 + selected * 16);
            vector = slot->moby->pvars;
            FUN_L00_0025f090(moby, &slot->moby->pos, -1, 2.0f, 13.0f);
            FUN_001f9a28(vector, &slot->moby->pos, &(*(struct Moby **)((char *)vars + 0x64 + selected * 16))->pos);
            normalize_vector_xyz(vector, vector, D_0015ED6C * 10.0f);
            slot->moby->state = 1;
            slot->moby = 0;
            return;
        }
        {
            int start = truncate_float_to_s32(random_float_between(0.0f, 23.0f));
            i = 0;
            do {
                int index = (i + start) % 24 + 10;
                slot = &slots[index];
                i++;
                if (slot->moby != 0) {
                    u8 *vector = slot->moby->pvars;
                    FUN_L00_0025f090(moby, &slot->moby->pos, -1, 2.0f, 13.0f);
                    FUN_001f9a28(vector, &slot->moby->pos, &slot->anchor->pos);
                    normalize_vector_xyz(vector, vector, D_0015ED6C * 10.0f);
                    slot->moby->state = 1;
                    slot->moby = 0;
                    return;
                }
            } while (i < 24);
            moby->state = 99;
        }
    }
play_sound:
    if (sound >= 0)
        allocate_voice_for_target_entry(sound, 0, moby);
}
#endif /* NON_MATCHING */
/* A looping waypoint path: count points, 16 bytes apart. */
typedef struct {
    s32 count;
    u8 pad4[0xC];
    Vec4 points[1];
} SwarmPath;

/* Position on a path: the current point, the step direction and the path. */
typedef struct {
    s32 point;
    s8 direction;
    u8 pad5[0xB];
    SwarmPath *path;
    s32 path_id; /* index into D_L08_001B0CB0 */
    u8 pad18[0x18];
} SwarmPathFollower;

/* pvars of the target: the projectiles fired at it. */
typedef struct {
    u8 pad0[0x60];
    struct Moby *shots[8];
} SwarmTargetVars;

/* Gun turret on a gunship: cruises one path firing at its target, or circles a second path firing at random. */
typedef struct {
    SwarmPathFollower follow[2]; /* 0x00: [0] cruising (state 1), [1] circling (state 2) */
    PartLink links[34];          /* 0x60: entry 0 is unused */
    s32 target_index;            /* 0x280: moby slot of the target */
    f32 turn_speed;              /* 0x284 */
    s32 fire_timer;              /* 0x288 */
    s16 pad28C;
    s16 sound;                   /* 0x28E */
} GunshipVars;

extern s32 D_L08_00161C4C __attribute__((sda));
extern f32 D_L08_00161C38 __attribute__((sda));
extern f32 D_L08_00161C44 __attribute__((sda));
extern f32 D_L08_00161C48 __attribute__((sda));
extern u8 D_0014C050[];
extern SwarmPath *D_L08_001B0CB0[];
extern struct Moby *D_L08_0015FFD8_m __asm__("D_L08_0015FFD8");

extern s32 FUN_L00_0028d8c0(struct Moby *, s32);
extern s32 allocate_voice_for_target_entry(s32, s32, struct Moby *) __asm__("FUN_0022da68");
extern void mark_moby_for_removal(void *) __asm__("FUN_0020c828");
extern f32 random_float_between(f32, f32) __asm__("FUN_002132a8");
extern f32 random_angle_radians(void) __asm__("FUN_00213308");
extern int random_integer_below(int) __asm__("FUN_00213260");
extern f32 FUN_001f96b0(f32);
extern s32 truncate_float_to_s32(f32) __asm__("FUN_001fa6d0");
extern f32 fast_add_rotations(f32, f32) __asm__("FUN_001fa580");
extern f32 fast_subtract_rotations(f32, f32) __asm__("FUN_001fa5c8");
extern s32 tick_countdown_32_alt(s32 *) __asm__("FUN_001f9740");
extern f32 FUN_001f9b48(void *, void *);
extern f32 vector_length_xyz(void *) __asm__("FUN_001f9af0");
extern void normalize_vector_xyz(void *, void *, f32) __asm__("FUN_001f9bf8");
extern void add_vector_xyz(void *, void *, void *) __asm__("FUN_001f9a10");
extern void subtract_vector_xyz(void *, void *, void *) __asm__("FUN_001f9a28");
extern void FUN_L00_0024f7c8(void *, int, void *);
extern void FUN_L00_00258278(struct Moby *, f32, f32 *, f32, f32, f32);
extern float FUN_L00_0025be00(float *, float *, float, float, float, float);
extern void FUN_L00_0025f090(void *, void *, s32, f32, f32);
extern struct Moby *FUN_L08_002de3e0(void *, struct Moby *, void *, f32, f32);
extern void FUN_L08_002e2250(struct Moby *);

void FUN_L08_002e24e8(struct Moby *moby) {
    GunshipVars *vars = (GunshipVars *)moby->pvars;
    SwarmPathFollower *follower;
    struct Moby *target;
    struct Moby *shot;
    struct Moby *bolt;
    SwarmTargetVars *target_vars;
    Vec4 point;
    Vec4 step;
    Vec4 muzzle;
    Vec4 velocity;
    s32 waypoint;
    s32 next;
    s32 after;
    s32 i;
    s32 slot;
    f32 distance;
    f32 heading;
    f32 next_heading;
    f32 turn;
    f32 pitch;
    f32 yaw;

    if (D_L08_00161C4C != 0) {
        return;
    }
    if (!FUN_L00_0028d8c0(moby, vars->sound)) {
        vars->sound = allocate_voice_for_target_entry(3, 4, moby);
    }
    switch (moby->state) {
    case 0:
        if (D_0014C050[moby->unkB0 + current_level_index * 16] == 0xFF) {
            mark_moby_for_removal(moby);
            return;
        }
        vars->follow[0].path = D_L08_001B0CB0[vars->follow[0].path_id];
        vars->follow[1].path = D_L08_001B0CB0[vars->follow[1].path_id];
        vars->fire_timer = truncate_float_to_s32(FUN_001f96b0(random_float_between(300.0f, 600.0f)));
        qcopy(&moby->pos, &vars->follow[1].path->points[0]);
        FUN_L08_002e1d70(moby);
        moby->state = 2;
        moby->rot.z = FUN_001f9e90(vars->follow[1].path->points[1].f[0] - moby->pos.x,
                                   vars->follow[1].path->points[1].f[1] - moby->pos.y);
        moby->flags |= 0x4000;
        break;
    case 1:
        waypoint = (vars->follow[0].point + vars->follow[0].path->count + vars->follow[0].direction) % vars->follow[0].path->count;
        target = &D_L08_0015FFD8_m[vars->target_index];
        FUN_L00_00258278(moby,
                         FUN_001f9e90(vars->follow[0].path->points[waypoint].f[0] - moby->pos.x,
                                      vars->follow[0].path->points[waypoint].f[1] - moby->pos.y),
                         &vars->turn_speed, 0.004f, 0.3f, 0.02f);
        FUN_L08_002e2250(moby);
        FUN_L08_002e2078(moby);
        qcopy(&point, &vars->follow[0].path->points[waypoint]);
        if (FUN_001f9b48(&moby->pos, &point) < 0.5f) {
            vars->follow[0].point = waypoint;
        }
        subtract_vector_xyz(&step, &point, &moby->pos);
        if (vector_length_xyz(&step) > D_L08_00161C38 * frame_time) {
            normalize_vector_xyz(&step, &step, D_L08_00161C38 * frame_time);
        }
        add_vector_xyz(&moby->pos, &moby->pos, &step);
        if (moby->unkBC == 0) {
            break;
        }
        moby->unkBC = 0;
        if (random_integer_below(0xFF) & 1) {
            FUN_L00_0024f7c8(vars->links[3].part, 1, &muzzle);
        } else {
            FUN_L00_0024f7c8(vars->links[4].part, 1, &muzzle);
        }
        pitch = random_float_between(0.17453292f, 0.5235988f);
        yaw = fast_add_rotations(FUN_001f9e90(target->pos.x - moby->pos.x, target->pos.y - moby->pos.y),
                                 3.1415927f);
        yaw = fast_add_rotations(yaw, random_float_between(-0.2617994f, 0.7853982f));
        if (yaw > 0.0f && yaw < 0.34f) {
            yaw = 0.34f;
        } else if (yaw <= 0.0f && yaw > -0.34f) {
            yaw = -0.34f;
        }
        normalize_vector_xyz(&velocity, &step, (D_L08_00161C38 + D_L08_00161C38) * frame_time);
        shot = FUN_L08_002de3e0(&muzzle, target, &velocity, pitch, yaw);
        shot->scale = shot->pclass->scale / 5.0f;
        target_vars = (SwarmTargetVars *)target->pvars;
        for (slot = 0; slot < 8; slot++) {
            if (target_vars->shots[slot] == NULL) {
                target_vars->shots[slot] = shot;
                break;
            }
        }
        break;
    case 2:
        follower = &vars->follow[1];
        next = (follower->point + 1) % follower->path->count;
        after = (follower->point + 2) % follower->path->count;
        heading = FUN_001f9e90(follower->path->points[next].f[0] - follower->path->points[follower->point].f[0],
                               follower->path->points[next].f[1] - follower->path->points[follower->point].f[1]);
        next_heading = FUN_001f9e90(follower->path->points[after].f[0] - follower->path->points[next].f[0],
                                    follower->path->points[after].f[1] - follower->path->points[next].f[1]);
        turn = fast_subtract_rotations(heading, next_heading);
        distance = FUN_001f9b48(&moby->pos, &follower->path->points[next]);
        distance /= FUN_001f9b48(&follower->path->points[follower->point],
                                 &follower->path->points[next]);
        /* the blended heading is computed but unused: the turn below steers towards the next point */
        fast_add_rotations(turn * distance, next_heading);
        heading = FUN_001f9e90(follower->path->points[next].f[0] - moby->pos.x,
                               follower->path->points[next].f[1] - moby->pos.y);
        FUN_L00_0025be00(&moby->rot.z, &vars->turn_speed, heading,
                         D_L08_00161C44 * DEG_TO_RAD * frame_time_sq, D_L08_00161C44 * DEG_TO_RAD * frame_time_sq,
                         D_L08_00161C48 * DEG_TO_RAD * frame_time);
        qcopy(&point, &follower->path->points[next]);
        if (FUN_001f9b48(&moby->pos, &point) < 0.5f) {
            follower->point = next;
        }
        subtract_vector_xyz(&step, &point, &moby->pos);
        if (vector_length_xyz(&step) > D_L08_00161C38 * frame_time) {
            normalize_vector_xyz(&step, &step, D_L08_00161C38 * frame_time);
        }
        add_vector_xyz(&moby->pos, &moby->pos, &step);
        FUN_L08_002e2078(moby);
        if (!tick_countdown_32_alt(&vars->fire_timer)) {
            break;
        }
        vars->fire_timer = truncate_float_to_s32(FUN_001f96b0(random_float_between(300.0f, 600.0f)));
        FUN_L00_0024f7c8(vars->links[4].part, 1, &muzzle);
        pitch = random_float_between(-0.5235988f, -0.2617994f);
        yaw = random_angle_radians();
        normalize_vector_xyz(&velocity, &step, (D_L08_00161C38 + D_L08_00161C38) * frame_time);
        bolt = FUN_L08_002de3e0(&muzzle, NULL, &velocity, pitch, yaw);
        if (bolt != NULL) {
            bolt->rot.z = vars->links[4].part->rot.z;
            bolt->state = 5;
            bolt->rot.y = 0.0f;
        }
        break;
    case 3: {
        SwarmPath *path;

        moby->state = 1;
        path = vars->follow[0].path;
        qcopy(&moby->pos, &path->points[0]);
        moby->rot.z = FUN_001f9e90(path->points[1].f[0] - moby->pos.x, path->points[1].f[1] - moby->pos.y);
        moby->rot.x = 0.0f;
        FUN_L08_002e2078(moby);
        break;
    }
    case 0x63:
        for (i = 1; i < 34; i++) {
            struct Moby *part = vars->links[i].part;
            if (part != NULL) {
                Vec4 *drift = (Vec4 *)part->pvars;
                FUN_L00_0025f090(moby, &part->pos, -1, 3.0f, 13.0f);
                subtract_vector_xyz(drift, &part->pos, &moby->pos);
                normalize_vector_xyz(drift, drift, frame_time * 5.0f);
                part->state = 1;
                vars->links[i].part = NULL;
            }
        }
        FUN_L00_0025f090(moby, &moby->pos, -1, 5.0f, 13.0f);
        mark_moby_for_removal(moby);
        break;
    }
}
#include "sda.h"

/* updates matching objects in the selected object range */
/* Ported from rac1-decomp (src/overlays/l08_batalia/vendor_002E0258.c: func_L08_002E4118), where it is exact; names translated to the US level program. */

extern char *D_L08_0015FFD8;

void FUN_L08_002e2da0(struct Moby *moby) {
    char *data = (char *)moby->pvars;
    int oclass = 0x279;
    char *base = D_L08_0015FFD8;
    int *ids = (int *)(data + 0x130);
    char **output = (char **)(data + 0x158);
    int i = 9;
    for (;;) {
        char *other = (char *)((*ids << 8) + (unsigned int)base);
        if (*(short *)(other + 0xA6) == oclass) {
            *output++ = other;
        }
        --i;
        if (i < 0)
            return;
        ++ids;
    }
}
INCLUDE_ASM("config/us/overlays/asm/FUN_L08_002e2df0.s", FUN_L08_002e2df0);
INCLUDE_ASM("config/us/overlays/asm/FUN_L08_002e3870.s", FUN_L08_002e3870);



#include "qcopy.h"

/* aims a turret: builds its barrel frame from the base rotation, yaw and pitch, writes the barrel rotation
 * and the muzzle point (offset per turret class) */
/* Ported from rac1-decomp (src/overlays/l08_batalia/vendor_002E0258.c: func_L08_002E6208), where it is exact; names translated to the US level program. */

extern f32 fast_cos(f32) __asm__("func_001F9DC8");
extern f32 fast_sin(f32) __asm__("func_001F9DE0");
extern short D_L08_00161C64 __attribute__((sda));
extern short D_L08_00161C7C __attribute__((sda));
extern short D_L08_00161C80 __attribute__((sda));
extern short D_L08_00161C78 __attribute__((sda));
extern short D_L08_00161CB8 __attribute__((sda));
extern short D_L08_00161CBC __attribute__((sda));
extern short D_L08_00161C84 __attribute__((sda));
extern short D_L08_00161C68 __attribute__((sda));
extern short D_L08_00161C6C __attribute__((sda));
extern short D_L08_00161CB4 __attribute__((sda));
extern short D_L08_00161C70 __attribute__((sda));
extern short D_L08_00161C74 __attribute__((sda));
extern void FUN_001fa050(float *, float *);
extern void FUN_00214598(void *, void *);
extern void add_vector_xyz(void *, void *, void *) __asm__("FUN_001f9a10");
extern void clear_u64_value(void *) __asm__("func_001F99F8");
extern void cross_vectors_xyz(void *, void *, void *) __asm__("func_001F9AD8");
extern void normalize_vector_xyz(void *, void *, f32) __asm__("FUN_001f9bf8");

void FUN_L08_002e4e90(struct Moby *moby, float *out, float *rot) {
    float r[16];
    float b[16];
    float up[4];
    float side[4];
    float fwd[4];
    float dir[4];
    float u[4];
    float v[4];
    char *data = (char *)moby->pvars;
    float sx, sy, sz;
    float t;
    switch (moby->oclass) {
    case 0x3DC:
        sx = *(float *)&D_L08_00161C68 * *(float *)&D_L08_00161CB8;
        sy = *(float *)&D_L08_00161C74 * *(float *)&D_L08_00161CB8;
        sz = *(float *)&D_L08_00161C80 * *(float *)&D_L08_00161CB8;
        break;
    case 0x3DD:
        sx = *(float *)&D_L08_00161C6C * *(float *)&D_L08_00161CBC;
        sy = *(float *)&D_L08_00161C78 * *(float *)&D_L08_00161CBC;
        sz = *(float *)&D_L08_00161C84 * *(float *)&D_L08_00161CBC;
        break;
    default:
        sx = *(float *)&D_L08_00161C64 * *(float *)&D_L08_00161CB4;
        sy = *(float *)&D_L08_00161C70 * *(float *)&D_L08_00161CB4;
        sz = *(float *)&D_L08_00161C7C * *(float *)&D_L08_00161CB4;
        break;
    }
    FUN_001fa050(b, (float *)(data + 0x10));
    normalize_vector_xyz(u, b, -fast_sin(*(float *)(data + 0x60)));
    normalize_vector_xyz(v, b + 4, fast_cos(*(float *)(data + 0x60)));
    add_vector_xyz(dir, u, v);
    t = sx * DEG_TO_RAD;
    normalize_vector_xyz(u, dir, fast_cos(t));
    normalize_vector_xyz(v, b + 8, fast_sin(t));
    add_vector_xyz(up, u, v);
    normalize_vector_xyz(u, b, -fast_cos(*(float *)(data + 0x60)));
    normalize_vector_xyz(v, b + 4, -fast_sin(*(float *)(data + 0x60)));
    add_vector_xyz(fwd, u, v);
    cross_vectors_xyz(side, up, fwd);
    normalize_vector_xyz(u, side, fast_cos(*(float *)(data + 0x64)));
    normalize_vector_xyz(v, fwd, fast_sin(*(float *)(data + 0x64)));
    add_vector_xyz(r, u, v);
    normalize_vector_xyz(u, side, -fast_sin(*(float *)(data + 0x64)));
    normalize_vector_xyz(v, fwd, fast_cos(*(float *)(data + 0x64)));
    add_vector_xyz(r + 4, u, v);
    qcopy(r + 8, up);
    r[11] = 0.0f;
    clear_u64_value(r + 12);
    r[15] = 1.0f;
    FUN_00214598(r, rot);
    rot[3] = 0.0f;
    normalize_vector_xyz(u, b + 8, sy);
    add_vector_xyz(out, data, u);
    normalize_vector_xyz(v, dir, sz);
    add_vector_xyz(out, out, v);
}
INCLUDE_ASM("config/us/overlays/asm/FUN_L08_002e5188.s", FUN_L08_002e5188);
/* Ported from rac1-decomp (src/overlays/l08_batalia/vendor_002E0258.c: func_L08_002E9CB0), where it is exact; names translated to the US level program. */

typedef struct Moby Moby;

extern f32 random_float_between_c(f32, f32) __asm__("func_002132A8");
extern float D_0015ED6C;
extern s32 allocate_voice_for_target_entry_alt(s32, s32, struct Moby *) __asm__("FUN_0022da68");
extern s32 truncate_float_to_s32_c(f32) __asm__("func_001FA6D0");
extern void *FUN_L00_0025a420(void *, int, int);
extern void func_0022ED80_2E9CB0(int, int, int) __asm__("FUN_0022da68");

void FUN_L08_002e88d8(char *m) {
    char *data = *(char **)(m + 0x78);
    char *base = data + 0x60;
    char **p = (char **)base;
    char **sq;
    int n = 0;
    int idx = 0;
    int r = -1;
    int i;
    for (i = 0; i < 13; i++, p += 4) {
        if (*p != 0) {
            if (FUN_L00_0025a420(*p, 0x10000, 0) != 0) {
                if (i < 3) {
                    if (n <= 0) { n = 1; r = 1; }
                } else if (i < 5) {
                    if (n < 2) { n = 2; r = 1; }
                } else {
                    if (n < 4) { n += 4; idx = i; r = 2; }
                }
                ((unsigned char *)*p)[0xA4] = 0xFF;
            }
        }
    }
    *(unsigned short *)(data + 0x13C) += n;
    if (*(short *)(data + 0x13C) >= 8) {
        *(short *)(data + 0x13C) = *(short *)(data + 0x13C) % 8;
        if (idx != 0) {
            int o1 = idx * 16;
            char **q = (char **)(base + o1);
            char *t = *q;
            char *d2;
            d2 = *(char **)(t + 0x78);
            FUN_L00_0025f090(m, t + 0x10, -1, 2.0f, 13.0f);
            subtract_vector_xyz(d2, *q + 0x10, *(char **)(o1 + data + 0x64) + 0x10);
            normalize_vector_xyz(d2, d2, D_0015ED6C * 10.0f);
            (*q)[0x20] = 1;
            *q = 0;
            return;
        } else {
            int s = truncate_float_to_s32_c(random_float_between_c(0.0f, 23.0f));
                        char *b2 = base;
            for (i = 0; i < 8; i++) {
                int k = (i + s) % 8 + 5;
                int off = k * 16;
                base = b2 + off; sq = (char **)base;
                if (*sq != 0) {
                    char *d2 = *(char **)(*sq + 0x78);
                    FUN_L00_0025f090(m, *sq + 0x10, -1, 2.0f, 13.0f);
                    subtract_vector_xyz(d2, *sq + 0x10, *(char **)(data + off + 0x64) + 0x10);
                    normalize_vector_xyz(d2, d2, D_0015ED6C * 10.0f);
                    (*sq)[0x20] = 1;
                    *sq = 0;
                    return;
                }
            }
            m[0x20] = 0x63;
        }
    }
    if (r >= 0) func_0022ED80_2E9CB0(r, 0, (int)m);
}
/* Flying gunship: cruises one path and fires at its target, or circles a second path and fires at random. */
/* Child moby slot, as FUN_L08_002e8788 fills them. */
typedef struct {
    struct Moby *moby;
    struct Moby *parent;
    s32 joint;
    s32 parent_joint;
} SwarmPart;

typedef struct {
    SwarmPathFollower follow[2]; /* 0x00: [0] cruising (state 1), [1] circling (state 2) */
    SwarmPart root;              /* 0x60 */
    SwarmPart parts[12];         /* 0x70 */
    s32 target_index;            /* 0x130: moby slot of the target */
    f32 turn_speed;              /* 0x134 */
    s16 can_skip;                /* 0x138: non-zero lets the circling jump ahead (see state 2) */
    s16 fire_timer;              /* 0x13A */
    s16 pad13C;
    s16 sound;                   /* 0x13E */
} SwarmVars;

extern s32 D_L08_00161D30 __attribute__((sda));
extern f32 D_L08_00161D24 __attribute__((sda));
extern s32 D_L08_0015F5C4;
extern s64 D_L08_0016D090 __attribute__((section(".data")));
extern u8 D_0014C050[];
extern SwarmPath *D_L08_001B0CB0[];
extern struct Moby *D_L08_0015FFD8_m __asm__("D_L08_0015FFD8");

extern s32 FUN_L00_0028d8c0(struct Moby *, s32);
extern s32 allocate_voice_for_target_entry(s32, s32, struct Moby *) __asm__("FUN_0022da68");
extern void mark_moby_for_removal(void *) __asm__("FUN_0020c828");
extern f32 random_float_between(f32, f32) __asm__("FUN_002132a8");
extern f32 random_angle_radians(void) __asm__("FUN_00213308");
extern f32 FUN_001f96b0(f32);
extern s32 truncate_float_to_s32(f32) __asm__("FUN_001fa6d0");
extern f32 fast_add_rotations(f32, f32) __asm__("FUN_001fa580");
extern f32 fast_subtract_rotations(f32, f32) __asm__("FUN_001fa5c8");
extern s32 FUN_001f9770(s16 *);
extern f32 FUN_001f9b48(void *, void *);
extern f32 vector_length_xyz(void *) __asm__("FUN_001f9af0");
extern void normalize_vector_xyz(void *, void *, f32) __asm__("FUN_001f9bf8");
extern void add_vector_xyz(void *, void *, void *) __asm__("FUN_001f9a10");
extern void subtract_vector_xyz(void *, void *, void *) __asm__("FUN_001f9a28");
extern void FUN_L00_0024f7c8(void *, int, void *);
extern void FUN_L00_00258278(struct Moby *, f32, f32 *, f32, f32, f32);
extern void FUN_L00_0025f090(void *, void *, s32, f32, f32);
extern struct Moby *FUN_L08_002de3e0(void *, struct Moby *, void *, f32, f32);
extern void FUN_L08_002e8788(char *);
extern void FUN_L08_002e88d8_u(struct Moby *) __asm__("FUN_L08_002e88d8");
extern void FUN_L08_002e8ba0(struct Moby *);

void FUN_L08_002e8cd0(struct Moby *moby) {
    SwarmVars *vars = (SwarmVars *)moby->pvars;
    SwarmPathFollower *follower;
    struct Moby *target;
    struct Moby *shot;
    struct Moby *bolt;
    SwarmTargetVars *target_vars;
    Vec4 point;
    Vec4 step;
    Vec4 muzzle;
    Vec4 velocity;
    s32 waypoint;
    s32 next;
    s32 after;
    s32 i;
    s32 slot;
    f32 distance;
    f32 heading;
    f32 next_heading;
    f32 turn;
    f32 pitch;
    f32 yaw;

    if (D_L08_00161D30 != 0) {
        return;
    }
    if (!FUN_L00_0028d8c0(moby, vars->sound)) {
        vars->sound = allocate_voice_for_target_entry(3, 4, moby);
    }
    switch (moby->state) {
    case 0:
        if (D_0014C050[moby->unkB0 + current_level_index * 16] == 0xFF) {
            mark_moby_for_removal(moby);
            return;
        }
        vars->follow[0].path = D_L08_001B0CB0[vars->follow[0].path_id];
        vars->follow[1].path = D_L08_001B0CB0[vars->follow[1].path_id];
        vars->fire_timer = truncate_float_to_s32(FUN_001f96b0(random_float_between(300.0f, 600.0f)));
        moby->flags |= 0x4000;
        qcopy(&moby->pos, &vars->follow[1].path->points[0]);
        FUN_L08_002e8788((char *)moby);
        moby->state = 2;
        moby->rot.z = FUN_001f9e90(vars->follow[1].path->points[1].f[0] - moby->pos.x,
                                   vars->follow[1].path->points[1].f[1] - moby->pos.y);
        break;
    case 1:
        waypoint = (vars->follow[0].point + vars->follow[0].path->count + vars->follow[0].direction) % vars->follow[0].path->count;
        target = &D_L08_0015FFD8_m[vars->target_index];
        FUN_L00_00258278(moby,
                         FUN_001f9e90(vars->follow[0].path->points[waypoint].f[0] - moby->pos.x,
                                      vars->follow[0].path->points[waypoint].f[1] - moby->pos.y),
                         &vars->turn_speed, 0.004f, 0.3f, 0.02f);
        FUN_L08_002e88d8_u(moby);
        FUN_L08_002e8ba0((char *)moby);
        qcopy(&point, &vars->follow[0].path->points[waypoint]);
        if (FUN_001f9b48(&moby->pos, &point) < 0.5f) {
            vars->follow[0].point = waypoint;
        }
        subtract_vector_xyz(&step, &point, &moby->pos);
        if (vector_length_xyz(&step) > D_L08_00161D24 * frame_time) {
            normalize_vector_xyz(&step, &step, D_L08_00161D24 * frame_time);
        }
        add_vector_xyz(&moby->pos, &moby->pos, &step);
        if (moby->unkBC == 0) {
            break;
        }
        moby->unkBC = 0;
        FUN_L00_0024f7c8(vars->parts[3].moby, 1, &muzzle);
        pitch = random_float_between(0.17453292f, 0.5235988f);
        yaw = fast_add_rotations(FUN_001f9e90(target->pos.x - moby->pos.x, target->pos.y - moby->pos.y),
                                 3.1415927f);
        yaw = fast_add_rotations(yaw, random_float_between(-0.2617994f, 0.7853982f));
        if (yaw > 0.0f && yaw < 0.34f) {
            yaw = 0.34f;
        } else if (yaw <= 0.0f && yaw > -0.34f) {
            yaw = -0.34f;
        }
        normalize_vector_xyz(&velocity, &step, (D_L08_00161D24 + D_L08_00161D24) * frame_time);
        shot = FUN_L08_002de3e0(&muzzle, target, &velocity, pitch, yaw);
        shot->scale = shot->pclass->scale / 5.0f;
        target_vars = (SwarmTargetVars *)target->pvars;
        for (slot = 0; slot < 8; slot++) {
            if (target_vars->shots[slot] == NULL) {
                target_vars->shots[slot] = shot;
                break;
            }
        }
        break;
    case 2:
        follower = &vars->follow[1];
        if (D_L08_0015F5C4 == 2 && vars->can_skip != 0 && D_L08_0016D090 == 0x200000000) {
            qcopy(&moby->pos, &follower->path->points[15]);
            follower->point = 15;
            moby->rot.z = FUN_001f9e90(follower->path->points[11].f[0] - moby->pos.x,
                                       follower->path->points[11].f[1] - moby->pos.y);
        }
        next = (follower->point + 1) % follower->path->count;
        after = (follower->point + 2) % follower->path->count;
        heading = FUN_001f9e90(follower->path->points[next].f[0] - follower->path->points[follower->point].f[0],
                               follower->path->points[next].f[1] - follower->path->points[follower->point].f[1]);
        next_heading = FUN_001f9e90(follower->path->points[after].f[0] - follower->path->points[next].f[0],
                                    follower->path->points[after].f[1] - follower->path->points[next].f[1]);
        turn = fast_subtract_rotations(heading, next_heading);
        distance = FUN_001f9b48(&moby->pos, &follower->path->points[next]);
        distance /= FUN_001f9b48(&follower->path->points[follower->point],
                                 &follower->path->points[next]);
        moby->rot.z = fast_add_rotations(turn * distance, next_heading);
        qcopy(&point, &follower->path->points[next]);
        if (FUN_001f9b48(&moby->pos, &point) < 0.5f) {
            follower->point = next;
        }
        subtract_vector_xyz(&step, &point, &moby->pos);
        if (vector_length_xyz(&step) > D_L08_00161D24 * frame_time) {
            normalize_vector_xyz(&step, &step, D_L08_00161D24 * frame_time);
        }
        add_vector_xyz(&moby->pos, &moby->pos, &step);
        FUN_L08_002e8ba0((char *)moby);
        if (!FUN_001f9770(&vars->fire_timer)) {
            break;
        }
        vars->fire_timer = truncate_float_to_s32(FUN_001f96b0(random_float_between(300.0f, 600.0f)));
        FUN_L00_0024f7c8(vars->parts[3].moby, 1, &muzzle);
        pitch = random_float_between(-0.5235988f, -0.2617994f);
        yaw = random_angle_radians();
        normalize_vector_xyz(&velocity, &step, (D_L08_00161D24 + D_L08_00161D24) * frame_time);
        bolt = FUN_L08_002de3e0(&muzzle, NULL, &velocity, pitch, yaw);
        if (bolt != NULL) {
            bolt->rot.z = vars->parts[3].moby->rot.z;
            bolt->state = 5;
            bolt->rot.y = 0.0f;
        }
        break;
    case 3: {
        SwarmPath *path;

        moby->state = 1;
        path = vars->follow[0].path;
        qcopy(&moby->pos, &path->points[0]);
        moby->rot.z = FUN_001f9e90(path->points[1].f[0] - moby->pos.x, path->points[1].f[1] - moby->pos.y);
        FUN_L08_002e8ba0((char *)moby);
        break;
    }
    case 0x63:
        for (i = 0; i < 12; i++) {
            struct Moby *part = vars->parts[i].moby;
            if (part != NULL) {
                Vec4 *drift = (Vec4 *)part->pvars;
                FUN_L00_0025f090(moby, &part->pos, -1, 3.0f, 13.0f);
                subtract_vector_xyz(drift, &part->pos, &moby->pos);
                normalize_vector_xyz(drift, drift, frame_time * 5.0f);
                part->state = 1;
                vars->parts[i].moby = NULL;
            }
        }
        FUN_L00_0025f090(moby, &moby->pos, -1, 5.0f, 13.0f);
        mark_moby_for_removal(moby);
        break;
    }
}
/* Builds the moby's part hierarchy: body, head, arms and eight trailing segments. */
/* Ported from rac1-decomp (src/overlays/l08_batalia/vendor_002E0258.c: func_L08_002EA930), where it is exact; names translated to the US level program. */

void *FUN_L08_002e1c98_c2(char *parent, int oClass, int joint,
                          int pjoint) __asm__("FUN_L08_002e1c98");

void FUN_L08_002e9558(char *moby) {
    char *data = *(char **)(moby + 0x78);
    char *e = data + 0xFC;
    int i = 0;
    char *c;
    char *c2;
    char *c6;
    char *c8;
    *(char **)(data + 0x60) = moby;
    *(int *)(data + 0x64) = 0;
    *(int *)(data + 0x68) = 0;
    *(int *)(data + 0x6C) = 0;
    *(char **)(data + 0x90) = FUN_L08_002e1c98_c2(moby, 0x1C0, 0, 0);
    *(char **)(data + 0x94) = moby;
    *(int *)(data + 0x98) = 0;
    *(int *)(data + 0x9C) = 0;
    c = FUN_L08_002e1c98_c2(moby, 0x1BD, 0, 2);
    *(char **)(data + 0x70) = c;
    *(int *)(data + 0x7C) = 2;
    *(char **)(data + 0x74) = moby;
    *(int *)(data + 0x78) = 0;
    *(float *)(c + 0x2C) = *(float *)(*(char **)(c + 0x24) + 0x24) * 0.75f;
    c2 = FUN_L08_002e1c98_c2(*(char **)(data + 0x90), 0x1BA, 1, 1);
    *(char **)(data + 0x80) = c2;
    *(char **)(data + 0x84) = *(char **)(data + 0x90);
    *(int *)(data + 0x88) = 1;
    *(int *)(data + 0x8C) = 1;
    *(char **)(data + 0xA0) = FUN_L08_002e1c98_c2(c2, 0x1B9, 0, 0);
    *(char **)(data + 0xA4) = *(char **)(data + 0x80);
    *(int *)(data + 0xA8) = 0;
    *(int *)(data + 0xAC) = 0;
    *(char **)(data + 0xB0) = FUN_L08_002e1c98_c2(moby, 0x1D0, 0, 1);
    *(char **)(data + 0xB4) = moby;
    *(int *)(data + 0xB8) = 0;
    *(int *)(data + 0xBC) = 1;
    c6 = FUN_L08_002e1c98_c2(moby, 0x1D0, 0, 1);
    *(char **)(data + 0xC0) = c6;
    *(char **)(data + 0xC4) = moby;
    *(int *)(data + 0xC8) = 0;
    *(int *)(data + 0xCC) = 1;
    *(unsigned short *)(c6 + 0x34) |= 0x8000;
    *(char **)(data + 0xD0) = FUN_L08_002e1c98_c2(*(char **)(data + 0x80), 0x1D1, 0, 0);
    *(char **)(data + 0xD4) = *(char **)(data + 0x80);
    *(int *)(data + 0xD8) = 0;
    *(int *)(data + 0xDC) = 0;
    c8 = FUN_L08_002e1c98_c2(*(char **)(data + 0x80), 0x1D1, 0, 0);
    *(char **)(data + 0xE0) = c8;
    *(char **)(data + 0xE4) = *(char **)(data + 0x80);
    *(int *)(data + 0xE8) = 0;
    *(int *)(data + 0xEC) = 0;
    *(unsigned short *)(c8 + 0x34) |= 0x8000;
    do {
        int j = i + 2;
        i++;
        *(char **)(e - 0xC) = FUN_L08_002e1c98_c2(*(char **)(data + 0x90), 0x1BB, 0, j);
        *(char **)(e - 8) = *(char **)(data + 0x90);
        *(int *)(e - 4) = 0;
        *(int *)e = j;
        e += 0x10;
    } while (i < 8);
}
#ifndef NON_MATCHING
INCLUDE_ASM("config/us/overlays/asm/FUN_L08_002e9758.s", FUN_L08_002e9758);
#else
extern void FUN_L00_0025f090(void *, void *, s32, f32, f32);
extern void FUN_001f9a28(void *, void *, void *);
extern void normalize_vector_xyz(void *, void *, f32) __asm__("FUN_001f9bf8");
extern f32 random_float_between(f32, f32) __asm__("FUN_002132a8");
extern s32 truncate_float_to_s32(f32) __asm__("FUN_001fa6d0");
extern s32 allocate_voice_for_target_entry(s32, s32, struct Moby *) __asm__("FUN_0022da68");
extern float D_0015ED6C;

void FUN_L08_002e9758(struct Moby *moby) {
    int selected = 0;
    char *data = (char *)moby->pvars;
    SwarmPart *slots = (SwarmPart *)(data + 0x60);
    SwarmPart *slot = slots;
    int i = 0;
    int hits = 0;
    int sound = -1;
    int total;
    u8 mark = 0xff;

    do {
        if (slot->moby != 0) {
            if (FUN_L00_0025a420(slot->moby, 0x10000, 0) != 0) {
                if (i < 3) {
                    if (hits < 1) {
                        hits = 1;
                        sound = 1;
                        goto mark_hit;
                    }
                } else if (i < 9) {
                    if (hits < 2) {
                        hits = 2;
                        sound = 1;
                        goto mark_hit;
                    }
                } else if (hits < 4) {
                    hits += 4;
                    selected = i;
                    sound = 2;
                    goto mark_hit;
                }
mark_hit:
                slot->moby->unkA4 = mark;
            }
        }
        i++;
        slot++;
    } while (i < 17);
    total = (u16)*(s16 *)(data + 0x17c) + hits;
    *(s16 *)(data + 0x17c) = total;
    if ((s16)total >= 12) {
        *(s16 *)(data + 0x17c) = (s16)total % 12;
        if (selected != 0) {
            SwarmPart *chosen = &slots[selected];
            u8 *vector;
            vector = chosen->moby->pvars;
            FUN_L00_0025f090(moby, &chosen->moby->pos, -1, 2.0f, 13.0f);
            FUN_001f9a28(vector, &chosen->moby->pos,
                         &(*(struct Moby **)(selected * 16 + data + 0x64))->pos);
            normalize_vector_xyz(vector, vector, D_0015ED6C * 10.0f);
            chosen->moby->state = 1;
            chosen->moby = 0;
            return;
        }
        {
            int start = truncate_float_to_s32(random_float_between(0.0f, 23.0f));
            i = 0;
            do {
                int index = (start + i) % 8 + 9;
                SwarmPart *candidate = &slots[index];
                i++;
                if (candidate->moby != 0) {
                    u8 *vector = candidate->moby->pvars;
                    FUN_L00_0025f090(moby, &candidate->moby->pos, -1, 2.0f, 13.0f);
                    FUN_001f9a28(vector, &candidate->moby->pos,
                                 &(*(struct Moby **)(data + index * 16 + 0x64))->pos);
                    normalize_vector_xyz(vector, vector, D_0015ED6C * 10.0f);
                    candidate->moby->state = 1;
                    candidate->moby = 0;
                    return;
                }
            } while (i < 8);
            moby->state = 99;
        }
    }
    if (sound >= 0)
        allocate_voice_for_target_entry(sound, 0, moby);
}
#endif /* NON_MATCHING */
