/* Level overlay code after unclassified; generated by `decomp overlays stubs`, stubs replaced by C as functions are matched. */
#include "types.h"
#include "rnc/globals.h"
#include "asm.h"
#include "eetypes.h"
#include "qcopy.h"
#include "rnc/math/vector.h"

#ifndef NON_MATCHING
INCLUDE_ASM("config/us/overlays/asm/FUN_L00_00268900.s", FUN_L00_00268900);
#else
extern void FUN_L00_00268d48();
extern void FUN_L00_00268fe8();
extern void FUN_L00_00269290(void);
extern void FUN_L00_002694f8(void);
extern void FUN_L00_00269a70(void);
extern void FUN_L00_00269c70(void);
extern void FUN_L00_00269d20(void);
extern void FUN_L00_0026a418(void);
extern void FUN_L00_0026a5b8(void);
extern void FUN_L00_0026a6f0(void);
extern void FUN_L00_0026a880(void);
extern void FUN_L00_0026ac78(void);
extern void FUN_L00_0026b500(void);
extern void FUN_L00_0026b910(void);
extern void FUN_L00_0026ba68(void);
extern void FUN_L00_0026bca8(void);
extern void FUN_L00_0026c088(void);
extern void FUN_L00_0026c3c8(void);
extern void FUN_L00_0026c558(void);
extern void FUN_L00_0026c7f0(void);
extern void FUN_L00_0026c860(void);
extern void FUN_L00_0026ccb0(void);
extern void FUN_L00_00267b10(void);
extern void FUN_L00_0026d1b0(void);
extern void FUN_L00_0026d470(void);
extern void FUN_L00_0026d700(void);
extern void FUN_L00_0026dbe0(void);
extern void FUN_L00_0026de00(void);
extern void FUN_L00_0026e150(void);
extern void FUN_L00_0026e3a8(void);
extern void FUN_L00_0026e670(void);
extern void FUN_L00_0026eb88(void);
extern void FUN_L00_0026ee48(void);
extern void FUN_L00_0026f048(void);
extern void FUN_L00_0026f280(void);
extern void FUN_L00_0026f660(void);
extern void FUN_L00_0026f898(void);
extern void FUN_L00_0026fa00(void);
extern void FUN_L00_0026fb00(void);
extern void FUN_L00_0026fc38(void);
extern void FUN_L00_0026ff10(void);
extern void FUN_L00_00270710(void);
extern void FUN_L00_00270948(void);
extern void FUN_L00_002710a0(void);
extern void FUN_L00_00271450(void);
extern void FUN_L00_00271748(void);
extern void FUN_L00_002719f0(void);
extern void FUN_L00_00271be8(void);
extern void FUN_L00_00271c88(void);
extern void FUN_L00_00271d20(void);
extern void FUN_L00_00271df8(void);
extern void FUN_L00_00271ec8(void);
extern void FUN_L00_00271fc0(void);
extern void FUN_L00_002721f0(void);
extern void FUN_L00_00272438(void);
extern void FUN_L00_002726d8(void);
extern void FUN_L00_00272838(void);
extern void FUN_L00_002728e8(void);
extern void FUN_L00_00272bc0(void);
extern void FUN_L00_00273088(void);
extern void FUN_L00_00273298(void);
extern void FUN_L00_00273448(void);
extern void FUN_L00_00273800(void);
extern void FUN_L00_00273a68(void);
extern void FUN_L00_002738b0(void);
extern void FUN_L00_00273ee0(void);
extern void FUN_L00_00274308(void);
extern void FUN_L00_00274518(void);
extern void FUN_L00_00274818(void);
extern void FUN_L00_00274a70(void);
extern void FUN_L00_00274de0(void);
extern void FUN_L00_00274e48(void);
extern void FUN_L00_002752e0(void);
extern void FUN_L00_00275320(void);
extern void FUN_L00_00275510(void);
extern void FUN_L00_002756f0(void);
extern void FUN_L00_00275810(void);
extern void FUN_L00_00275860(void);
extern void FUN_L00_00275aa0(void);
extern void FUN_L00_00275d68(void);
extern void FUN_L00_00275eb0(void);

extern u32 effect_handlers[] __asm__("D_L00_001B1E80");

void FUN_L00_00268900(void)
{
    u32 *handlers = effect_handlers;
    handlers[0] = (u32)FUN_L00_00268d48;
    handlers[1] = (u32)FUN_L00_00268fe8;
    handlers[2] = (u32)FUN_L00_00269290;
    handlers[3] = (u32)FUN_L00_002694f8;
    handlers[4] = (u32)FUN_L00_00269a70;
    handlers[5] = (u32)FUN_L00_00269c70;
    handlers[7] = (u32)FUN_L00_0026a418;
    handlers[13] = (u32)FUN_L00_0026b910;
    handlers[14] = (u32)FUN_L00_0026ba68;
    handlers[15] = (u32)FUN_L00_0026bca8;
    handlers[16] = (u32)FUN_L00_0026c088;
    handlers[17] = (u32)FUN_L00_0026c3c8;
    handlers[18] = (u32)FUN_L00_0026c558;
    handlers[19] = (u32)FUN_L00_0026c7f0;
    handlers[20] = (u32)FUN_L00_0026c860;
    handlers[22] = (u32)FUN_L00_00267b10;
    handlers[6] = (u32)FUN_L00_00269d20;
    handlers[8] = (u32)FUN_L00_0026a5b8;
    handlers[9] = (u32)FUN_L00_0026a6f0;
    handlers[10] = (u32)FUN_L00_0026a880;
    handlers[11] = (u32)FUN_L00_0026ac78;
    handlers[12] = (u32)FUN_L00_0026b500;
    handlers[21] = (u32)FUN_L00_0026ccb0;
    handlers[23] = (u32)FUN_L00_0026d1b0;
    handlers[24] = (u32)FUN_L00_0026d470;
    handlers[25] = (u32)FUN_L00_0026d700;
    handlers[26] = (u32)FUN_L00_0026dbe0;
    handlers[27] = (u32)FUN_L00_0026de00;
    handlers[28] = (u32)FUN_L00_0026e150;
    handlers[29] = (u32)FUN_L00_0026e3a8;
    handlers[30] = (u32)FUN_L00_0026e670;
    handlers[31] = (u32)FUN_L00_0026eb88;
    handlers[32] = (u32)FUN_L00_0026ee48;
    handlers[33] = (u32)FUN_L00_0026f048;
    handlers[34] = (u32)FUN_L00_0026f280;
    handlers[35] = (u32)FUN_L00_0026f660;
    handlers[42] = (u32)FUN_L00_00270948;
    handlers[44] = (u32)FUN_L00_00271450;
    handlers[45] = (u32)FUN_L00_00271748;
    handlers[47] = (u32)FUN_L00_00271be8;
    handlers[48] = (u32)FUN_L00_00271c88;
    handlers[49] = (u32)FUN_L00_00271d20;
    handlers[50] = (u32)FUN_L00_00271df8;
    handlers[51] = (u32)FUN_L00_00271ec8;
    handlers[52] = (u32)FUN_L00_00271fc0;
    handlers[53] = (u32)FUN_L00_002721f0;
    handlers[54] = (u32)FUN_L00_00272438;
    handlers[55] = (u32)FUN_L00_002726d8;
    handlers[36] = (u32)FUN_L00_0026f898;
    handlers[37] = (u32)FUN_L00_0026fa00;
    handlers[38] = (u32)FUN_L00_0026fb00;
    handlers[39] = (u32)FUN_L00_0026fc38;
    handlers[40] = (u32)FUN_L00_0026ff10;
    handlers[41] = (u32)FUN_L00_00270710;
    handlers[43] = (u32)FUN_L00_002710a0;
    handlers[46] = (u32)FUN_L00_002719f0;
    handlers[56] = (u32)FUN_L00_00272838;
    handlers[57] = (u32)FUN_L00_002728e8;
    handlers[58] = (u32)FUN_L00_00272bc0;
    handlers[60] = (u32)FUN_L00_00273298;
    handlers[61] = (u32)FUN_L00_00273448;
    handlers[62] = (u32)FUN_L00_00273800;
    handlers[63] = (u32)FUN_L00_002738b0;
    handlers[64] = (u32)FUN_L00_00273a68;
    handlers[59] = (u32)FUN_L00_00273088;
    handlers[65] = (u32)FUN_L00_00273ee0;
    handlers[66] = (u32)FUN_L00_00274308;
    handlers[67] = (u32)FUN_L00_00274518;
    handlers[68] = (u32)FUN_L00_00274818;
    handlers[69] = (u32)FUN_L00_00274a70;
    handlers[70] = (u32)FUN_L00_00274de0;
    handlers[71] = (u32)FUN_L00_00274e48;
    handlers[72] = (u32)FUN_L00_002752e0;
    handlers[73] = (u32)FUN_L00_00275320;
    handlers[74] = (u32)FUN_L00_00275510;
    handlers[75] = (u32)FUN_L00_002756f0;
    handlers[76] = (u32)FUN_L00_00275810;
    handlers[77] = (u32)FUN_L00_00275860;
    handlers[78] = (u32)FUN_L00_00275aa0;
    handlers[80] = (u32)FUN_L00_00275eb0;
    handlers[79] = (u32)FUN_L00_00275d68;
}
#endif
/*
 * Falling effect particle (one kind of the pool behind FUN_L00_002678b8; its
 * slot is freed by FUN_L00_00267a08). Each frame both points move by the
 * velocity plus a global drift, gravity pulls the velocity down, and the
 * particle dies when it leaves the 512 x 512 map or drops below the ground.
 * The ground height is sampled again only when the probe enters a new
 * 1 x 1 cell, and cached in vel.w.
 */
typedef struct {
    u8 pad_00[0xA];
    s16 unk0A;                     /* 2 skips the ground test (a timer in sibling kinds) */
    u8 pad_0C[4];
    Vec4 pos;                      /* 0x10: drawn position */
    Vec4 probe;                    /* 0x20: point tested against the ground */
    Vec4 vel;                      /* 0x30: w = ground height + clearance */
} FallingParticle;

/* .sdata placement is load-bearing */
extern Vec4 particle_drift __asm__("D_L00_00160250") __attribute__((section(".sdata")));
typedef struct {
    f32 value;
} ParticleClearance;
/* read through a one-field struct: a plain f32 changes the addressing */
extern ParticleClearance particle_clearance __asm__("D_L00_00160258");
extern f32 particle_min_ground __asm__("D_L00_00160260");
extern void add_vector_xyz(void *, void *, void *) __asm__("FUN_001f9a10");
extern f32 ground_height_at(Vec4 *) __asm__("FUN_L00_00263468");
extern void free_effect_particle(FallingParticle *) __asm__("FUN_L00_00267a08");

void FUN_L00_00268d48(FallingParticle *p)
{
    Vec4 step;
    Vec4 tmp1;
    Vec4 tmp2;
    Vec4 *vel = &p->vel;
    f32 ground = vel->f[3];
    s32 cell_x;
    s32 cell_y;

    if (p->pos.f[2] < ground || p->pos.f[0] < 0.0f || p->pos.f[1] < 0.0f
        || 512.0f < p->pos.f[0] || 512.0f < p->pos.f[1])
        goto die;

    cell_x = p->probe.f[0];
    cell_y = p->probe.f[1];
    add_vector_xyz(&step, vel, &particle_drift);
    add_vector_xyz(&p->probe, &p->probe, &step);
    add_vector_xyz(&p->pos, &p->pos, &step);
    if (p->unk0A != 2) {
        if (cell_x != (s32)p->probe.f[0] || cell_y != (s32)p->probe.f[1]) {
            tmp1.q = p->probe.q;
            if (ground_height_at(&tmp1) < particle_min_ground) {
                ground = particle_min_ground;
            } else {
                tmp2.q = p->probe.q;
                ground = ground_height_at(&tmp2);
            }
            if (p->probe.f[2] < ground) {
                /* shared exit; retail has one call site for all kill paths */
            die:
                free_effect_particle(p);
                return;
            }
        }
    }
    vel->f[2] -= frame_time_sq * 9.8f;
    vel->f[3] = ground + particle_clearance.value;
}
extern unsigned char *D_L00_001B2084 __attribute__((section(".data")));
unsigned char *FUN_L00_002678b8(int);
int truncate_float_to_s32(float) __asm__("FUN_001fa6d0");
int scale_game_frames(int) __asm__("FUN_001f96f8");
void FUN_L00_00268f10(Vec4 *v, int c) {
    unsigned char *m = FUN_L00_002678b8(1);
    if (m) {
        v->f[2] += 0.1f;
        qcopy(m + 0x10, v);
        *(int *)(m + 4) = (c << 24) | 0x907070;
        m[9] = truncate_float_to_s32(2.0f) + 0x40;
        m[3] = 0x48;
        m[1] = 0;
        m[2] = *D_L00_001B2084;
        *(float *)(m + 0xc) = 31500.002f;
        m[8] = 0xa0;
        *(short *)(m + 0xa) = scale_game_frames(0x1b);
        *(int *)(m + 0x20) = c;
    }
}
int scale_game_frames(int) __asm__("FUN_001f96f8");
int FUN_001f9770(void *);
void FUN_L00_00267a08(unsigned char *);
void FUN_L00_00268fe8(unsigned char *p) {
    int r = scale_game_frames(0x1b);
    int k = *(short *)(p + 0xa) * *(int *)(p + 0x20) / r;
    *(int *)(p + 4) = (*(int *)(p + 4) & 0xffffff) | (k << 24);
    if (FUN_001f9770(p + 0xa))
        FUN_L00_00267a08(p);
    else {
        int a = scale_game_frames(0x1b);
        int b = scale_game_frames(0x1b);
        p[2] = D_L00_001B2084[(a - *(short *)(p + 0xa)) * 9 / b];
    }
}
