/* Level overlay code after gameplay/state; generated by `decomp overlays stubs`, stubs replaced by C as functions are matched. */
#include "types.h"
#include "asm.h"

#include "qcopy.h"
typedef struct {
    float m[16];
} __attribute__((aligned(16))) Mtx;
typedef struct {
    float x, y, z, w;
} __attribute__((aligned(16))) Vec4;
typedef struct {
    float a;
    float b;
    float pad[2];
    Vec4 v;
} Ent32;
typedef struct {
    char h[0x10];
    Ent32 e[1];
} Tbl;
void FUN_001fa2d8(Mtx *, void *);
void FUN_001f9a28(Vec4 *, void *, void *);
void FUN_001f9d20(Vec4 *, Vec4 *, Mtx *);
void FUN_001f9a68(Vec4 *, Vec4 *, float);
void FUN_L00_0024eed8(char *p, int idx, void *v, float a, float b) {
    Mtx m;
    Vec4 t;
    Ent32 *e = &(*(Tbl **)(p + 0x94))->e[idx];
    float k = 1024.0f / *(float *)(p + 0x2C);
    FUN_001fa2d8(&m, p + 0xC0);
    FUN_001f9a28(&t, v, p + 0x10);
    FUN_001f9d20(&t, &t, &m);
    FUN_001f9a68(&t, &t, k);
    qcopy(&e->v, &t);
    e->b = b * k;
    e->v.w = a * k;
}
#define NOT_SDA

#define MACRO_ADDR

/* Ported from rac1-decomp (src/overlays/shared/mobyfunc_0024FD50.c: func_L00_0024FFE8), where it is exact; names translated to the US level program. */

/* Offsets the point pairs of each of the a[4] + a[5] entries by dx, dy. */
void FUN_L00_0024efb0(unsigned char *a, int dx, int dy) {
    int i;
    int n = a[4] + a[5];
    int *t = *(int **)a;
    for (i = 0; i < n; i++, t += 4) {
        unsigned short *e = *(unsigned short **)t;
        int c = ((unsigned char *)e)[2];
        int cnt;
        e += 2;
        if (c != 0) {
            cnt = c;
            do {
                e[0] = e[0] + dx;
                e[1] = e[1] + dy;
                e += 2;
                cnt--;
            } while (cnt != 0);
        }
    }
}
#define NOT_SDA

#define MACRO_ADDR

/* Ported from rac1-decomp (src/overlays/shared/mobyfunc_0024FD50.c: func_L00_00250060), where it is exact; names translated to the US level program. */

typedef struct Slot {
    short id;
    short s2;
    unsigned char used;
    char pad5[7];
    void *p0C;
    void *p10;
    int p14;
    char pad18[4];
    void *p1C;
    char pad20[0x20];
} Slot;

extern Slot D_L00_0018EB40[];
extern char D_L00_00186D40[];

Slot *FUN_L00_0024f028(char *o, int id) {
    int i = 0;
    Slot *s;
    unsigned char *r;
    for (i = 0; i < 6 && D_L00_0018EB40[i].used != 0; i++) {
    }
    s = &D_L00_0018EB40[i];
    s->used = 1;
    s->id = id;
    id = (short)id;
    s->p10 = D_L00_00186D40 + i * 0x1500;
    s->p14 = *(int *)(o + 0x24);
    r = *(unsigned char **)(*(char **)(*(char **)(o + 0x24) + 0x1C) + id * 4 + 4);
    s->s2 = r[2];
    s->p0C = r + (r[0] + 4);
    s->p1C = *(void **)(o + 0x60);
    *(Slot **)(o + 0x60) = s;
    return s;
}
#ifndef NON_MATCHING
INCLUDE_ASM("config/us/overlays/asm/FUN_L00_0024f0e8.s", FUN_L00_0024f0e8);
#else
void FUN_001f97e8(void *, int, int);

void FUN_L00_0024f0e8(char *o, Slot **slot) {
    Slot *s = *slot;
    Slot **head;
    Slot *p;
    Slot *next;
    if (s == 0) return;
    head = (Slot **)(o + 0x60);
    p = *head;
    if (p == s) {
        *head = s->p1C;
    } else {
        next = p->p1C;
        while (next != 0 && next != s) {
            p = next;
            next = p->p1C;
        }
        if (next == s)
            p->p1C = s->p1C;
    }
    FUN_001f97e8(*slot, 0, 0x40);
    *slot = 0;
}
#endif

#define NOT_SDA

#define MACRO_ADDR

/* advances an animation blend timer and steps through its frame table */
/* Ported from rac1-decomp (src/overlays/shared/mobyfunc_0024FD50.c: func_L00_002501C8), where it is exact; names translated to the US level program. */

extern void FUN_L00_0024f440(void *, int, int, int);
extern void FUN_L00_00252990(void *);

void FUN_L00_0024f190_c(void *unused, unsigned char *a) __asm__("FUN_L00_0024f190");
void FUN_L00_0024f190_c(void *unused, unsigned char *a) {
    float s = *(float *)(a + 0x28);
    a[5] = 0;
    if (s != 0.0f && *(float *)(a + 0x2C) != 0.0f) {
        float t = *(float *)(a + 0x24) + s * *(float *)(a + 0x2C);
        *(float *)(a + 0x24) = t;
        if (s > 0.0f) {
            if (t > 0.99f && t < 1.01f) {
                *(float *)(a + 0x24) = 1.0f;
            }
            if (*(float *)(a + 0x24) >= 1.0f) {
                int u = a[7];
                do {
                    int o, p, o2;
                    a[6] = u;
                    a[5] |= 1;
                    a[0x20] = a[0x21];
                    if ((unsigned char)u) {
                        *(int *)(a + 0x38) = *(int *)(a + 0x3C);
                    }
                    a[0x22] = a[0x23];
                    a[0x21]++;
                    o = a[0x23] * 4;
                    if (a[0x21] >=
                        *(unsigned char *)(*(int *)(*(unsigned char **)(a + 0x14) + o + 0x48) +
                                           0x10)) {
                        a[0x21] = 0;
                        a[5] |= 2;
                    }
                    {
                        float f = (*(float *)(a + 0x24) - 1.0f) / *(float *)(a + 0x2C);
                        float g;
                        o2 = a[0x22] * 4;
                        p = a[0x20] * 4;
                        *(float *)(a + 0x24) = f;
                        g = **(float **)(*(int *)(*(unsigned char **)(a + 0x14) + o2 + 0x48) + p +
                                         0x1C);
                        *(float *)(a + 0x2C) = g;
                        *(float *)(a + 0x24) = f * g;
                    }
                } while (*(float *)(a + 0x24) >= 1.0f);
            }
        }
    }
    if (a[6]) {
        FUN_L00_0024f440(a, a[0x22], a[0x20], *(int *)(a + 0x38));
    } else {
        int o = a[0x22] * 4;
        int p = a[0x20] * 4;
        *(int *)(a + 0x38) =
            *(int *)(*(int *)(*(unsigned char **)(a + 0x14) + o + 0x48) + p + 0x1C);
    }
    if (a[7]) {
        FUN_L00_0024f440(a, a[0x23], a[0x21], *(int *)(a + 0x3C));
    } else {
        int o = a[0x23] * 4;
        int p = a[0x21] * 4;
        *(int *)(a + 0x3C) =
            *(int *)(*(int *)(*(unsigned char **)(a + 0x14) + o + 0x48) + p + 0x1C);
    }
    FUN_L00_00252990(a);
}
typedef struct {
    u8 pad[0x20];
    u8 b20, b21, b22, b23;
    s32 i24;
    f32 f28;
    f32 f2c;
} S;
typedef struct {
    u8 pad[0x51];
    u8 b51, b52, b53;
} A;
/* Fills a1 from a0's bytes, a2/a3 and a 1/a4 step; calls FUN_L00_0024f190 when a5 is set. */
void FUN_L00_0024f3e0(A *a0, S *a1, s32 a2, s32 a3, s32 a4, s32 a5) {
    a1->b22 = a0->b53;
    a1->b20 = a0->b51;
    a1->b23 = a2;
    a1->b21 = a3;
    a1->f28 = 1.0f;
    a1->f2c = 1.0f / (f32)a4;
    a1->i24 = 0;
    if (a5)
        FUN_L00_0024f190();
}
#ifndef NON_MATCHING
INCLUDE_ASM("config/us/overlays/asm/FUN_L00_0024f440.s", FUN_L00_0024f440);
#else
extern void FUN_001f9810(void *, int);
extern void FUN_001f9838(void *, void *, int);
extern void FUN_00118a80(int);

void FUN_L00_0024f440(void *statePointer, int tableIndex, int frameIndex, int outputAddress) {
    int table;
    int baseTable;
    unsigned char count;
    unsigned char baseCount;
    unsigned char *frame;
    unsigned char *indices;
    unsigned long long *values;
    unsigned int remainingCount;
    unsigned short frameStart;
    int baseBytes;
    int countBytes;
    int copyBytes;
    unsigned char *copySource;
    unsigned long long *sentinel;

    table = *(int *)((char *)statePointer + 0x18);
    baseTable = *(int *)((char *)statePointer + 0x14);
    baseCount = *(unsigned char *)(baseTable + 8);
    count = *(unsigned char *)(table + 8);
    frame = *(unsigned char **)(*(int *)(table + tableIndex * 4 + 0x48) + frameIndex * 4 + 0x1c);
    FUN_001f9810((void *)outputAddress, ((baseCount + 3) * 8) & 0xff0);
    baseBytes = baseCount * 8;
    countBytes = count * 8;
    *(short *)(outputAddress + 6) = (baseCount + *(short *)(frame + 10) + *(short *)(frame + 14) + 1) >> 1;
    *(short *)(outputAddress + 8) = baseBytes;
    frameStart = *(unsigned short *)(frame + 10);
    *(short *)(outputAddress + 10) = frameStart;
    *(unsigned short *)(outputAddress + 12) = (frameStart + baseCount) * 8;
    *(unsigned short *)(outputAddress + 14) = *(unsigned short *)(frame + 14);
    copySource = frame + (countBytes + 16);
    copyBytes = *(short *)(frame + 6) * 16 - countBytes;
    if (copyBytes != 0) {
        FUN_001f9838((void *)(outputAddress + (baseBytes + 16)), copySource, copyBytes);
    }
    indices = (unsigned char *)(*(int *)(*(int *)((char *)statePointer + 0x18) + 0x1c) + 4);
    values = (unsigned long long *)(frame + 16);
    remainingCount = count;
    for (; remainingCount != 0; remainingCount--) {
        unsigned char index = *indices++;
        unsigned long long value = *values++;
        *(unsigned long long *)(outputAddress + index * 8 + 16) = value;
    }
    sentinel = (unsigned long long *)(outputAddress + *(short *)(outputAddress + 6) * 16);
    if (*sentinel == 0) {
        *sentinel = 1;
    }
    FUN_00118a80(0);
}
#endif
