/* Level overlay code after unclassified; generated by `decomp overlays stubs`, stubs replaced by C as functions are matched. */
/* Mixed file: VU0 (vcallms) and byte/halfword unpacking helpers; 00257218 and 00257470 read moby and hero state. */
#include "types.h"
#include "rnc/globals.h"
#include "rnc/gameplay/hero.h"
#include "asm.h"

INCLUDE_ASM("config/us/overlays/asm/FUN_L00_00250df8.s", FUN_L00_00250df8);
INCLUDE_ASM("config/us/overlays/asm/FUN_L00_00250e30.s", FUN_L00_00250e30);
INCLUDE_ASM("config/us/overlays/asm/FUN_L00_00252990.s", FUN_L00_00252990);
INCLUDE_ASM("config/us/overlays/asm/FUN_L00_00254b58.s", FUN_L00_00254b58);
INCLUDE_ASM("config/us/overlays/asm/FUN_L00_00256f14.s", FUN_L00_00256f14);
INCLUDE_ASM("config/us/overlays/asm/FUN_L00_00257024.s", FUN_L00_00257024);
#ifndef NON_MATCHING
INCLUDE_ASM("config/us/overlays/asm/FUN_L00_00257218.s", FUN_L00_00257218);
#else
#include "rnc/gameplay/state/item_state.h"

typedef struct {
    u8 pad[0xE];
    u16 count;
    u8 tail[8];
} ItemCount_257218;
extern ItemCount_257218 D_L00_001C40B0[] __asm__("D_L00_001C40B0");
extern s32 random_integer_below(s32) __asm__("FUN_00213260");

int FUN_L00_00257218(u8 *m, s32 *item) {
    s32 available = 0;
    s32 stocked = 0;
    s32 shortfall = 0;
    s32 i;
    s32 choice;
    u32 id;
    u8 *entry;

    if (*item <= 0 || (m != 0 &&
        ((D_0014C190_257218[current_level_index][(s16)*(u16 *)(m + 0xB2) >> 5] >>
          (*(u16 *)(m + 0xB2) & 31)) & 1))) {
        entry = D_0015EDD0_257218;
        i = 0;
        if (*entry != 0xFF) {
            while (1) {
                id = *entry & 0x3F;
                if (item_available[id]) {
                    ItemCount_257218 *count = &D_L00_001C40B0[id];
                    available++;
                    if (count->count != 0) {
                        stocked++;
                    }
                    shortfall += weapon_ammo_counts[id] < count->count;
                }
                i++;
                entry++;
                if (i == 12) break;
                if (*entry == 0xFF) break;
            }
        }
        i = -1;
        if (shortfall == 0) {
            id = 10;
            if (available != 0) {
                choice = random_integer_below(stocked);
                if (choice >= 0) {
                    i = -1;
                    while (1) {
                        i++;
                        id = D_0015EDD0_257218[i] & 0x3F;
                        if (item_available[id]) {
                            if (D_L00_001C40B0[id].count != 0) choice--;
                        }
                        if (choice < 0) break;
                    }
                }
                id = D_0015EDD0_257218[i] & 0x3F;
            }
        } else {
            choice = random_integer_below(shortfall);
            if (choice >= 0) {
                i = 0;
                while (1) {
                    id = D_0015EDD0_257218[i] & 0x3F;
                    if (item_available[id]) {
                        choice -= weapon_ammo_counts[id] < D_L00_001C40B0[id].count;
                    }
                    if (choice < 0) break;
                    ++i;
                }
            }
            id = D_0015EDD0_257218[i] & 0x3F;
        }
        *item = id;
    }
    choice = random_integer_below(5);
    id = 1;
    if (choice == 0) id = 2;
    return id;
}
#endif
extern int D_0015ED84_257470 __asm__("D_0015ED84");
extern int D_0015ED84_257470b __asm__("D_0015ED84");
extern int D_L00_0015FFBC_257470 __asm__("D_L00_0015FFBC");
extern int D_0014C190_257470[][64] __asm__("D_0014C190") __attribute__((section(".data")));
extern unsigned char D_0014C050_257470[][16] __asm__("D_0014C050")
    __attribute__((section(".data")));
extern short D_0014D590_257470[][64][2] __asm__("D_0014D590") __attribute__((section(".data")));
extern int D_L00_001BA4D0_257470[] __asm__("D_L00_001BA4D0") __attribute__((section(".data")));
typedef struct {
    unsigned char p[0x454];
    unsigned char a[1];
} S_257470;
extern S_257470 D_L00_001BA5D0_257470 __asm__("D_L00_001BA5D0") __attribute__((section(".data")));
extern S_257470 D_L00_001BB230_257470 __asm__("D_L00_001BB230") __attribute__((section(".data")));
extern unsigned char D_L00_0015FC88_257470[] __asm__("D_L00_0015FC88")
    __attribute__((section(".data")));
extern unsigned char D_L00_001E8F00_257470[] __asm__("D_L00_001E8F00")
    __attribute__((section(".data")));
extern unsigned char D_L00_001E8F28_257470[] __asm__("D_L00_001E8F28")
    __attribute__((section(".data")));
extern struct Hero hero_data __asm__("D_0013F350") __attribute__((section(".data")));
extern void FUN_001e93b0_257470(void *, ...) __asm__("FUN_001e93b0");
extern int FUN_001fa6d0_257470(float) __asm__("FUN_001fa6d0");
extern float FUN_001f9b48_257470(void *, void *) __asm__("FUN_001f9b48");
extern void FUN_L00_00260a88_257470(void *, int, int, int, int) __asm__("FUN_L00_00260a88");

void FUN_L00_00257470(unsigned char *m, int flags, int arg) {
    float amt;
    int lvl;
    int k;
    int d;
    int n;
    int f;
    int r;
    int cnt;
    unsigned char *g;

    amt = *(short *)(m + 0xB4);
    FUN_001e93b0_257470(D_L00_001E8F00_257470, *(short *)(m + 0xA6), *(short *)(m + 0xB2),
                        *(short *)(m + 0xB4), *(short *)(m + 0xB6));
    if (m[0xB1] == 0xFE) {
        return;
    }
    if (*(short *)(m + 0xB2) < 0) {
        return;
    }
    lvl = D_0015ED84_257470;
    D_0014C190_257470[lvl][*(short *)(m + 0xB2) >> 5] |= 1
                                                         << (*(unsigned short *)(m + 0xB2) & 0x1F);
    D_L00_001BA4D0_257470[*(short *)(m + 0xB2) >> 5] |= 1 << (*(unsigned short *)(m + 0xB2) & 0x1F);
    D_L00_001BA5D0_257470.a[*(short *)(m + 0xB2)] = m[0xB0] + 2;
    k = m[0xB0];
    {
        unsigned int u = k & 0xFF;
        if (k == 0xFF || (D_L00_0015FC88_257470[u] != 0xFF && D_0014C050_257470[lvl][u] == 0xFF)) {
            D_L00_001BB230_257470.a[*(short *)(m + 0xB2)] = k + 2;
        }
    }
    if ((signed char)m[0xB1] >= 0) {
        int n1 = *(short *)(m + 0xB6);
        d = n1 - D_0014D590_257470[D_0015ED84_257470b][m[0xB1]][1];
        {
            int x = (n1 + 1) / 2 < d ? d : 0;
            if (x) {
                amt = x;
            }
        }
        if (amt < 1.0f) {
            amt = 1.0f;
        }
        FUN_001e93b0_257470(D_L00_001E8F28_257470, FUN_001fa6d0_257470(amt));
    }
    f = 1;
    if (flags & 0x100) {
        f = 5;
    }
    if (hero_data.unk20B2 || (flags & 0x200)) {
        f |= 2;
    }
    if (hero_data.state.current == 0x10 &&
        FUN_001f9b48_257470(&hero_data.motion.pos, m + 0x10) < 4.0f) {
        f |= 2;
    }
    cnt = D_L00_0015FFBC_257470;
    if (flags & 0x400) {
        f |= 0x10;
    }
    if (cnt < 100 || (flags & 0x800)) {
        f |= 8;
    }
    if (D_L00_0015FFBC_257470 < 50) {
        f |= 2;
    }
    if (amt < 0.0f) {
        amt = 0.0f;
    }
    if (amt > 0.0f) {
        r = 0;
        if (amt >= 8.0f) {
            r = FUN_001fa6d0_257470(amt * 0.25f);
        } else if (amt >= 2.0f) {
            r = 1;
        }
        {
            int n2 = FUN_001fa6d0_257470(amt);
            int hi = n2 + r;
            n2 -= r;
            FUN_L00_00260a88_257470(m, n2, hi, f, arg);
        }
    }
}
