/* Level overlay code after rendering; generated by `decomp overlays stubs`, stubs replaced by C as functions are matched. */
#include "types.h"
#include "asm.h"

#define NOT_SDA

#define MACRO_ADDR

#include "qcopy.h"

/* Spawns a type-10 particle at a position and sets its colour, size, life and velocity. */
/* Ported from rac1-decomp (src/overlays/shared/partupd_00280428.c: func_L01_00280428), where it is exact; names translated to the US level program. */

extern float random_float_between_alt(float, float) __asm__("FUN_002132a8");
extern int scale_game_frames(int) __asm__("FUN_001f96f8");
extern int FUN_L00_0025bfe0(float, float, float, float);
extern s32 truncate_float_to_s32(f32) __asm__("FUN_001fa6d0");
extern unsigned char *D_L01_001B250C_d __asm__("D_L01_001B250C") __attribute__((section(".data")));
extern unsigned char *FUN_L00_002678b8(int);
extern int func_001FA898_r(float) __asm__("FUN_001fa6d0");

void FUN_L01_0027f660(char *pos, char *vel) {
    unsigned char *p = FUN_L00_002678b8(10);
    if (p != 0) {
        char *q = (char *)p + 0x20;
        qcopy(p + 0x10, pos);
        *(int *)(p + 4) = FUN_L00_0025bfe0(0.425f, 0.425f, 0.225f, 1.0f);
        p[9] = func_001FA898_r(8.0f) - 0x60;
        p[1] = 0;
        p[3] = 0x48;
        *(float *)(p + 0xC) = random_float_between_alt(60900.0f, 90300.0f);
        p[8] = 0;
        p[2] = *D_L01_001B250C_d;
        *(float *)(q + 0x10) = 0.425f;
        *(float *)(q + 0x14) = 0.425f;
        *(float *)(q + 0x18) = 0.225f;
        *(float *)(q + 0x1C) = 1.0f;
        *(short *)(p + 0xA) = scale_game_frames(0x57);
        qcopy(q, vel);
    }
}
#ifndef NOT_SDA
#define NOT_SDA __attribute__((section(".data")))
#endif
#ifndef MACRO_ADDR
#define MACRO_ADDR __attribute__((section(".sdata")))
#endif
extern unsigned char *func_00218928_80970(int) __asm__("FUN_L00_002678b8");
extern float func_L00_00258C80_80970(float, float) __asm__("FUN_L00_00257c48");
extern int func_001FA898_r_80970(float) __asm__("FUN_001fa6d0");
extern int func_002140B0_80970(int) __asm__("FUN_00213260");
extern int func_001F9850_80970(int) __asm__("FUN_001f96f8");
extern unsigned char *D_L01_001B2838_80970 __asm__("D_L01_001B2538")
    __attribute__((section(".data")));
char *FUN_L01_00280970(int a, char *b) {
    char *p = func_00218928_80970(0xE);
    int r;
    int *q;
    if (p) {
        qcopy(p + 0x10, b + 0x10);
        *(float *)(p + 0x10) += func_L00_00258C80_80970(0.0f, 0.03f);
        *(float *)(p + 0x14) += func_L00_00258C80_80970(0.0f, 0.03f);
        *(float *)(p + 0x18) += func_L00_00258C80_80970(0.0f, 0.03f);
        *(int *)(p + 4) = -1;
        r = func_001FA898_r_80970(4.0f);
        p[9] = r - 0x60;
        p[1] = 0;
        p[3] = 0x48;
        *(float *)(p + 0xC) = 29400.0f;
        p[8] = func_002140B0_80970(0xFF);
        p[2] = *D_L01_001B2838_80970;
        *(short *)(p + 0xA) = func_001F9850_80970(6);
        q = (int *)(p + 0x20);
        q[2] = (int)b;
        q[1] = 1;
        if (a == 0) {
            q[0] = 0;
        } else if (func_002140B0_80970(2)) {
            q[0] = a;
        } else {
            q[0] = -a;
        }
    }
    return p;
}

extern char *D_L01_001B25A4[];
extern char *alloc_285768(int) __asm__("FUN_L00_002678b8");
extern int trunc_285768(float) __asm__("FUN_001fa6d0");

/* Allocates a type 0x29 particle and fills it from the arguments; kind 0xFF
 * derives the frame from flags and picks one of two blend modes. */
char *FUN_L01_00285768(float scale, void *pos, int a, int idx, int b, unsigned char flags, short h, unsigned char kind) {
    char *r = alloc_285768(0x29);
    if (r != 0) {
        int *tail = (int *)(r + 0x20);
        qcopy(r + 0x10, pos);
        *(int *)(r + 4) = b;
        if (kind == 0xFF) {
            r[9] = (flags >> 5) * 16 + trunc_285768(4.0f);
            if (flags & 1) {
                r[3] = 0x48;
            } else {
                r[3] = 0x44;
            }
        } else {
            r[9] = flags;
            r[3] = kind;
        }
        r[1] = 0;
        r[2] = D_L01_001B25A4[0][idx];
        *(float *)(r + 0xC) = scale * 210000.0f;
        *(short *)(r + 0xA) = h;
        ((unsigned char *)r)[8] = 0xA0;
        /* taking the address changes register allocation to match */
        *tail = *&a;
    }
    return r;
}

#ifndef NOT_SDA
#endif
#ifndef MACRO_ADDR
#endif
extern unsigned char *func_00218928_87158(int) __asm__("FUN_L00_002678b8");
extern int func_001FA898_87158(float) __asm__("FUN_001fa6d0");
extern int func_002140B0_87158(int) __asm__("FUN_00213260");
extern float func_001FA888_87158(int) __asm__("FUN_001fa6c0");
extern unsigned char *D_L01_001B28D0_87158 __asm__("D_L01_001B25D0")
    __attribute__((section(".data")));
unsigned char *FUN_L01_00287158(void *a, int b, int c, int d, float f, float g) {
    unsigned char *r = func_00218928_87158(0x34);
    if (r != 0) {
        char *v = (char *)r + 0x20;
        qcopy(r + 0x10, a);
        *(float *)(r + 0x18) += 0.05f;
        *(int *)(r + 4) = b;
        r[3] = 0x44;
        r[9] = func_001FA898_87158(4.0f) + 0x20;
        r[1] = 1;
        r[2] = *D_L01_001B28D0_87158;
        *(short *)(r + 0xA) = d;
        *(float *)(r + 0xC) = f * 210000.0f;
        r[8] = func_002140B0_87158(0xFF);
        *(int *)(v + 8) = b;
        *(int *)(v + 0xC) = c;
        *(float *)v = f;
        *(float *)(v + 4) = g;
        *(float *)(v + 0x10) = 1.0f / func_001FA888_87158(d);
    }
    return r;
}
#include "qzero.h"
#include "rnc/overlay/quad.h"

/* spawns a type-74 particle with transformed offset and velocity */
/* Ported from rac1-decomp (src/overlays/shared/partupd_00280428.c: func_L01_0028B570), where it is exact; names translated to the US level program. */

extern int D_L01_001B2628; /* no foreign declaration */
extern s32 rand(void);
extern s32 truncate_float_to_s32_c(f32) __asm__("func_001FA6D0");
extern void FUN_001fa2d8(void *, void *);
extern void subtract_vector_xyz_c(void *, void *, void *) __asm__("FUN_001f9a28");
extern void transform_vector(void *, void *, void *) __asm__("func_001F9D20");
extern unsigned char D_L01_001B2928_b[] __asm__("D_L01_001B2628");

unsigned char *FUN_L01_0028a7a8(char *m, char *pos, float *vel, char *cfg, int flag) {
    float v[4];
    float mat[16];
    unsigned char *p = FUN_L00_002678b8(74);
    if (p) {
        char *q;
        p[9] = func_001FA898_r(4.0f) - 0x60;
        if (flag)
            p[3] = 0x48;
        else
            p[3] = 0x44;
        p[1] = 0;
        q = (char *)p + 0x20;
        p[2] = **(unsigned char **)D_L01_001B2928_b;
        p[8] = rand();
        *(int *)(p + 0xc) = 0;
        qcopy(p + 0x10, pos);
        *(float *)q = vel[0];
        *(float *)(q + 4) = vel[1];
        *(float *)(q + 8) = vel[2];
        subtract_vector_xyz_c(v, pos, m + 0x10);
        qzero(mat);
        qzero(mat + 4);
        qzero(mat + 8);
        qzero(mat + 12);
        FUN_001fa2d8(mat, m + 0xc0);
        transform_vector(v, v, mat);
        *(float *)(q + 0x10) = v[0];
        *(float *)(q + 0x14) = v[1];
        *(float *)(q + 0x18) = v[2];
        *(char **)(q + 0xc) = m;
        *(char **)(q + 0x1c) = cfg;
        *(short *)(p + 0xa) = *(unsigned short *)(cfg + 0xc);
        *(int *)(p + 4) = *(int *)cfg;
    }
    return p;
}
/* Ported from rac1-decomp (src/overlays/shared/partupd_00280428.c: func_L01_0028C1D8), where it is exact; names translated to the US level program. */

extern char *D_L01_001B0930[];
extern float FUN_001f9b48(void *, void *);

void FUN_L01_0028b410(char *p) {
    int i;
    int off;
    char *q;
    p[5] = 0;
    *(int *)(p + 8) = 0;
    *(char **)(p + 0x10) = D_L01_001B0930[*(int *)(p + 0x14)];
    for (i = 0; i < **(int **)(p + 0x10); i++) {
        q = *(char **)(p + 0x10);
        off = i << 4;
        *(float *)(*(char **)(p + 0x10) + off + 0x1C) =
            FUN_001f9b48(q + (off + 0x10), q + ((((i + 1) % *(int *)q) << 4) + 0x10));
        *(float *)(*(char **)(p + 0x10) + off + 0x18) += 0.5f;
        *(float *)(*(char **)(p + 0x10) + off + 0x18) -= 0.5f;
    }
}
/* Returns the index of the entry whose distance to arg0 is closest to a target value. */
/* Ported from rac1-decomp (src/overlays/shared/partupd_00280428.c: func_L01_0028C2D8), where it is exact; names translated to the US level program. */

typedef struct {
    int count;
    int pad[3];
    float e[1][4];
} List;

extern float FUN_001f9b48(void *, void *);
float absolute_float(float input) __asm__("func_001F99C0");

int FUN_L01_0028b510(void *arg0, List *arg1, float target) {
    int best = 0;
    int i;
    float bestDiff = 1e11f;
    for (i = 0; i < arg1->count; i++) {
        float d = FUN_001f9b48(arg1->e[i], arg0);
        if (absolute_float(d - target) < bestDiff) {
            bestDiff = d;
            best = i;
        }
    }
    return best;
}
int FUN_L01_0028b5e0(char *a0, List *list, char *pt, char *out) {
    int idx0 = -1;
    int idx1 = -1;
    float best0 = 10000.0f;
    float best1 = 10000.0f;
    float d_init = FUN_001f9b48(a0 + 0x10, pt);
    int i;

    for (i = 0; i < list->count; i++) {
        float d_pt = FUN_001f9b48(list->e[i], pt);
        float d_a0 = FUN_001f9b48(list->e[i], a0 + 0x10);
        if (d_a0 < best0) {
            best0 = d_a0;
            idx0 = i;
        }
        if (d_pt < d_init) {
            if (d_pt < best1) {
                best1 = d_pt;
                idx1 = i;
            }
        }
    }
    if (idx1 != -1) {
        if (idx0 == idx1) {
            qcopy(out, list->e[idx0]);
            return idx0;
        }
        if (idx0 < idx1) {
            qcopy(out, list->e[idx0 + 1]);
            return idx0 + 1;
        }
        qcopy(out, list->e[idx0 - 1]);
        return idx0 - 1;
    }
    qcopy(out, pt);
    return -1;
}
/* Select a 16-byte entry using the descriptor's signed index rules. */
void *FUN_L01_0028b7b0(void *descriptor, s32 index) {
    char *data;
    s32 last;

    if (*(s8 *)((char *)descriptor + 4) >= 0) {
        last = (s32)((u32)**(s32 **)((char *)descriptor + 0x10) - 1);
        data = *(char **)((char *)descriptor + 0x10);
    } else {
        data = *(char **)((char *)descriptor + 0x10);
        last = 0;
    }
    if (index < 0)
        return data + ((((u32)last + (u32)index) << 4) + 0x20);
    if (index > last)
        return data + (((u32)(index % (s32)((u32)last + 1)) << 4) + 0x10);
    return data + (((u32)index << 4) + 0x10);
}

typedef struct {
    char pad0[4];
    signed char f4;
    char pad1[0x10 - 5];
    int *f10;
} T_28b828;

int FUN_L01_0028b828(T_28b828 *a, int b) {
    int n;
    n = (a->f4 < 0) ? 0 : (*a->f10 - 1);
    if (b < 0) {
        return n + b;
    }
    if (n < b) {
        return b % (n + 1);
    }
    return b;
}
/* 0x0028b878, 76 bytes.
 * Ported from rac1-decomp, where it is exact; names translated to
 * the US level program (data still reached through the MACRO_ADDR form). */
int FUN_L01_0028b878(char *p) {
    int max = 0;
    int next;
    if (p[4] >= 0) {
        max = **(int **)(p + 0x10) - 1;
    }
    next = *(int *)p + 1;
    if (max < next) {
        next %= max + 1;
    }
    *(int *)p = next;
    return next;
}

/* Ported from rac1-decomp (src/overlays/shared/partupd_00280428.c: func_L01_0028C690), where it is exact; names translated to the US level program. */


extern f32 vector_length_xyz(void *a) __asm__("FUN_001f9af0");
extern void *FUN_L01_0028b7b0(void *, int);
extern void *memset(void *, int, unsigned int);
extern void add_vector_xyz(void *, void *, void *) __asm__("FUN_001f9a10");
extern void normalize_vector_xyz(void *out, void *a, f32 len) __asm__("FUN_001f9bf8");
extern void scale_vector_xyz(void *out, void *a, f32 s) __asm__("FUN_001f9a68");
extern void subtract_vector_xyz(void *out, void *a, void *b) __asm__("FUN_001f9a28");
extern void *func_001153FC_c(void *, int, unsigned int) __asm__("FUN_001153fc");

void FUN_L01_0028b8c8(void *out, int *l, int idx, float a, float b) {
    void *p[3];
    float v1[4];
    float v2[4];
    float v3[4];
    float d1, d2, m, len;
    float wa, wb;
    func_001153FC_c(p, 0, 12);
    p[0] = FUN_L01_0028b7b0(l, *l + idx - 1);
    p[1] = FUN_L01_0028b7b0(l, *l + idx);
    p[2] = FUN_L01_0028b7b0(l, *l + idx + 1);
    {
        wb = (1.0f - a) * (b + 1.0f) * 0.5f;
        wa = (1.0f - a) * (1.0f - b) * 0.5f;
    }
    d1 = FUN_001f9b48(p[0], p[1]);
    d2 = FUN_001f9b48(p[1], p[2]);
    if (d1 < d2)
        m = d1;
    else
        m = d2;
    subtract_vector_xyz(v1, p[1], p[0]);
    scale_vector_xyz(v1, v1, wb);
    subtract_vector_xyz(v2, p[2], p[1]);
    scale_vector_xyz(v2, v2, wa);
    add_vector_xyz(v3, v1, v2);
    m = m * 1.1f;
    len = vector_length_xyz(v3);
    if (m < len) {
        normalize_vector_xyz(out, v3, m);
    } else {
        *(OvlQuad *)out = *(OvlQuad *)v3;
    }
}
/* Ported from rac1-decomp (src/overlays/shared/partupd_00280428.c: func_L01_0028C848), where it is exact; names translated to the US level program. */

extern void FUN_001f9a10(void *, void *, void *);
extern void FUN_001f9a68(void *, void *, float);

void FUN_L01_0028ba80(float t, void *out, void *p1, void *p2, void *p3, void *p4) {
    char tmp[16];
    float t2 = t * t;
    float t3 = t2 * t;
    float b = t2 * 3.0f;
    float a = t3 + t3;
    float c = t2 + t2;
    FUN_001f9a68(out, p1, a - b + 1.0f);
    FUN_001f9a68(tmp, p3, t3 - c + t);
    FUN_001f9a10(out, out, tmp);
    FUN_001f9a68(tmp, p4, t3 - t2);
    FUN_001f9a10(out, out, tmp);
    FUN_001f9a68(tmp, p2, b - a);
    FUN_001f9a10(out, out, tmp);
}
#ifndef NON_MATCHING
INCLUDE_ASM("config/us/overlays/asm/FUN_L01_0028bb90.s", FUN_L01_0028bb90);
#else
float FUN_L01_0028bb90(T_28b828 *path, int particles, void *moby, float a, float b) {
    OvlVec4 previousTangent;
    OvlVec4 nextTangent;
    OvlVec4 currentNode;
    OvlVec4 nextNode;
    OvlVec4 point;
    OvlVec4 previousPoint;
    int count = *path->f10;
    int savedIndex = *(int *)path;
    int index;
    float total = 0.0f;

    *(int *)path = 0;
    nextNode.q = *(OvlQuad *)((char *)path->f10 + 0x10);
    if (particles) {
        FUN_L01_00285768(0.666f, &nextNode, (int)moby, 0, 0x80101080, 0x7f, -1, 0xff);
    }
    FUN_L01_0028b8c8(&nextTangent, (int *)path, 0, a, b);

    index = 0;
    while (index < count) {
        float t;
        float step;
        float segmentLength;
        int nextIndex;
        currentNode.q = nextNode.q;
        previousTangent.q = nextTangent.q;
        if (particles) {
            FUN_L01_00285768(1.0f, &currentNode, (int)moby, index % 15 + 2, 0x80108010, 0x7f, -1, 0xff);
        }
        t = 0.05f;
        nextIndex = FUN_L01_0028b828(path, index + 1);
        segmentLength = 0.0f;
        nextNode.q = *(OvlQuad *)((char *)path->f10 + nextIndex * 16 + 0x10);
        *(int *)path = index;
        FUN_L01_0028b8c8(&nextTangent, (int *)path, 1, a, b);
        previousPoint.q = currentNode.q;
        step = t;
        do {
            if (particles) {
                FUN_L01_00285768(0.2f, &previousPoint, (int)moby, 0, 0x80404080, 0x7f, -1, 0xff);
            }
            FUN_L01_0028ba80(t, &point, &currentNode, &nextNode, &previousTangent, &nextTangent);
            t += step;
            segmentLength += FUN_001f9b48(&previousPoint, &point);
            previousPoint.q = point.q;
        } while (t <= 1.0f);
        total += segmentLength;
        {
            char *nodeData = (char *)path->f10;
            *(float *)(nodeData + (index << 4) + 0x1c) = segmentLength;
        }
        index++;
    }
    *(int *)path = savedIndex;
    return total;
}
#endif
