/* Level overlay code after unclassified; generated by `decomp overlays stubs`, stubs replaced by C as functions are matched. */
#include "types.h"
#include "rnc/gameplay/hero.h"
#include "rnc/globals.h"
#include "rnc/math_consts.h"
#include "asm.h"
#include "rnc/overlay/watch.h"
#include "qcopy.h"
#include "rnc/math/vector.h"
#include "rnc/gameplay/entities/moby.h"

#define NOT_SDA

#define MACRO_ADDR

/* records, for entry arg, which of the 48 entries sit one grid step away */
/* Ported from rac1-decomp (src/overlays/l05_rilgar/vendor_0030EB68.c: func_L05_0030EB68), where it is exact; names translated to the US level program. */

typedef struct {
    float x;
    float y;
    int pad;
    char n[0x14];
    char rest[0x1170];
} Ent;

extern Ent D_L05_001D6880[];
float absolute_float(float input) __asm__("func_001F99C0");

void FUN_L05_0030d6a0(int arg) {
    int i;
    Ent *t = D_L05_001D6880;
    for (i = 0; i < 48; i++) {
        if (arg != i) {
            Ent *e = &t[arg];
            float x = e->x - t[i].x;
            float y = e->y - t[i].y;
            if (absolute_float(x) < 0.1f) {
                if (absolute_float(y - 16.0f) < 0.1f)
                    e->n[0] = i;
                if (absolute_float(y + 16.0f) < 0.1f)
                    e->n[2] = i;
            } else if (absolute_float(y) < 0.1f) {
                if (absolute_float(x - 16.0f) < 0.1f)
                    e->n[1] = i;
                if (absolute_float(x + 16.0f) < 0.1f)
                    e->n[3] = i;
            } else {
                if (absolute_float(x - 16.0f) < 0.1f) {
                    if (absolute_float(x - 16.0f) < 0.1f)
                        e->n[5] = i;
                    if (absolute_float(x + 16.0f) < 0.1f)
                        e->n[7] = i;
                } else if (absolute_float(x + 16.0f) < 0.1f) {
                    if (absolute_float(x - 16.0f) < 0.1f)
                        e->n[4] = i;
                    if (absolute_float(x + 16.0f) < 0.1f)
                        e->n[6] = i;
                }
            }
        }
    }
}
#include "qcopy.h"

/* Ported from rac1-decomp (src/overlays/l05_rilgar/vendor_0030EB68.c: func_L05_0030F130), where it is exact; names translated to the US level program. */

extern char D_0013E550[];
extern char D_L05_001671C0[];
extern float FUN_001f9b48(void *, void *);
extern int D_L05_0015F5CC_e[] __asm__("D_L05_0015F5C4") __attribute__((section(".sdata")));
extern int allocate_voice_for_target_entry() __asm__("FUN_0022da68");
extern short D_L05_0015FFD8_d __asm__("D_L05_0015FFD8");
extern short D_L05_00161D38_d __asm__("D_L05_00161D38") __attribute__((sda));
extern void FUN_L05_0030de90(void);
void enqueue_callback_list_1(int arg0, int arg1) __asm__("FUN_001f4600");
extern int func_0022ED80_i(int, int, void *) __asm__("FUN_0022da68");

void FUN_L05_0030dc68(char *m) {
    char *data = *(char **)(m + 0x78);
    int state = *(unsigned char *)(m + 0x20);
    char *base;
    char *tab;
    char *pos;
    char *q;
    char *o;
    float d;
    int idx;
    switch (state) {
    case 0:
        *(unsigned short *)(m + 0x34) |= 1;
        *(unsigned char *)(m + 0x20) = 1;
        *(unsigned char *)(m + 0x31) = 0;
        **(int **)(data + 4) = -1;
        break;
    case 1:
        if (*(int *)&D_L05_00161D38_d != D_L05_0015F5CC_e[2]) {
            *(int *)&D_L05_00161D38_d = D_L05_0015F5CC_e[2];
            enqueue_callback_list_1(FUN_L05_0030de90, m);
        }
        pos = m + 0x10;
        tab = D_L05_001671C0;
        if (FUN_001f9b48(pos, tab) < 64.0f) {
            idx = **(int **)(data + 4);
            if (idx >= 0) {
                base = D_0013E550;
                o = *(char **)(base + idx * 0x70 + 0x88);
                if (o != 0) {
                    if (*(short *)(o + 0xA6) == 0x346) {
                        if (o != m) {
                            if (*(unsigned char *)(o + 0x20) == state) {
                                d = FUN_001f9b48(pos, tab);
                                if (!(d < FUN_001f9b48(o + 0x10, tab)))
                                    goto after;
                            }
                            q = base + 0x90;
                            *(char **)(base + **(int **)(data + 4) * 0x70 + 0x88) = m;
                            qcopy(**(int **)(data + 4) * 0x70 + q, pos);
                        }
                        goto after;
                    }
                }
            }
            **(int **)(data + 4) = func_0022ED80_i(0, 4, m);
        }
    after:
        if (*(int *)data >= 0) {
            if ((*(unsigned char **)&D_L05_0015FFD8_d)[*(int *)data * 256 + 0xBC] != 0) {
                func_0022ED80_i(1, 0, m);
                *(int *)(m + 0x94) = 0;
                *(unsigned char *)(m + 0x20) = 2;
            }
        }
        break;
    case 2:
        if (*(int *)(m + 0x94) != 0)
            *(int *)(m + 0x94) = 0;
        break;
    }
}
INCLUDE_ASM("config/us/overlays/asm/FUN_L05_0030de90.s", FUN_L05_0030de90);

/* Fog zone: switches the level fog between its two settings when the hero enters either trigger volume, and
 * tints a colour by the hero's side of a gate while inside the third. */
/* Ported from rac1-decomp (src/overlays/l05_rilgar/vendor_0030EB68.c: func_L05_0030F6C0), where it is exact; names translated to the US level program. */

extern float D_L05_0015F448;
extern float D_L05_0015F44C;
extern float D_L05_0015F450;
extern float D_L05_0015F454;
extern int D_L05_001600EC; /* no foreign declaration */
extern int FUN_001fa6e0(int, int, float);
extern int is_point_inside_clip_volume(void *arg0, int arg1) __asm__("func_00214720");
extern unsigned char D_L05_0015F444;
extern unsigned char D_L05_0015F445;
extern unsigned char D_L05_0015F446;
extern unsigned char D_L05_00161202;
extern unsigned char D_L05_00161203;
extern unsigned char D_L05_00161201;
extern unsigned char D_L05_00161200;
extern void subtract_vector_xyz(void *, void *, void *) __asm__("FUN_001f9a28");
extern void transform_vector_by_basis(void *, void *, void *) __asm__("func_001F9CF8");

void FUN_L05_0030e1f8(char *moby) {
    char *data = *(char **)(moby + 0x78);
    float v[4];
    float w[4];
    char *g = (char *)&hero.motion.pos;
    if (is_point_inside_clip_volume(g, *(int *)(data + 0x28))) {
        *(float *)(g + 0x270) = 500.0f;
    }
    switch (((unsigned char *)moby)[0x20]) {
    case 0:
        data[0x20] = D_L05_0015F444;
        data[0x21] = D_L05_0015F445;
        data[0x22] = D_L05_0015F446;
        {
            float f0 = D_L05_0015F448;
            float f1 = D_L05_0015F44C;
            float f2 = D_L05_0015F450;
            float f3 = D_L05_0015F454;
            *(float *)(data + 0) = f0;
            *(float *)(data + 8) = f1;
            *(float *)(data + 4) = f2;
            *(float *)(data + 0xC) = f3;
        }
        data[0x23] = 0x49;
        data[0x24] = 0x53;
        data[0x25] = 0xC;
        *(float *)(data + 0x18) = 33792.0f;
        *(float *)(data + 0x14) = 255.0f;
        *(int *)(data + 0x10) = 0;
        *(int *)(data + 0x1C) = 0;
        {
            int c = D_L05_00161200 + (D_L05_00161201 << 8) + (D_L05_00161202 << 16) + (D_L05_00161203 << 24);
            *(int *)(data + 0x34) = 0x40408070;
            *(int *)(data + 0x30) = c;
        }
        moby[0x20] = 1;
        break;
    case 1:
        if (is_point_inside_clip_volume(&hero.motion.pos, *(int *)(data + 0x2C))) {
            D_L05_0015F444 = data[0x23];
            D_L05_0015F445 = data[0x24];
            D_L05_0015F446 = data[0x25];
            {
                float f0 = *(float *)(data + 0x10);
                float f1 = *(float *)(data + 0x18);
                float f2 = *(float *)(data + 0x14);
                float f3 = *(float *)(data + 0x1C);
                D_L05_0015F448 = f0;
                D_L05_0015F44C = f1;
                D_L05_0015F450 = f2;
                D_L05_0015F454 = f3;
            }
            moby[0x20] = 2;
        }
        break;
    case 2:
        if (is_point_inside_clip_volume(&hero.motion.pos, *(int *)(data + 0x28))) {
            D_L05_0015F444 = data[0x20];
            D_L05_0015F445 = data[0x21];
            D_L05_0015F446 = data[0x22];
            {
                float f0 = *(float *)(data + 0);
                float f1 = *(float *)(data + 8);
                float f2 = *(float *)(data + 4);
                float f3 = *(float *)(data + 0xC);
                D_L05_0015F448 = f0;
                D_L05_0015F44C = f1;
                D_L05_0015F450 = f2;
                D_L05_0015F454 = f3;
            }
            moby[0x20] = 1;
        }
        break;
    }
    g = (char *)&hero.motion.pos;
    if (is_point_inside_clip_volume(g, *(int *)(data + 0x38))) {
        int c;
        subtract_vector_xyz(v, g, D_L05_001600EC + *(int *)(data + 0x38) * 128 + 0x30);
        v[3] = 0.0f;
        transform_vector_by_basis(w, v, D_L05_001600EC + *(int *)(data + 0x38) * 128 + 0x40);
        c = FUN_001fa6e0(*(int *)(data + 0x30), *(int *)(data + 0x34), (w[0] + 1.0f) * 0.5f);
        D_L05_00161201 = c >> 8;
        D_L05_00161202 = c >> 16;
        D_L05_00161200 = c;
        D_L05_00161203 = c >> 24;
    }
}
extern void FUN_001f9bf8(void *, void *, float);
extern void FUN_001f9a68(void *, void *, float);
extern void add_vector_xyz(void *, void *, void *) __asm__("FUN_001f9a10");
extern float vector_length_xyz(void *);
extern void clear_u64_value(void *) __asm__("FUN_001f99f8");
extern float advance_accelerated_scalar(float, float, float, float, float *,
                                        float *) __asm__("FUN_00213f38");

/* Slides the moby out along its pose-table entry's direction: 0 places it,
   1 waits for the trigger byte 0xBC of its D_L05_0015FFD8 record, 2 eases
   it toward the end point, 3 lowers it to 5.9 below the entry's height. */
void FUN_L05_0030e508(char *moby) {
    char *data = *(char **)(moby + 0x78);
    float v[4];
    float pos;
    float speed;
    char *e;
    float len;
    float reach;

    switch (*(u8 *)(moby + 0x20)) {
    case 0: {
        char *e0;

        e0 = (char *)(D_L05_001600EC + (*(int *)(data + 0x10) << 7));
        qcopy(moby + 0x10, e0 + 0x30);
        *(float *)(moby + 0x48) = *(float *)(e0 + 0x78);
        FUN_001f9bf8(v, e0 + 0x10, *(float *)(data + 0x18));
        if (*(int *)(data + 0x1C) != 0) {
            FUN_001f9a68(v, v, -1.0f);
            *(u16 *)(moby + 0x34) |= 0x8000;
        }
        add_vector_xyz(moby + 0x10, moby + 0x10, v);
        *(u8 *)(moby + 0x20) = 1;
        break;
    }
    case 1:
        if ((*(unsigned char **)&D_L05_0015FFD8_d)[*(int *)(data + 0x14) * 256 + 0xBC] != 0) {
            allocate_voice_for_target_entry(0, 0, moby);
            *(u8 *)(moby + 0x20) = 2;
            clear_u64_value(data);
        }
        break;
    case 2:
        e = (char *)(D_L05_001600EC + (*(int *)(data + 0x10) << 7));
        reach = *(float *)(data + 0x18) * 3.0f;
        pos = 0.0f;
        FUN_001f9bf8(v, e + 0x10, reach);
        if (*(int *)(data + 0x1C) != 0) {
            FUN_001f9a68(v, v, -1.0f);
        }
        add_vector_xyz(v, e + 0x30, v);
        subtract_vector_xyz(v, v, moby + 0x10);
        len = vector_length_xyz(v);
        speed = vector_length_xyz(data);
        advance_accelerated_scalar(len, frame_time_sq * 20.0f, frame_time_sq * 30.0f,
                                   frame_time * 10.0f, &pos, &speed);
        FUN_001f9bf8(data, v, speed);
        add_vector_xyz(moby + 0x10, moby + 0x10, data);
        if (vector_length_xyz(v) < 0.01f) {
            *(u8 *)(moby + 0x20) = 3;
        }
        break;
    case 3:
        e = (char *)D_L05_001600EC;
        e += *(int *)(data + 0x10) << 7;
        advance_accelerated_scalar(*(float *)(e + 0x38) - 5.9f, frame_time_sq * 20.0f,
                                   frame_time_sq * 40.0f, frame_time * 10.0f,
                                   (float *)(moby + 0x18), (float *)(data + 8));
        if (*(float *)(moby + 0x18) < *(float *)(e + 0x38) - 5.9f) {
            *(u8 *)(moby + 0x20) = 4;
        }
        break;
    }
}
INCLUDE_ASM("config/us/overlays/asm/FUN_L05_0030e7f8.s", FUN_L05_0030e7f8);
/* Scatters points along a range, placing each one with a heading and radius. */
/* Ported from rac1-decomp (src/overlays/l05_rilgar/vendor_0030EB68.c: func_L05_003106E0), where it is exact; names translated to the US level program. */

extern f32 convert_integer_to_float(s32) __asm__("func_001FA6C0");
extern float FUN_L00_00257c48(float lo, float hi);
extern float fast_cos(float) __asm__("func_001F9DC8");
extern float fast_sin(float) __asm__("func_001F9DE0");
extern float random_angle_radians(void) __asm__("FUN_00213308");
extern float random_float_between_alt(float, float) __asm__("FUN_002132a8");
extern s32 scale_game_frames(s32) __asm__("func_001F96F8");
extern s32 truncate_float_to_s32(f32) __asm__("FUN_001fa6d0");
extern short D_L05_00161DB4_d __asm__("D_L05_00161DB4") __attribute__((sda));
extern short D_L05_00161DB8_d __asm__("D_L05_00161DB8") __attribute__((sda));
extern short D_L05_00161DBC_d __asm__("D_L05_00161DBC") __attribute__((sda));
extern short D_L05_00161DC0_d __asm__("D_L05_00161DC0") __attribute__((sda));
extern short D_L05_00161DC4_d __asm__("D_L05_00161DC4") __attribute__((sda));
extern short D_L05_00161DC8_d __asm__("D_L05_00161DC8") __attribute__((sda));
extern short D_L05_00161DCC_d __asm__("D_L05_00161DCC") __attribute__((sda));
extern short D_L05_00161DD0_d __asm__("D_L05_00161DD0") __attribute__((sda));
extern void FUN_L05_0029bbe0(float, void *, void *, int, int, int);
extern void add_vector_xyz(void *, void *, void *) __asm__("FUN_001f9a10");
extern void clear_vector(void *) __asm__("func_001F99F8");
extern int func_001FA898_r(float) __asm__("FUN_001fa6d0");

void FUN_L05_0030f218(char *obj, float a, float b) {
    float v[4];
    float w[4];
    float ground, x, y, t, u;
    int i, j, k, m, n;
    clear_vector(v);
    v[2] = *(float *)&D_L05_00161DC8_d * frame_time;
    ground = v[2] * 0.75f * convert_integer_to_float(*(int *)&D_L05_00161DB8_d);
    j = 0;
    for (i = j; (float)i < (b - a) / *(float *)&D_L05_00161DB4_d; i++) {
        float fi = (float)j;
        x = random_float_between_alt(fi, *(float *)&D_L05_00161DD0_d);
        y = random_angle_radians();
        w[0] = fast_cos(y) * x;
        w[1] = fast_sin(y) * x;
        w[2] = fi;
        add_vector_xyz(w, obj + 0x10, w);
        w[2] = random_float_between_alt(a, b) - ground;
        t = random_float_between_alt((a + b) * 0.5f, b) - ground;
        if (t < w[2])
            w[2] = t;
        u = random_float_between_alt(*(float *)&D_L05_00161DBC_d, *(float *)&D_L05_00161DC0_d);
        k = scale_game_frames(*(int *)&D_L05_00161DB8_d);
        m = func_001FA898_r(FUN_L00_00257c48(fi, (float)*(int *)&D_L05_00161DC4_d));
        n = *(int *)&D_L05_00161DCC_d;
        FUN_L05_0029bbe0(u, w, v, k, m, n);
    }
}
#define MOBY(p) ((struct Moby *)(p))
extern float dot_vectors_xyz(void *, void *) __asm__("FUN_001f9ab0");
extern f32 fast_add_rotations(f32, f32) __asm__("FUN_001fa580");
extern float D_L05_00161DD8 __attribute__((sda));
extern float D_L05_00161DDC __attribute__((sda));
extern float D_L05_00161DE0 __attribute__((sda));
extern float D_L05_00161DE4 __attribute__((sda));
extern float approach_angle(float *, float, float *, float, float,
                            float) __asm__("FUN_L00_0025be00");

void FUN_L05_0030f408(char *moby, float turn_scale, float speed_scale) {
    char *data = (char *)MOBY(moby)->pvars;
    struct Hero *game = &hero;
    float offset[4];
    float horizontal;
    float vertical;
    float angle0;
    float angle1;
    float target0;
    float target1;
    float rate0;
    float rate1;
    float limit;
    float dot0;
    float dot1;

    if ((char *)game->ground_moby == moby && game->air_frames.s == 0) {
        subtract_vector_xyz(offset, &game->motion.pos, &MOBY(moby)->pos);
        dot0 = dot_vectors_xyz(offset, &MOBY(moby)->unkC0);
        dot1 = dot_vectors_xyz(offset, &MOBY(moby)->unkD0);
        horizontal = turn_scale * dot0;
        vertical = -turn_scale * dot1;
    } else {
        horizontal = 0.0f;
        vertical = 0.0f;
    }

    *(float *)(data + 0x98) = fast_add_rotations(*(float *)(data + 0x98), *(float *)(data + 0xa0));
    *(float *)(data + 0x9c) = fast_add_rotations(*(float *)(data + 0x9c), *(float *)(data + 0xa4));
    angle0 = fast_sin(*(float *)(data + 0x98));
    target0 = fast_add_rotations(vertical, angle0 * turn_scale * D_L05_00161DD8);
    angle1 = fast_sin(*(float *)(data + 0x9c));
    target1 = fast_add_rotations(horizontal, angle1 * turn_scale * D_L05_00161DD8);

    rate0 = D_L05_00161DDC * speed_scale * 0.017453292f * frame_time_sq;
    rate1 = D_L05_00161DE0 * speed_scale * 0.017453292f * frame_time_sq;
    limit = D_L05_00161DE4 * 0.017453292f * frame_time;
    approach_angle(&MOBY(moby)->rot.x, target0, (float *)(data + 0x90), rate0, rate1, limit);
    approach_angle(&MOBY(moby)->rot.y, target1, (float *)(data + 0x94),
                   D_L05_00161DDC * speed_scale * 0.017453292f * frame_time_sq,
                   D_L05_00161DE0 * speed_scale * 0.017453292f * frame_time_sq,
                   D_L05_00161DE4 * 0.017453292f * frame_time);
}
INCLUDE_ASM("config/us/overlays/asm/FUN_L05_0030f5c8.s", FUN_L05_0030f5c8);

struct GateVars {
    s32 trigger;   /* D_L05_0015FFD8 index of the moby whose byte 0xBC opens it */
    s32 riseTimer;
    s32 swingTimer;
    f32 topZ;
    f32 riseSpeed;
    f32 swingSpeed;
};

extern float D_L05_00161E80 __attribute__((sda));
extern float D_L05_00161E84 __attribute__((sda));
extern float D_L05_00161E88 __attribute__((sda));
extern float D_L05_00161E8C __attribute__((sda));
extern float D_L05_00161E90 __attribute__((sda));
extern float D_L05_00161E94 __attribute__((sda));
extern int gate_mobys_314eb0 __asm__("D_L05_0015FFD8");
extern float advance_accelerated_scalar(float, float, float, float, float *,
                                        float *) __asm__("FUN_00213f38");
extern int gate_tick_314eb0(s32 *) __asm__("FUN_001f9740");
extern float FUN_001f99c0(float);
extern int func_0022ED80_i(int, int, void *) __asm__("FUN_0022da68");
extern float FUN_L00_0025be00(float *, float *, float, float, float, float);

/* Gate: waits for its trigger moby, then rises to topZ and swings its yaw back to 0, with sounds per class. */
void FUN_L05_00314eb0(struct Moby *m) {
    struct GateVars *d = (struct GateVars *)m->pvars;
    struct Moby *t;

    switch (m->state) {
    case 0:
        d->topZ = m->pos.z + 1.0f;
        m->state = 1;
        m->pos.z -= 8.0f;
        break;
    case 1:
        t = (struct Moby *)((d->trigger << 8) + gate_mobys_314eb0);
        if (t->unkBC == 1) {
            m->state = 2;
            break;
        }
        if (t->unkBC == 2) {
            m->pos.z = d->topZ;
            m->state = 3;
            m->rot.y = 0.0f;
        }
        break;
    case 2:
        if (gate_tick_314eb0(&d->riseTimer)) {
            advance_accelerated_scalar(d->topZ, D_L05_00161E80 * frame_time_sq, D_L05_00161E84 * frame_time_sq,
                                       D_L05_00161E88 * frame_time, &m->pos.z, &d->riseSpeed);
            if (m->oclass == 0x355 && FUN_001f99c0(m->pos.z - d->topZ) < 3.0f &&
                3.0f < FUN_001f99c0(d->topZ - m->pos.z + d->riseSpeed))
                func_0022ED80_i(0, 0, m);
        }
        if (gate_tick_314eb0(&d->swingTimer)) {
            FUN_L00_0025be00(&m->rot.y, &d->swingSpeed, 0.0f, D_L05_00161E8C * 0.017453292f * frame_time_sq,
                             D_L05_00161E90 * 0.017453292f * frame_time_sq,
                             D_L05_00161E94 * 0.017453292f * frame_time);
            if (m->rot.y == 0.0f)
                m->state = 3;
        } else if (d->swingTimer == 1 && m->oclass == 0x354) {
            func_0022ED80_i(0, 0, m);
        }
        break;
    }
}
/* pvars of the 0x357 emitter: once woken it sprays particles along its facing (unkC0) that fall to the
   floor height of its D_L05_001612D0 row and splash there, and keeps the shared voice at the emitter nearest D_L05_001671C0. */
struct EmitterVars {
    s32 unk0;
    s32 floor;   /* row of D_L05_001612D0 */
    s32 trigger; /* D_L05_0015FFD8 index of the moby whose byte 0xBC wakes it, -1: none */
    s32 *voice;  /* voice slot shared by the emitters, -1: none */
    s32 age;     /* frames since it started spraying */
};

/* D_0013E550 seen from slot n (0x70 bytes per slot) */
struct VoiceSlot {
    u8 pad0[0x88];
    struct Moby *owner;
    u8 pad8C[4];
    Vec4f pos;
};

/* 0x1190-byte rows; word 8 is the floor height the emitter particles land on */
struct FloorRow {
    u8 pad0[8];
    f32 z;
    u8 padC[0x1190 - 0xC];
};

extern float FUN_001f9988(float);
extern float FUN_001f9dc8(float);
extern float FUN_001f9de0(float);
extern float random_float_between(float, float) __asm__("FUN_002132a8");
extern s32 random_integer_below(s32) __asm__("FUN_00213260");
extern void FUN_L01_0026e0e0(int, int);
extern void FUN_L05_0029be70(float, float, float, void *, void *, int, int);
extern void FUN_L00_002718d0(float, float, void *, void *, void *);
extern unsigned char D_0014C050[][16];
extern struct Moby *D_L05_0015FFD8;
extern struct FloorRow *D_L05_001612D0;
extern char D_L05_0015F580[] __attribute__((section(".sdata")));
extern int D_L05_00161E98 __attribute__((sda));
extern int D_L05_00161E9C __attribute__((sda));
extern float D_L05_00161EA0 __attribute__((sda));
extern float D_L05_00161EA4 __attribute__((sda));
extern float D_L05_00161EA8 __attribute__((sda));
extern float D_L05_00161EAC __attribute__((sda));
extern float D_L05_00161EB0 __attribute__((sda));
extern float D_L05_00161EB4 __attribute__((sda));
extern float D_L05_00161EB8 __attribute__((sda));
extern float D_L05_00161EBC __attribute__((sda));

void FUN_L05_003150f0(struct Moby *m) {
    float v[4];
    float w[4];
    float u[4];
    struct EmitterVars *d = (struct EmitterVars *)m->pvars;
    float floor;
    float lim;
    float a, b, c;
    float scale;
    int kind;
    int big;
    int i;
    unsigned char state;

    if (d == 0) {
        return;
    }
    switch (state = m->state) {
    case 0:
        if (D_0014C050[current_level_index][m->unkB0] != 0xFF) {
            m->state = 1;
        } else {
            m->state = 3;
        }
        break;
    case 1:
        if (d->trigger >= 0 && D_L05_0015FFD8[d->trigger].unkBC != 0) {
            FUN_L01_0026e0e0(m->group, 2);
        }
        break;
    case 2:
        d->age++;
        if (FUN_001f9b48(&m->pos, D_L05_001671C0) < 64.0f) {
            struct Moby *o;
            if (*d->voice >= 0 && (o = ((struct VoiceSlot *)(D_0013E550 + *d->voice * 0x70))->owner) != 0 &&
                o->oclass == 0x357) {
                if (o != m && (o->state != state || FUN_001f9b48(&m->pos, D_L05_001671C0) <
                                                         FUN_001f9b48(&o->pos, D_L05_001671C0))) {
                    FUN_001f9bf8(v, &m->unkC0, 2.5f);
                    add_vector_xyz(&((struct VoiceSlot *)(D_0013E550 + *d->voice * 0x70))->pos, v, &m->pos);
                    ((struct VoiceSlot *)(D_0013E550 + *d->voice * 0x70))->owner = m;
                }
            } else {
                *d->voice = allocate_voice_for_target_entry(0, 0xD, m);
                if (*d->voice >= 0) {
                    FUN_001f9bf8(v, &m->unkC0, 2.5f);
                    add_vector_xyz(&((struct VoiceSlot *)(D_0013E550 + *d->voice * 0x70))->pos, v, &m->pos);
                }
            }
        }
        floor = D_L05_001612D0[d->floor].z;
        if (m->pos.z < floor) {
            m->state = 3;
        }
        for (i = 0; (float)i < D_L05_00161EB8; i++) {
            big = 1;
            if (D_L05_00161EBC < random_float_between(0.0f, 100.0f)) {
                big = 0;
            }
            lim = D_L05_00161EAC;
            if (!big) {
                lim = D_L05_00161EB0;
            }
            qcopy(v, &m->pos);
            FUN_001f9bf8(u, &m->unkD0, random_float_between(-D_L05_00161EB4, D_L05_00161EB4));
            add_vector_xyz(v, v, u);
            a = random_float_between(lim, D_L05_00161EA8);
            b = random_float_between(lim, D_L05_00161EA8);
            c = random_float_between(lim, D_L05_00161EA8);
            if (a < b) {
                a = b;
            }
            if (a < c) {
                a = c;
            }
            FUN_001f9bf8(w, &m->unkC0, a * frame_time);
            if (big) {
                scale = D_L05_00161EA0;
                kind = D_L05_00161E98;
                v[2] += D_L05_00161EB4 - scale + random_float_between(-0.4f, 0.4f);
            } else {
                scale = D_L05_00161EA4;
                kind = D_L05_00161E9C;
                v[2] += D_L05_00161EB4 - scale + 0.4f;
            }
            FUN_L05_0029be70(scale * random_float_between(0.8f, 1.2f), floor, frame_time_sq * 10.0f, v, w, kind,
                             big);
            if (random_integer_below(2)) {
                /* fall time from the emitter to the floor */
                float t = FUN_001f9988(2.0f * (m->pos.z - floor) / (frame_time_sq * 10.0f));
                if (t < (float)d->age) {
                    float s = t * (frame_time * 4.0f);
                    float ang = random_angle_radians();
                    float r = random_float_between(0.0f, 1.25f);
                    FUN_001f9a68(v, &m->unkC0, s);
                    add_vector_xyz(v, v, &m->pos);
                    v[0] += FUN_001f9dc8(ang) * r;
                    v[1] += FUN_001f9de0(ang) * r;
                    v[2] = floor + 0.05f;
                    FUN_L00_002718d0(random_float_between(1.0f, 1.5f), random_integer_below(2) ? 2.0f : -2.0f, v,
                                     D_L05_0015F580, &D_L05_001612D0[d->floor].z);
                }
            }
        }
        break;
    }
}
/* pvars of the lift: it rides between two heights with the hero standing on it. */
typedef struct {
    u8 pad0[0x20];
    char rider[0x40]; /* 0x20: carried-object state for FUN_L00_00260738 */
    f32 top;          /* 0x60 */
    f32 bottom;       /* 0x64 */
    s32 marker;       /* 0x68: marker ring in D_L05_001B0930 and camera id, -1: none */
    s32 pose;         /* 0x6C: index into D_L05_001600EC */
    f32 progress;     /* 0x70: 0 at the bottom, 1 at the top */
    s32 sound;        /* 0x74: voice slot, -1: none */
    f32 fade;         /* 0x78 */
    s32 timer;        /* 0x7C */
    f32 phase;        /* 0x80: glow pulse angle */
    f32 base_yaw;     /* 0x84 */
    f32 speed;        /* 0x88 */
} LiftVars;

typedef struct {
    u8 pad0[0x70];
    Vec4f rot; /* 0x70: z: yaw at the top */
} LiftPose;

typedef struct {
    u32 handle;
    u8 state;
    u8 pad5[0x13];
    struct Moby *owner; /* 0x18 */
    u8 pad1C[0x54];
} LiftVoice;

typedef struct {
    u8 header[0x70];
    LiftVoice voices[30];
} LiftVoicePool;

/* The pool seen from slot n: its voice field is voices[n]. */
typedef struct {
    u8 header[0x70];
    LiftVoice voice;
} LiftVoiceWindow;

extern LiftVoicePool voice_pool __asm__("D_0013E550");
extern u16 D_0014162A __attribute__((section(".data")));
extern f32 D_L05_0015F3FC;
extern LiftPose *D_L05_001600EC_l __asm__("D_L05_001600EC");

extern void scale_vector_xyz(void *, void *, f32) __asm__("FUN_001f9a68");
extern void add_vector_xyz(void *, void *, void *) __asm__("FUN_001f9a10");
extern f32 random_angle_radians(void) __asm__("FUN_00213308");
extern f32 approach_value(f32 *, f32, f32) __asm__("FUN_00213ed8");
extern f32 approach_with_speed(f32 *, f32 *, f32, f32, f32, f32) __asm__("FUN_00213f38");
extern int FUN_L00_0028d8c0(void *, int);
extern s32 allocate_voice_for_target_entry(s32, s32, struct Moby *) __asm__("FUN_0022da68");
extern void release_voice_slot(s32) __asm__("FUN_0022d798");
extern f32 fast_add_rotations(f32, f32) __asm__("FUN_001fa580");
extern f32 fast_subtract_rotations(f32, f32) __asm__("FUN_001fa5c8");
extern f32 FUN_001f99c0(f32);
extern f32 FUN_001f9b80(void *, void *);
extern s32 truncate_float_to_s32(f32) __asm__("FUN_001fa6d0");
extern s32 scale_game_frames(s32) __asm__("FUN_001f96f8");
extern s32 tick_countdown_32_alt(s32 *) __asm__("FUN_001f9740");
extern void FUN_L00_00260738(char *a, void *b, void *c, void *d);
extern void FUN_L00_002ea9d8(void *);
extern void FUN_L00_002eaa30(void *);
extern void FUN_L00_002eaaa0(void *, void *, s32, s32, s32);
extern void FUN_L00_002eac18(s32);
extern void lift_camera_view(void *, void *, void *) __asm__("FUN_L05_00315ee0");
extern void place_marker_ring(void *) __asm__("FUN_L05_00315f70");

void FUN_L05_003156d0(struct Moby *moby) {
    LiftVars *vars = (LiftVars *)moby->pvars;
    Vec4 delta;
    Vec4 rot;
    Vec4 eye;
    Vec4 look;
    f32 scale;
    f32 accel;
    f32 max_speed;
    f32 target;
    s32 level;

    scale_vector_xyz(&delta, &moby->pos, -1.0f);
    qcopy(&rot, &moby->rot);
    switch (moby->state) {
    case 0:
        vars->phase = random_angle_radians();
        vars->sound = -1;
        vars->base_yaw = moby->rot.z;
        moby->state = 3;
        break;
    case 1:
        D_0014162A = vars->marker;
        approach_value(&vars->fade, 1.0f, 0.133f);
        D_L05_0015F3FC = vars->fade;
        if (vars->fade == 1.0f) {
            lift_camera_view(moby, &eye, &look);
            FUN_L00_002eaaa0(&eye, &look, 1, 0, 0);
            moby->state = moby->unkBC;
            moby->unkBC = 1;
        }
        break;
    case 2:
    case 3:
        if (!FUN_L00_0028d8c0(moby, vars->sound)) {
            vars->sound = allocate_voice_for_target_entry(0, 4, moby);
        }
        if (moby->unkBC) {
            D_0014162A = vars->marker;
            approach_value(&vars->fade, 0.0f, 0.133f);
            D_L05_0015F3FC = vars->fade;
            lift_camera_view(moby, &eye, &look);
            FUN_L00_002ea9d8(&eye);
            FUN_L00_002eaa30(&look);
            scale = 1.0f / (vars->top - vars->bottom);
            accel = frame_time * (moby->unkBC ? 6.0f : 16.0f) * scale;
            max_speed = frame_time_sq * (moby->unkBC ? 6.0f : 16.0f) * scale;
        } else {
            accel = frame_time;
            max_speed = frame_time_sq;
        }
        target = moby->state == 2 ? 1.0f : 0.0f;
        approach_with_speed(&vars->progress, &vars->speed, target, max_speed, max_speed, accel);
        moby->pos.z = (vars->top - vars->bottom) * vars->progress + vars->bottom;
        moby->rot.z = fast_subtract_rotations(D_L05_001600EC_l[vars->pose].rot.z, vars->base_yaw) * vars->progress;
        moby->rot.z = fast_add_rotations(moby->rot.z, vars->base_yaw);
        if (FUN_001f99c0(vars->progress - target) < 0.01f) {
            vars->timer = scale_game_frames(120);
            if (vars->sound != -1) {
                LiftVoiceWindow *window = (LiftVoiceWindow *)((u8 *)&voice_pool + vars->sound * sizeof(LiftVoice));
                if (window->voice.owner == moby && window->voice.state != 0) {
                    release_voice_slot(vars->sound);
                }
            }
            vars->sound = -1;
            if (vars->speed > 0.00125f) {
                vars->speed = 0.00125f;
            } else if (vars->speed < -0.00125f) {
                vars->speed = -0.00125f;
            }
            if (moby->unkBC) {
                if (moby->state == 2) {
                    moby->state = 6;
                } else {
                    moby->state = 7;
                }
            } else {
                if (moby->state == 2) {
                    moby->state = 4;
                } else {
                    moby->state = 5;
                }
            }
        }
        break;
    case 6:
    case 7:
        if (FUN_L00_0028d8c0(moby, vars->sound)) {
            release_voice_slot(vars->sound);
            vars->sound = -1;
        }
        if (vars->timer > scale_game_frames(30) || FUN_001f9b80(&hero.motion.pos, &moby->pos) > 0.5f) {
            tick_countdown_32_alt(&vars->timer);
        }
        if (hero.ground_moby != moby) {
            FUN_L00_002eac18(1);
            if (moby->state == 7) {
                moby->state = 5;
            } else {
                moby->state = 4;
            }
            break;
        }
        if (vars->timer != 0) {
            break;
        }
        vars->phase = fast_add_rotations(vars->phase, frame_time * 6.2831855f);
        level = truncate_float_to_s32((FUN_001f9de0(vars->phase) * 4.0f - 3.0f) * 128.0f);
        if (level > 0x80) {
            level = 0x80;
        } else if (level < 0x20) {
            level = 0x20;
        }
        moby->unk90 = 0x80000000 | (level << 16) | (level << 8) | level;
        if (hero.ground_moby == moby && hero.air_frames.s == 0 && FUN_001f9b80(&hero.motion.pos, &moby->pos) < 0.5f) {
            allocate_voice_for_target_entry(1, 0, moby);
            moby->unk90 = 0x80208020;
            if (moby->state == 7) {
                moby->state = 2;
            } else {
                moby->state = 3;
            }
        }
        break;
    case 4:
    case 5:
        vars->phase = fast_add_rotations(vars->phase, frame_time * 6.2831855f);
        level = truncate_float_to_s32((FUN_001f9de0(vars->phase) * 4.0f - 3.0f) * 128.0f);
        if (level > 0x80) {
            level = 0x80;
        } else if (level < 0x20) {
            level = 0x20;
        }
        moby->unk90 = 0x80000000 | (level << 16) | (level << 8) | level;
        if (hero.ground_moby == moby && hero.air_frames.s == 0 && FUN_001f9b80(&hero.motion.pos, &moby->pos) < 0.5f) {
            allocate_voice_for_target_entry(1, 0, moby);
            if (vars->marker != -1) {
                place_marker_ring(moby);
            }
            moby->unk90 = 0x80208020;
            if (moby->state == 5) {
                moby->unkBC = 2;
            } else {
                moby->unkBC = 3;
            }
            moby->state = 1;
            vars->fade = 0.0f;
        } else if (moby->state == 4) {
            f32 dist = FUN_001f9b80(&moby->pos, &hero.motion.pos);
            if (FUN_001f99c0(hero.ground_z.f - vars->bottom) < 2.0f && dist < 32.0f && dist > 5.0f) {
                moby->unkBC = 0;
                moby->state = 3;
            }
        } else if (moby->state == 5) {
            f32 dist = FUN_001f9b80(&moby->pos, &hero.motion.pos);
            if (FUN_001f99c0(hero.ground_z.f - vars->top) < 2.0f && dist < 32.0f && dist > 5.0f) {
                moby->unkBC = 0;
                moby->state = 2;
            }
        }
        break;
    }
    add_vector_xyz(&delta, &delta, &moby->pos);
    FUN_L00_00260738(vars->rider, &delta, &rot, &moby->rot);
}
#define NOT_SDA

#define MACRO_ADDR

/* Ported from rac1-decomp (src/overlays/l05_rilgar/vendor_0030EB68.c: func_L05_003173A8), where it is exact; names translated to the US level program. */

extern short D_L05_00161EC0_d __asm__("D_L05_00161EC0") __attribute__((sda));
extern short D_L05_00161EC4_d __asm__("D_L05_00161EC4") __attribute__((sda));
extern short D_L05_00161EC8_d __asm__("D_L05_00161EC8") __attribute__((sda));
extern void clear_u64_value(void *) __asm__("FUN_001f99f8");
extern void FUN_001f9a10(void *, void *, void *);
extern void FUN_001f9bf8(void *, void *, float);

void FUN_L05_00315ee0(char *a, char *b, char *c) {
    float t;
    FUN_001f9bf8(b, a + 0xC0, *(float *)&D_L05_00161EC8_d);
    FUN_001f9a10(b, b, a + 0x10);
    *(float *)(b + 8) = *(float *)(b + 8) + *(float *)&D_L05_00161EC0_d;
    clear_u64_value(c);
    t = *(float *)&D_L05_00161EC4_d;
    *(float *)(c + 8) = *(float *)(a + 0x48);
    *(float *)(c + 4) = t * DEG_TO_RAD;
}
/* Ported from rac1-decomp (src/overlays/l05_rilgar/vendor_0030EB68.c: func_L05_00317438), where it is exact; names translated to the US level program. */

extern char *D_L05_001B0930[];
extern float FUN_001fa580(float, float);

void FUN_L05_00315f70(char *moby) {
    int i = 0;
    char *data = *(char **)(moby + 0x78);
    char *tab = D_L05_001B0930[*(int *)(data + 0x68)];
    float ang = 0.0f;
    float step = 6.28318f / (float)(*(int *)tab - 1);
    for (; i < *(int *)tab; i++) {
        char *v = tab + 0x10 + i * 16;
        *(float *)v = FUN_001f9dc8(ang) * 3.5f;
        *(float *)(v + 4) = FUN_001f9de0(ang) * 3.5f;
        *(int *)(v + 8) = 0;
        FUN_001f9a10(v, v, moby + 0x10);
        ang = FUN_001fa580(ang, step);
    }
}
/* Ported from rac1-decomp (src/overlays/l05_rilgar/vendor_0030EB68.c: func_L05_00317538), where it is exact; names translated to the US level program. */

extern char D_L05_001671C0[];
extern char D_L05_00211B20[];
extern int is_point_inside_clip_volume_alt(void *, int) __asm__("FUN_00214720");
extern void FUN_L03_00291918(char *);

void FUN_L05_00316070(char *moby) {
    int *p = *(int **)(moby + 0x78);
    int i;
    int none = 1;
    for (i = 0; i < 8; p++, i++) {
        if (*p == -1)
            continue;
        if (is_point_inside_clip_volume_alt(D_L05_001671C0, *p) != 0) {
            none = 0;
            break;
        }
    }
    if (none)
        FUN_L03_00291918(D_L05_00211B20);
}
/* Updates the pulsing marker: spawns it, then each frame animates its height and queues the draw. */
extern char D_0013E533[];
extern char D_L05_00211B28[];
extern float fast_sin(float) __asm__("func_001F9DE0");
extern int D_L05_0015F5CC_c __asm__("D_L05_0015F5CC");
extern void FUN_L02_002a40d0(void *, float);
void FUN_L05_00316070_c(char *moby) __asm__("FUN_L05_00316070");
void enqueue_callback_list_1(int arg0, int arg1) __asm__("FUN_001f4600");
extern void func_L05_00317538_3175D8(void) __asm__("FUN_L05_00316070");
extern float D_L05_00211E60_3175D8[] __asm__("D_L05_00211B20");

void FUN_L05_00316110(char *moby) {
    switch ((unsigned char)moby[0x20]) {
    case 0:
        FUN_L02_002a40d0(D_L05_00211E60_3175D8, 1.0f);
        moby[0x20] = 1;
        ((unsigned char *)moby)[0x30] = 0xFF;
        break;
    case 1:
        if (hero.state.control_mode == 0x16) {
            D_L05_00211E60_3175D8[2] =
                fast_sin((float)(D_L05_0015F5CC_c % 360) * 0.017444444f - 3.14f) * 0.25f + 61.5f;
        } else {
            D_L05_00211E60_3175D8[2] =
                fast_sin((float)(D_L05_0015F5CC_c % 360) * 0.017444444f - 3.14f) * 0.25f + 59.5f;
        }
        enqueue_callback_list_1(func_L05_00317538_3175D8, moby);
        break;
    }
}
extern void attach_manipulator(void *, int, void *) __asm__("FUN_0020cb10");
extern void FUN_L00_001fff28(void *, int, float);
extern float vector_length_xyz(void *) __asm__("FUN_001f9af0");
extern float FUN_001f9b48(void *, void *);
extern char *D_001413D0_316258 __asm__("D_001413D0") __attribute__((section(".data")));

void FUN_L05_00316258(char *moby) {
    char *data = *(char **)(moby + 0x78);
    float target[4];
    float delta[4];
    float stopped;

    switch (*(u8 *)(moby + 0x20)) {
    case 0:
        if (*(int *)(data + 0x50) != 0) {
            *(float *)(moby + 0x40) = 3.1415927f;
            *(float *)(moby + 0x18) += 4.0f;
        }
        qcopy(data, moby + 0x10);
        attach_manipulator(moby, 0, data + 0x10);
        if (*(int *)(data + 0x54) != 0) {
            *(float *)(data + 0x60) = 0.0f;
            *(u8 *)(moby + 0x20) = 2;
            if (*(int *)(data + 0x50) != 0)
                FUN_001f9a68(target, moby + 0xD0, 2.0f);
            else
                FUN_001f9a68(target, moby + 0xD0, -2.0f);
            add_vector_xyz(moby + 0x10, moby + 0x10, target);
        } else {
            *(u8 *)(moby + 0x20) = 1;
            *(float *)(data + 0x60) = 0.5934119f;
            FUN_L00_001fff28(data + 0x20, 0, 0.5934119f);
        }
        *(long long *)(moby + 0x38) = *(long long *)(D_001413D0_316258 + 0x38);
        break;
    case 1:
    case 2:
        {
            u8 trigger = ((u8 *)*(int *)&D_L05_0015FFD8_d)[*(int *)(data + 0x58) * 256 + 0xBC];
            if (trigger == 0)
                return;
            if (*(u8 *)(moby + 0x20) == 2 && trigger != 2) {
                *(u8 *)(moby + 0x20) = 4;
                break;
            }
            if (*(u8 *)(moby + 0x20) != 1)
                return;
            allocate_voice_for_target_entry(0, 0, moby);
            *(u8 *)(moby + 0x20) = 6;
            return;
        }
    case 5:
    case 6:
        {
            float end;
            float approach;
            if (*(u8 *)(moby + 0x20) == 5) {
                end = 0.5934119f;
                approach = 1.1868238f;
            } else {
                end = 0.0f;
                approach = -0.5934119f;
            }
            FUN_L00_0025be00((float *)(data + 0x60), (float *)(data + 0x64), approach,
                              frame_time_sq * 4.1887903f, frame_time_sq * 4.1887903f,
                              frame_time * 12.566371f);
            if (*(float *)(data + 0x60) > 0.5934119f || *(float *)(data + 0x60) < 0.0f) {
                if (*(float *)(data + 0x60) > 0.5934119f)
                    *(float *)(data + 0x60) = 0.5934119f;
                else if (*(float *)(data + 0x60) < 0.0f)
                    *(float *)(data + 0x60) = 0.0f;
                if (*(u8 *)(moby + 0xBC) == 0) {
                    *(u8 *)(moby + 0xBC) = 1;
                    *(float *)(data + 0x64) *= -0.33f;
                } else if (*(float *)(data + 0x60) == end) {
                    if (*(u8 *)(moby + 0x20) == 5)
                        *(u8 *)(moby + 0x20) = 7;
                    else
                        *(u8 *)(moby + 0x20) = 3;
                }
            }
            FUN_L00_001fff28(data + 0x20, 0, *(float *)(data + 0x60));
        }
        break;
    case 3:
    case 4:
        if (*(u8 *)(moby + 0x20) == 3) {
            FUN_001f9a68(target, moby + 0xD0, -1.9f);
            add_vector_xyz(target, data, target);
        } else {
            qcopy(target, data);
        }
        subtract_vector_xyz(delta, target, moby + 0x10);
        stopped = 0.0f;
        advance_accelerated_scalar(vector_length_xyz(delta), frame_time_sq * 6.0f,
                                   frame_time_sq * 12.0f, frame_time * 10.0f,
                                   &stopped, (float *)(data + 0x5C));
        subtract_vector_xyz(delta, target, moby + 0x10);
        FUN_001f9bf8(delta, delta, *(float *)(data + 0x5C));
        add_vector_xyz(moby + 0x10, moby + 0x10, delta);
        if (!(FUN_001f9b48(moby + 0x10, target) < 0.0001f))
            return;
        if (*(u8 *)(moby + 0x20) == 3) {
            allocate_voice_for_target_entry(1, 0, moby);
            *(u8 *)(moby + 0x20) = 7;
            return;
        }
        *(u8 *)(moby + 0x20) = 5;
        break;
    }
}
#ifndef NON_MATCHING
INCLUDE_ASM("config/us/overlays/asm/FUN_L05_003166a0.s", FUN_L05_003166a0);
#else
void FUN_L05_003166a0(struct Moby *moby) {
    int *data = (int *)moby->pvars;

    switch (moby->state) {
    case 0:
        if (data[0] != 0)
            moby->flags |= 0x8000;
        moby->state = 1;
        *(float *)&data[3] = moby->rot.z;
        if (data[0] != 0)
            moby->rot.z = fast_subtract_rotations(moby->rot.z, 1.5707964f);
        else
            moby->rot.z = fast_add_rotations(moby->rot.z, 1.5707964f);
        /* fall through */
    case 1:
        if (((unsigned char *)*(int *)&D_L05_0015FFD8_d)[data[2] * 256 + 0xBC] != 0) {
            func_0022ED80_i(0, 0, moby);
            moby->state = 2;
        }
        break;
    case 2: {
        float target;
        if (data[0] != 0)
            target = fast_subtract_rotations(*(float *)&data[3], 0.6981317f);
        else
            target = fast_add_rotations(*(float *)&data[3], 0.6981317f);
        FUN_L00_0025be00(&moby->rot.z, (float *)&data[1], target,
                          frame_time_sq * 12.566371f, frame_time_sq * 12.566371f,
                          frame_time * 12.566371f);
        break;
    }
    }
}
#endif
#include "sda.h"

/* Applies breast growth (D_L05_00161ED0) and big-head manipulators to
 * matching-class cutscene instances of the hoverboard girl. */
/* Ported from rac1-decomp (src/overlays/l05_rilgar/vendor_0030EB68.c: func_L05_00317E58), where it is exact; names translated to the US level program. */

typedef struct {
    char pad0[0x44];
    short n;
    char pad1[0x132];
    char *m[1];
} G;

extern G D_L05_0016CC60;
extern int D_L05_0015F5C4;
extern short D_L05_00161ED0_d __asm__("D_L05_00161ED0") __attribute__((sda));
extern unsigned char D_0015EDB0[] MACRO_ADDR;
extern unsigned char D_L05_0017C8A0[];
extern void FUN_L05_00316810(char *, int);
extern void attach_manipulator(void *arg0, s32 arg1, void *arg2) __asm__("FUN_0020cb10");

void FUN_L05_00316990(char *arg) {
    if (D_L05_0015F5C4 == 2 && (D_0015EDB0[0] != 0 || *(int *)&D_L05_00161ED0_d != 0)) {
        int i;
        for (i = 0; i < D_L05_0016CC60.n; i++) {
            char *moby = D_L05_0016CC60.m[i];
            if (*(short *)(moby + 0xA6) == *(short *)(arg + 0xA6)) {
                if (D_0015EDB0[0] != 0) {
                    unsigned char *q = D_L05_0017C8A0;
                    if (q[1] == 0) {
                        attach_manipulator(moby, 0, q);
                        *(float *)(q + 0x20) = 2.75f;
                        *(float *)(q + 0x24) = 2.75f;
                        *(float *)(q + 0x28) = 2.75f;
                    }
                }
                if (*(int *)&D_L05_00161ED0_d != 0) {
                    FUN_L05_00316810(moby, *(int *)(arg + 0x78));
                }
            }
        }
    }
}
typedef struct {
    char pad00[4];
    unsigned short sub;
    char pad06[0x1A];
    void *ptr20;
    char pad24[0x1C];
    char body[0x64];
    float pitch;
    float yaw;
    char padAC[4];
    float height;
    char padB4[0xC];
    char head[0x68];
    float head_yaw;
    char pad12C[0x14];
    float target[4];
    char pad150[4];
    int idle_timer;
    int moving_timer;
    int target_timer;
} WD_c;
typedef struct {
    char pad00[0x10];
    float position[4];
    unsigned char state;
    char pad21[0x10];
    unsigned char opacity;
    char pad32[0x16];
    float yaw;
    char pad4C[7];
    unsigned char animation;
    char pad54[0x1C];
    unsigned char flags70;
    char pad71[7];
    WD_c *data;
    char pad7C[3];
    unsigned char b7F;
} WM_c;
typedef struct {
    char pad00[0x80];
    float position[4];
    char pad90[0x40];
    float aim[4];
    char padE0[0x22E];
    short disabled;
    char pad310[0x1D7C];
    int mode;
} L16WatchPlayer_c;
typedef struct {
    float target[4];
    float eye[4];
    float delta[4];
} L16WatchScratch_c;
extern void FUN_L01_002783a8_c(void *, float) __asm__("FUN_L01_002783a8");
extern void FUN_0020c828_c(void *) __asm__("FUN_0020c828");
extern void FUN_0020b178_c(int, int) __asm__("FUN_0020b178");
extern int FUN_001f9740_c(void *) __asm__("FUN_001f9740");
extern void FUN_00212f90_c(void *, int, int, int) __asm__("FUN_00212f90");
extern int FUN_001f96f8_c(int) __asm__("FUN_001f96f8");
extern float D_0015ED64_c __asm__("D_0015ED64");
extern float FUN_001f96b0_c(float) __asm__("FUN_001f96b0");
extern float FUN_001f9b80_c(void *, void *) __asm__("FUN_001f9b80");
extern float FUN_001f9e90_cf_c(float, float) __asm__("FUN_001fa688");
extern float FUN_001fa688_cf_c(float, float) __asm__("FUN_001f9e90");
extern float fast_add_rotations_c(float, float) __asm__("fast_add_rotations");
extern float fast_subtract_rotations_c(float, float) __asm__("fast_subtract_rotations");
extern float truncate_float_to_s32_cf_c(float, float) __asm__("FUN_002132a8");
extern float vector_length_xy_c(void *) __asm__("vector_length_xy");
extern float vector_length_xyz_c(void *) __asm__("vector_length_xyz");
extern int FUN_L00_00266448_c(void *, void *) __asm__("FUN_L00_00266448");
extern int FUN_L00_002668a0_c(void *, void *) __asm__("FUN_L00_002668a0");
extern int random_float_between_cf_c(float) __asm__("FUN_001fa6d0");
extern int scale_game_frames_c(int) __asm__("scale_game_frames");
extern int tick_countdown_32_c(int *) __asm__("tick_countdown_32");
extern unsigned char D_0015EDB0_b_c __asm__("D_0015EDB0");
extern void FUN_L00_002628d8_c(float, float, void *, void *, int) __asm__("FUN_L00_002628d8");
extern void add_vector_xyz_c(void *, void *, void *) __asm__("add_vector_xyz");
extern void subtract_vector_xyz_c(void *, void *, void *) __asm__("subtract_vector_xyz");
extern L16WatchPlayer_c D_0013E633_watch_c __asm__("D_0013E533");
typedef struct {
    char pad00[4];
    short sub;
    char pad06[6];
    float fC;
    char pad10[0x10];
    void *ptr20;
    char pad24[0x1C];
    char body[0x64];
    float pitch;
    float yaw;
    char padAC[4];
    float height;
    char padB4[0xC];
    char head[0x68];
    float head_yaw;
    char pad12C[0x18];
    int idle_timer;
    int moving_timer;
    int target_timer;
    float target[4];
} WD2;
extern unsigned char D_0013DD47_d __asm__("D_0013DD47") __attribute__((section(".data")));
extern char D_L05_00161EF0[];
extern void FUN_L05_00317398(void *);
extern void FUN_L02_0025c758(void *);
extern void FUN_L00_002607d0(int);
extern void build_spherical_offset(void *, float, float, float) __asm__("FUN_00214db0");

/* Watcher moby update (variant of FUN_L05_003180a0): turns its head toward the hero or a random target. */
void FUN_L05_00317470(WM_c *m) {
    L16WatchScratch_c scratch;
    WD2 *d = (WD2 *)m->data;
    float rate;
    float head_rate;
    int tracking;
    FUN_L05_00317398(m);
    if (!d)
        return;
    switch (m->state) {
    case 0:
        if (D_0013DD47_d) {
            FUN_0020c828_c(m);
            return;
        }
        d->ptr20 = (void *)D_L05_00161EF0;
        m->state = 1;
        FUN_L00_002668a0_c(m, d);
        d->fC = 3.7f;
        FUN_L02_0025c758(m);
        break;
    case 1:
        if (FUN_L00_00266448_c(m, d))
            FUN_L01_002783a8_c(m, 2.5f);
        if (d->sub == 5) {
            FUN_L00_002607d0(7);
            FUN_0020b178_c(0, -1);
            FUN_0020c828_c(m);
            return;
        }
        if (m->animation == 0 && FUN_001f9740_c(&d->idle_timer)) {
            int a = 2;
            d->idle_timer = random_float_between_cf_c(
                FUN_001f96b0_c(truncate_float_to_s32_cf_c(1200.0f, 2400.0f)));
            if (random_integer_below(2))
                a = 1;
            if (m->animation != a)
                FUN_00212f90_c(m, a, 0, FUN_001f96f8_c(10));
        } else if ((m->flags70 & 2) && m->animation) {
            FUN_00212f90_c(m, 0, 0, FUN_001f96f8_c(10));
        }
        break;
    }
    rate = 0.02f;
    head_rate = 0.3f;
    tracking = 0;
    if (m->animation == 0) {
        char *player = (char *)&D_0013E633_watch_c + 0xE9D;
        tracking = 1;
        if (FUN_001f9b80_c(m->position, player) < 8.0f &&
            FUN_001f9e90_cf_c(
                m->yaw, FUN_001fa688_cf_c(
                            ((L16WatchPlayer_c *)((char *)&D_0013E633_watch_c + 0xE1D))->aim[0] -
                                m->position[0],
                            ((L16WatchPlayer_c *)((char *)&D_0013E633_watch_c + 0xE1D))->aim[1] -
                                m->position[1])) < 1.5707964f) {
            if (vector_length_xyz_c(player + 0x80) > 0.01f)
                d->moving_timer = scale_game_frames_c(120);
            else
                tick_countdown_32_c(&d->moving_timer);
        } else if (d->moving_timer) {
            d->moving_timer = 0;
            qcopy(d->target, (char *)&D_0013E633_watch_c + 0xEED);
        }
        if (tick_countdown_32_c(&d->target_timer)) {
            float heading;
            d->target_timer = random_float_between_cf_c(
                FUN_001f96b0_c(truncate_float_to_s32_cf_c(180.0f, 300.0f)));
            heading = fast_add_rotations_c(m->yaw, truncate_float_to_s32_cf_c(-90.0f, 90.0f) *
                                                       DEG_TO_RAD);
            build_spherical_offset(d->target, 6.0f, heading,
                                   truncate_float_to_s32_cf_c(0.0f, 30.0f) * DEG_TO_RAD);
            add_vector_xyz_c(d->target, d->target, m->position);
        }
        if (d->moving_timer) {
            qcopy(scratch.target, (char *)&D_0013E633_watch_c + 0xEED);
            rate = 0.04f;
            head_rate = 0.3f;
        } else {
            qcopy(scratch.target, d->target);
        }
    }
    if (tracking) {
        float yaw;
        float pitch;
        qcopy(scratch.eye, m->position);
        scratch.eye[2] += 1.0f;
        subtract_vector_xyz_c(scratch.delta, scratch.target, scratch.eye);
        yaw = fast_subtract_rotations_c(FUN_001fa688_cf_c(scratch.delta[0], scratch.delta[1]),
                                        m->yaw);
        pitch = -FUN_001fa688_cf_c(vector_length_xy_c(scratch.delta), scratch.delta[2]);
        if (yaw > 1.5707964f)
            yaw = 1.5707964f;
        else if (yaw < -1.5707964f)
            yaw = -1.5707964f;
        if (pitch > 0.5235988f)
            pitch = 0.5235988f;
        else if (pitch < -0.5235988f)
            pitch = -0.5235988f;
        d->pitch = pitch;
        d->head_yaw = d->yaw = yaw * 0.5f;
    }
    if (D_0015EDB0_b_c)
        d->height = 2.75f;
    FUN_L00_002628d8_c(rate * D_0015ED64_c, head_rate * D_0015ED64_c, m, d->body, 0);
    FUN_L00_002628d8_c(rate * D_0015ED64_c, head_rate * D_0015ED64_c, m, d->head, 1);
}
/* Level overlay code after gameplay/vendor; generated by `decomp overlays stubs`, stubs replaced by C as functions are matched. */

#include "qcopy.h"

/* Activate the watcher and steer its body and head toward the player. */
/* Ported from rac1-decomp (src/overlays/l16_kalebo3/vendor_002A50F0.c: func_L16_002E45F8), where it is exact; names translated to the US level program. */

typedef struct {
    char pad00[4];
    unsigned short sub;
    char pad06[0x1A];
    void *ptr20;
    char pad24[0x1C];
    char body[0x64];
    float pitch;
    float yaw;
    char padAC[4];
    float height;
    char padB4[0xC];
    char head[0x68];
    float head_yaw;
    char pad12C[0x14];
    float target[4];
    char pad150[4];
    int idle_timer;
    int moving_timer;
    int target_timer;
} WD;

typedef struct {
    char pad00[0x10];
    float position[4];
    unsigned char state;
    char pad21[0x10];
    unsigned char opacity;
    char pad32[0x16];
    float yaw;
    char pad4C[7];
    unsigned char animation;
    char pad54[0x1C];
    unsigned char flags70;
    char pad71[7];
    WD *data;
    char pad7C[3];
    unsigned char b7F;
} WM;

typedef struct {
    char pad00[0x70];
    unsigned char entered;
    unsigned char mission;
} L16WatchFlags;

extern char D_0013E533[];
extern char D_L05_001671C0[];
extern unsigned char D_0013D4FF __attribute__((section(".data")));
extern f32 FUN_001f9b48(void *, void *);
extern void FUN_L00_0025a120(void *);
extern void FUN_L01_002783a8(void *, float);
extern void mark_moby_for_removal(void *) __asm__("FUN_0020c828");
extern int memcard_save_data(int, int) __asm__("FUN_0020b178");
extern f32 probe_ground_height(void *, int, float) __asm__("FUN_00213508");
extern int FUN_001f9740(void *);
extern void blend_moby_animation(void *, int, int, int) __asm__("FUN_00212f90");
extern int FUN_001f96f8(int);

extern char D_0013E633[], D_0014171B[], D_0013D24D[], D_L16_00167240[];
extern float D_L16_001D96C0[8];
extern float FUN_001f96b0(float);
extern float FUN_001f9b80(void *, void *);
extern float FUN_001f9e90_cf(float, float) __asm__("FUN_001fa688");
extern float FUN_001fa688_cf(float, float) __asm__("FUN_001f9e90");
extern float fast_add_rotations(float, float);
extern float fast_subtract_rotations(float, float);
extern float truncate_float_to_s32_cf(float, float) __asm__("FUN_002132a8");
extern float vector_length_xy(void *);
extern float vector_length_xyz(void *);
extern int FUN_L00_00203908(int, int);
extern int FUN_L00_00266448(void *, void *);
extern int FUN_L00_002668a0(void *, void *);
extern int is_point_inside_clip_volume(void *, int) __asm__("FUN_00214720");
extern int memcard_save_data(int, int) __asm__("FUN_0020b178");
extern int random_float_between_cf(float) __asm__("FUN_001fa6d0");
extern int scale_game_frames(int);
extern int tick_countdown_32(int *);
extern char D_L05_00161EF8[];
extern unsigned char D_0015EDB0_b __asm__("D_0015EDB0");
extern void FUN_L00_00216f90(void *, void *, int, int);
extern void FUN_L00_002502a0(int);
extern void FUN_L00_00260860(int, int);
extern void FUN_L00_002628d8(float, float, void *, void *, int);
extern void FUN_L00_00263d40(int, int);
extern void FUN_L02_002e0cd8(char *);
extern void add_vector_xyz(void *, void *, void *);
extern void build_spherical_offset(void *, float, float, float) __asm__("FUN_00214db0");
extern void subtract_vector_xyz(void *, void *, void *);
extern L16WatchPlayer D_0013E633_watch __asm__("D_0013E533");
extern L16WatchFlags D_0013D355_watch __asm__("D_0013D24D");

void FUN_L05_003180a0(WM *m) {
    L16WatchScratch scratch;
    WD *d = m->data;
    float rate;
    float head_rate;
    int tracking;
    FUN_L02_002e0cd8((char *)m);
    if (m->opacity) {
        if (FUN_001f9b48(m->position, D_L05_001671C0) < 40.0f) {
            FUN_L00_0025a120(m);
            m->b7F = 0x20;
        }
    }
    switch (m->state) {
    case 0:
        if (D_0013D4FF) {
            mark_moby_for_removal(m);
            return;
        }
        m->position[2] += 0.5f;
        m->position[2] = probe_ground_height(m->position, 0, 0.5f);
        d->ptr20 = (void *)D_L05_00161EF8;
        m->state = 1;
        FUN_L00_002668a0(m, d);
        break;
    case 1:
        if (FUN_L00_00266448(m, d))
            FUN_L01_002783a8(m, 2.0f);
        if ((unsigned)(d->sub - 3) < 2) {
            FUN_L00_00260860(0x17, 1);
            FUN_L00_00263d40(0x1396, -1);
            memcard_save_data(0, -1);
            mark_moby_for_removal(m);
            return;
        }
        if (m->animation == 0 && FUN_001f9740((char *)d + 0x154)) {
            d->idle_timer =
                random_float_between_cf(FUN_001f96b0(truncate_float_to_s32_cf(1200.0f, 2400.0f)));
            if (m->animation != 1)
                blend_moby_animation(m, 1, 0, FUN_001f96f8(10));
        } else if (m->animation == 1 && (m->flags70 & 2)) {
            blend_moby_animation(m, 0, 0, FUN_001f96f8(10));
        }
        break;
    }
    rate = 0.02f;
    head_rate = 0.3f;
    tracking = 0;
    if (m->animation == 0) {
        char *player = (char *)&D_0013E633_watch + 0xE9D;
        tracking = 1;
        if (FUN_001f9b80(m->position, player) < 8.0f &&
            FUN_001f9e90_cf(
                m->yaw,
                FUN_001fa688_cf(((L16WatchPlayer *)((char *)&D_0013E633_watch + 0xE1D))->aim[0] -
                                    m->position[0],
                                ((L16WatchPlayer *)((char *)&D_0013E633_watch + 0xE1D))->aim[1] -
                                    m->position[1])) < 1.5707964f) {
            if (vector_length_xyz(player + 0x80) > 0.01f)
                d->moving_timer = scale_game_frames(120);
            else
                tick_countdown_32(&d->moving_timer);
        } else if (d->moving_timer) {
            d->moving_timer = 0;
            qcopy(d->target, (char *)&D_0013E633_watch + 0xEED);
        }
        if (tick_countdown_32(&d->target_timer)) {
            float heading;
            d->target_timer =
                random_float_between_cf(FUN_001f96b0(truncate_float_to_s32_cf(180.0f, 300.0f)));
            heading =
                fast_add_rotations(m->yaw, truncate_float_to_s32_cf(-90.0f, 90.0f) * DEG_TO_RAD);
            build_spherical_offset(d->target, 6.0f, heading,
                                   truncate_float_to_s32_cf(0.0f, 30.0f) * DEG_TO_RAD);
            add_vector_xyz(d->target, d->target, m->position);
        }
        if (d->moving_timer) {
            qcopy(scratch.target, (char *)&D_0013E633_watch + 0xEED);
            rate = 0.04f;
            head_rate = 0.3f;
        } else {
            qcopy(scratch.target, d->target);
        }
    }
    if (tracking) {
        float yaw;
        float pitch;
        qcopy(scratch.eye, m->position);
        scratch.eye[2] += 1.0f;
        subtract_vector_xyz(scratch.delta, scratch.target, scratch.eye);
        yaw = fast_subtract_rotations(FUN_001fa688_cf(scratch.delta[0], scratch.delta[1]), m->yaw);
        pitch = -FUN_001fa688_cf(vector_length_xy(scratch.delta), scratch.delta[2]);
        if (yaw > 1.5707964f)
            yaw = 1.5707964f;
        else if (yaw < -1.5707964f)
            yaw = -1.5707964f;
        if (pitch > 0.5235988f)
            pitch = 0.5235988f;
        else if (pitch < -0.5235988f)
            pitch = -0.5235988f;
        d->pitch = pitch;
        d->yaw = yaw * 0.6f;
        d->head_yaw = yaw * 0.4f;
    }
    if (D_0015EDB0_b)
        d->height = 2.75f;
    FUN_L00_002628d8(rate * frame_scale_sq, head_rate * frame_scale_sq, m, d->body, 0);
    FUN_L00_002628d8(rate * frame_scale_sq, head_rate * frame_scale_sq, m, d->head, 1);
}

extern int D_L05_001612DC_318a68 __asm__("D_L05_001612DC");
extern int D_L05_001612D8_318a68[] __asm__("D_L05_001612D8") MACRO_ADDR;
extern char D_L05_001612E0_318a68[16] __asm__("D_L05_001612E0") MACRO_ADDR __attribute__((sda));
extern float D_L05_001612E8_318a68 __asm__("D_L05_001612E8");
extern float D_L05_001612EC_318a68 __asm__("D_L05_001612EC");
extern int D_L05_0015F5C4_318a68[] __asm__("D_L05_0015F5C4") MACRO_ADDR;
extern int find_318a68(void *, int) __asm__("FUN_00214720");
extern float sin_318a68(float) __asm__("FUN_001f9de0");

/* Two-state marker: arms the moby, then once its target is found copies the
 * target position and sets the bob height from the frame counter. */
void FUN_L05_00318a68(char *m) {
    int state = *(unsigned char *)(m + 0x20);
    int *v = *(int **)(m + 0x78);
    char *t;

    switch (state) {
    case 0:
        *(unsigned char *)(m + 0x20) = 1;
        *(unsigned short *)(m + 0x34) |= 1;
        *(unsigned char *)(m + 0x30) = 0xFF;
        *(int *)(m + 0x94) = 0;
        break;
    case 1:
        t = (char *)&hero.motion.pos;
        if (find_318a68(t, *v) != 0) {
            D_L05_001612D8_318a68[1] = state;
            qcopy(D_L05_001612E0_318a68, t);
            *(short *)(t + 0x15E) = 5;
            D_L05_001612EC_318a68 = 48.0f;
            *(volatile float *)&D_L05_001612E8_318a68 = sin_318a68((float)(D_L05_0015F5C4_318a68[2] % 360) * 0.017444444f - 3.14f) * 0.25f + 59.5f;
        } else {
            D_L05_001612DC_318a68 = 0;
        }
        break;
    }
}

/* Ported from rac1-decomp (src/overlays/l05_rilgar/vendor_0030EB68.c: func_L05_0031A0A8), where it is exact; names translated to the US level program. */

extern float random_angle_radians_alt(void) __asm__("FUN_00213308");
extern int D_L05_0015F5C4;
extern short D_L05_00161F08_d __asm__("D_L05_00161F08") __attribute__((sda));

void FUN_L05_00318b98(struct Moby *moby) {
    float v;
    char *data = (char *)moby->pvars;
    int g;
    moby->scale =
        moby->pclass->scale * *(float *)&D_L05_00161F08_d;
    switch (moby->state) {
    case 0:
        moby->state = 1;
        *(float *)data = random_angle_radians_alt();
        *(float *)(data + 4) = moby->pos.z;
        break;
    case 1:
        g = D_L05_0015F5C4;
        if (g == 2) {
            moby->unk31 = 0;
            moby->flags |= 1;
        } else {
            moby->unk31 = 1;
            moby->flags &= 0xFFFE;
        }
        v = FUN_001fa580(*(float *)data, frame_time * 0.87266463f);
        *(float *)data = v;
        moby->pos.z = *(float *)(data + 4) + FUN_001f9de0(v);
        break;
    }
}
/* Same source as the exact FUN_L16_002e43e0, with its moby data 8 bytes further on, an x range on the pickup test and a table test for state 6. */
typedef struct {
    char pad00[0x30];
    float position[4];
    char pad40[0x30];
    float direction[4];
} PickupPose_318c78;

extern PickupPose_318c78 *D_L05_001600EC_p __asm__("D_L05_001600EC");
extern char *FUN_L05_00319598(void *, int);
extern char D_0013CAE4[];
extern float advance_accelerated_scalar_c(float, float, float, float, float *,
                                          float *) __asm__("FUN_00213f38");
extern f32 fast_add_rotations(f32 a, f32 b) __asm__("FUN_001fa580");
extern f32 fast_subtract_rotations(f32, f32) __asm__("func_001FA5C8");
extern float D_0015ED70_c2 __asm__("D_0015ED70");
extern int FUN_L00_0028d8c0(void *, int);
extern int FUN_L05_003195f8(char *);
extern void FUN_001f9a40(void *, void *, void *, float);
extern void FUN_001f9d20(void *, void *, void *);
extern void FUN_001fa2d8(void *, void *);
extern void FUN_0022da68_c(int, int, void *) __asm__("FUN_0022da68");
extern void FUN_L00_00260738(char *a, void *b, void *c, void *d);
extern void FUN_L00_00266858(void *, int);
extern void FUN_L05_00319510(void *);
extern void FUN_L05_00319690(char *);
extern void FUN_L05_00319740(char *);
extern void FUN_L05_003198e8(char *);
void FUN_L05_00319208(void *moby_v);
extern void FUN_L05_003193a8_u(char *) __asm__("FUN_L05_003193a8");
extern void release_voice_slot(s32) __asm__("FUN_0022d798");
extern void sample_camera_path(void *, s32, void *, void *, s32, f32) __asm__("func_00214E58");
extern void subtract_vector_xyz(void *out, void *a, void *b) __asm__("FUN_001f9a28");
float absolute_float(float input) __asm__("func_001F99C0");
extern void func_00215CA8_f5848(float, int *, int, void *, float *, int) __asm__("FUN_00214e58");

void FUN_L05_00318c78(struct Moby *moby) {
    char *d = (char *)moby->pvars;
    float v00[4], v10[4], v20[4], v30[4], v40[4], v50[4], v60[4], v70[4];
    struct Hero *g;
    struct Hero *g2;
    float z;
    char *m;
    char *e;
    PickupPose_318c78 *tab;
    float *qa;
    int h;
    int s;
    qcopy(v00, &moby->pos);
    qcopy(v10, &moby->rot);
    FUN_L00_00266858(moby, (moby->flags ^ 1) & 1);
    switch (moby->state) {
    case 0:
        *(short *)(d + 0xB2) = *(short *)(d + 0xB0) = -1;
        FUN_L05_00319208(moby);
        break;
    case 1:
        g = &hero;
        if (((char *)g->ground_moby) == moby && g->air_frames.s == 0) {
            FUN_001fa2d8(v30, &moby->unkC0);
            subtract_vector_xyz(v70, &g->motion.pos, &moby->pos);
            v70[3] = 0;
            FUN_001f9d20(v70, v70, v30);
            if (absolute_float(v70[1]) < 1.2f && v70[0] < 1.0f && v70[0] > -0.75f) {
                FUN_L05_003193a8_u(moby);
                FUN_L05_00319690(moby);
                if (*(int *)(D_0013CAE4) & 0x10) {
                    moby->state = 3;
                    m = FUN_L05_00319598(moby, *(short *)(d + 0xB6));
                    if (m != 0) {
                        m[0x20] = 2;
                        *(unsigned short *)(m + 0x34) |= 1;
                        m[0x31] = 0;
                        *(int *)(m + 0x94) = 0;
                    }
                }
            }
        }
        break;
    case 3:
        advance_accelerated_scalar_c(1.0f, D_0015ED70_c2, D_0015ED70_c2, frame_time * 0.5f,
                                     (float *)(d + 0xC0), (float *)(d + 0xC4));
        qa = v30;
        s = *(int *)(d + 0x80 - (-(*(short *)(d + 0xB4) * 4)));
        tab = D_L05_001600EC_p;
        qcopy(qa, tab[s].position);
        qcopy(v50, tab[s].direction);
        z = 0.0f;
        func_00215CA8_f5848(z, *(int **)(d + 0xAC), 0, v40, v60, 0);
        FUN_001f9a40(d + 0x60, v30, v40, *(float *)(d + 0xC0));
        *(float *)(d + 0x74) = fast_add_rotations(
            fast_subtract_rotations(v60[1], v50[1]) * *(float *)(d + 0xC0), v50[1]);
        *(float *)(d + 0x78) = fast_add_rotations(
            fast_subtract_rotations(v60[2], v50[2]) * *(float *)(d + 0xC0), v50[2]);
        if (1.0f <= *(float *)(d + 0xC0)) {
            *(float *)(d + 0xC0) = z;
            *(float *)(d + 0xC4) = z;
            moby->state = 4;
        }
        break;
    case 4:
        if (FUN_L05_003195f8(moby)) {
            *(int *)(d + 0xC0) = 0;
            *(int *)(d + 0xC4) = 0;
            moby->state = 5;
        }
        break;
    case 5:
        advance_accelerated_scalar_c(1.0f, D_0015ED70_c2, D_0015ED70_c2, frame_time * 0.5f,
                                     (float *)(d + 0xC0), (float *)(d + 0xC4));
        qa = v40;
        s = *(int *)(d + 0x80 - (-(*(short *)(d + 0xB6) * 4)));
        tab = D_L05_001600EC_p;
        qcopy(qa, tab[s].position);
        qcopy(v60, tab[s].direction);
        sample_camera_path(*(int **)(d + 0xAC), 0, v30, v50, 0, (float)**(int **)(d + 0xAC));
        FUN_001f9a40(d + 0x60, v30, v40, *(float *)(d + 0xC0));
        *(float *)(d + 0x74) = fast_add_rotations(
            fast_subtract_rotations(v60[1], v50[1]) * *(float *)(d + 0xC0), v50[1]);
        *(float *)(d + 0x78) = fast_add_rotations(
            fast_subtract_rotations(v60[2], v50[2]) * *(float *)(d + 0xC0), v50[2]);
        if (1.0f <= *(float *)(d + 0xC0)) {
            *(int *)(d + 0xC0) = 0;
            *(int *)(d + 0xC4) = 0;
            moby->state = 1;
            FUN_L05_00319510(moby);
        }
        break;
    case 6:
        if (D_0014C050[current_level_index][*(int *)(d + 0xB8)] == 0xFF ||
            D_0014C050[current_level_index][*(int *)(d + 0xBC)] == 0xFF) {
            char *model = moby->pclass;
            unsigned short flags = moby->flags;
            int value = *(int *)(model + 0x10);
            moby->unk31 = 1;
            moby->unk94 = value;
            moby->flags = flags & 0xFFFE;
            moby->state = 1;
        }
        break;
    }
    FUN_L05_00319740(moby);
    if (moby->state >= 3 && moby->state <= 5) {
        g2 = &hero;
        g2->unk1F2 = 2;
        g2->unk1F4 = 2;
        FUN_L05_003198e8(moby);
        if (FUN_L00_0028d8c0(moby, *(short *)(d + 0xB2)) == 0) {
            *(short *)(d + 0xB2) = func_0022ED80_i(0, 4, moby);
        }
    } else if (FUN_L00_0028d8c0(moby, *(short *)(d + 0xB2)) != 0) {
        h = *(short *)(d + 0xB2);
        if (h != -1) {
            e = D_0013E550 + h * 0x70;
            if (*(char **)(e + 0x88) == moby && *(unsigned char *)(e + 0x74) != 0) {
                release_voice_slot(h);
            }
        }
        *(short *)(d + 0xB2) = -1;
    }
    subtract_vector_xyz(v20, &moby->pos, v00);
    FUN_L00_00260738(d + 0x20, v20, v10, &moby->rot);
}
#include "qcopy.h"
extern float func_001F9D10_19208(void *, void *) __asm__("FUN_001f9b48");
extern char *D_L05_001600EC_19208 __asm__("D_L05_001600EC");
extern int D_0015ED84_19208 __asm__("D_0015ED84");
extern unsigned char D_0014C050_19208[] __asm__("D_0014C050");

void FUN_L05_00319208(void *moby_v) {
    char *moby = moby_v;
    char *data = *(char **)(moby + 0x78);
    int *list = (int *)(data + 0x80);
    int i;
    int idx;
    char *g;
    *(short *)(data + 0xB4) = -1;
    for (i = 0; i < 5; i++) {
        if (func_001F9D10_19208(moby + 0x10, D_L05_001600EC_19208 + (list[i] << 7) + 0x30) < 1.0f) {
            *(short *)(data + 0xB4) = i;
        }
    }
    switch (*(short *)(data + 0xB4)) {
    case 2: {
        int k = D_0015ED84_19208 << 4;
        if (D_0014C050_19208[*(int *)(data + 0xB8) + k] != 0xFF &&
            D_0014C050_19208[*(int *)(data + 0xBC) + k] != 0xFF) {
            moby[0x20] = 6;
            *(unsigned short *)(moby + 0x34) = *(unsigned short *)(moby + 0x34) | 1;
            moby[0x31] = 0;
            *(int *)(moby + 0x94) = 0;
            break;
        } else {
            int v = *(int *)(*(char **)(moby + 0x24) + 0x10);
            moby[0x31] = 1;
            *(int *)(moby + 0x94) = v;
            *(unsigned short *)(moby + 0x34) = *(unsigned short *)(moby + 0x34) & 0xFFFE;
            moby[0x20] = 1;
            break;
        }
    }
    case 0:
    case 1:
    case 3:
    case 4: {
        int v = *(int *)(*(char **)(moby + 0x24) + 0x10);
        moby[0x31] = 1;
        *(int *)(moby + 0x94) = v;
        *(unsigned short *)(moby + 0x34) = *(unsigned short *)(moby + 0x34) & 0xFFFE;
        moby[0x20] = 1;
        break;
    }
    }
    {
        int *selected = list;
        selected += *(short *)(data + 0xB4);
        idx = *selected << 7;
    }
    g = D_L05_001600EC_19208;
    qcopy(data + 0x60, (void *)(idx + (int)g + 0x30));
    qcopy(data + 0x70, (void *)(idx + (int)g + 0x70));
}
/* Picks the path for the current point (five points, point 2 chosen by the table entry) and sets the travel speeds; same source as FUN_L16_002e4a58. */

void FUN_L05_003193a8(char *moby) {
    char *d = *(char **)(moby + 0x78);
    char *p;
    float inv, a, b, r;
    switch (*(short *)(d + 0xB4)) {
    case 0:
        *(char **)(d + 0xAC) = D_L05_001B0930[*(int *)(d + 0x94)];
        *(short *)(d + 0xB6) = 1;
        break;
    case 1:
        *(char **)(d + 0xAC) = D_L05_001B0930[*(int *)(d + 0x98)];
        *(short *)(d + 0xB6) = 0;
        break;
    case 2:
        if (D_0014C050[current_level_index][*(int *)(d + 0xB8)] != 0xFF) {
            *(char **)(d + 0xAC) = D_L05_001B0930[*(int *)(d + 0x9C)];
            *(short *)(d + 0xB6) = 3;
        } else {
            *(char **)(d + 0xAC) = D_L05_001B0930[*(int *)(d + 0xA4)];
            *(short *)(d + 0xB6) = 4;
        }
        break;
    case 3:
        *(char **)(d + 0xAC) = D_L05_001B0930[*(int *)(d + 0xA0)];
        *(short *)(d + 0xB6) = 2;
        break;
    case 4:
        *(char **)(d + 0xAC) = D_L05_001B0930[*(int *)(d + 0xA8)];
        *(short *)(d + 0xB6) = 2;
        break;
    }
    p = *(char **)(d + 0xAC);
    r = FUN_001f9b48(p + 0x10, p + 0x20);
    a = frame_time * 20.0f;
    b = frame_time_sq * 5.0f;
    inv = 1.0f / (r * (float)**(int **)(d + 0xAC));
    *(int *)(d + 0xC4) = 0;
    *(int *)(d + 0xC0) = 0;
    *(float *)(d + 0xD4) = a * inv;
    *(float *)(d + 0xD8) = b * inv;
}
/* Ported from rac1-decomp (src/overlays/l05_rilgar/vendor_0030EB68.c: func_L05_0031B138), where it is exact; names translated to the US level program. */

extern int D_L05_0015F5C4_c __asm__("D_L05_0015F5C4");

void FUN_L05_00319c28(char *moby) {
    if (D_L05_0015F5C4_c == 2) {
        moby[0x31] = 0;
        *(unsigned short *)(moby + 0x34) |= 1;
    } else {
        moby[0x31] = 1;
        *(unsigned short *)(moby + 0x34) &= 0xFFFE;
    }
}
